In [155]:
import numpy as np
import pandas as pd

In [156]:
df = pd.read_csv("../data/iris.csv")

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [157]:
df.shape

(150, 5)

In [158]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species            150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [159]:
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [160]:
features = df.iloc[:, :-1].to_numpy()

labels = df.iloc[:, -1].to_numpy()

In [161]:
features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [162]:
features.shape

(150, 4)

In [163]:
features.ndim

2

In [164]:
features.dtype

dtype('float64')

In [165]:
labels.shape

(150,)

In [166]:
features[0]

array([5.1, 3.5, 1.4, 0.2])

In [167]:
features[0,0]

np.float64(5.1)

In [168]:
features[-1]

array([5.9, 3. , 5.1, 1.8])

In [169]:
features[:,0]

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [170]:
features[:,0]

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [171]:
features[:,3]

array([0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 0.2, 0.2, 0.2, 0.4, 0.1, 0.2, 0.2, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 1. , 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.1, 1.3, 2.5, 1.9, 2.1, 1.8,
       2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9, 2.1, 2. , 2.4, 2.3, 1.8,
       2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1, 1.8, 1.8, 1.8, 2.1, 1.6,
       1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3, 1.9,
       2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8])

In [172]:
features[10]

array([5.4, 3.7, 1.5, 0.2])

In [173]:
features[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [174]:
features[5:10]

array([[5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [175]:
features[:,1:3]

array([[3.5, 1.4],
       [3. , 1.4],
       [3.2, 1.3],
       [3.1, 1.5],
       [3.6, 1.4],
       [3.9, 1.7],
       [3.4, 1.4],
       [3.4, 1.5],
       [2.9, 1.4],
       [3.1, 1.5],
       [3.7, 1.5],
       [3.4, 1.6],
       [3. , 1.4],
       [3. , 1.1],
       [4. , 1.2],
       [4.4, 1.5],
       [3.9, 1.3],
       [3.5, 1.4],
       [3.8, 1.7],
       [3.8, 1.5],
       [3.4, 1.7],
       [3.7, 1.5],
       [3.6, 1. ],
       [3.3, 1.7],
       [3.4, 1.9],
       [3. , 1.6],
       [3.4, 1.6],
       [3.5, 1.5],
       [3.4, 1.4],
       [3.2, 1.6],
       [3.1, 1.6],
       [3.4, 1.5],
       [4.1, 1.5],
       [4.2, 1.4],
       [3.1, 1.5],
       [3.2, 1.2],
       [3.5, 1.3],
       [3.6, 1.4],
       [3. , 1.3],
       [3.4, 1.5],
       [3.5, 1.3],
       [2.3, 1.3],
       [3.2, 1.3],
       [3.5, 1.6],
       [3.8, 1.9],
       [3. , 1.4],
       [3.8, 1.6],
       [3.2, 1.4],
       [3.7, 1.5],
       [3.3, 1.4],
       [3.2, 4.7],
       [3.2, 4.5],
       [3.1, 4.9],
       [2.3, 4. ],
       [2.8, 4.6],
       [2.8, 4.5],
       [3.3, 4.7],
       [2.4, 3.3],
       [2.9, 4.6],
       [2.7, 3.9],
       [2. , 3.5],
       [3. , 4.2],
       [2.2, 4. ],
       [2.9, 4.7],
       [2.9, 3.6],
       [3.1, 4.4],
       [3. , 4.5],
       [2.7, 4.1],
       [2.2, 4.5],
       [2.5, 3.9],
       [3.2, 4.8],
       [2.8, 4. ],
       [2.5, 4.9],
       [2.8, 4.7],
       [2.9, 4.3],
       [3. , 4.4],
       [2.8, 4.8],
       [3. , 5. ],
       [2.9, 4.5],
       [2.6, 3.5],
       [2.4, 3.8],
       [2.4, 3.7],
       [2.7, 3.9],
       [2.7, 5.1],
       [3. , 4.5],
       [3.4, 4.5],
       [3.1, 4.7],
       [2.3, 4.4],
       [3. , 4.1],
       [2.5, 4. ],
       [2.6, 4.4],
       [3. , 4.6],
       [2.6, 4. ],
       [2.3, 3.3],
       [2.7, 4.2],
       [3. , 4.2],
       [2.9, 4.2],
       [2.9, 4.3],
       [2.5, 3. ],
       [2.8, 4.1],
       [3.3, 6. ],
       [2.7, 5.1],
       [3. , 5.9],
       [2.9, 5.6],
       [3. , 5.8],
       [3. , 6.6],
       [2.5, 4.5],
       [2.9, 6.3],
       [2.5, 5.8],
       [3.6, 6.1],
       [3.2, 5.1],
       [2.7, 5.3],
       [3. , 5.5],
       [2.5, 5. ],
       [2.8, 5.1],
       [3.2, 5.3],
       [3. , 5.5],
       [3.8, 6.7],
       [2.6, 6.9],
       [2.2, 5. ],
       [3.2, 5.7],
       [2.8, 4.9],
       [2.8, 6.7],
       [2.7, 4.9],
       [3.3, 5.7],
       [3.2, 6. ],
       [2.8, 4.8],
       [3. , 4.9],
       [2.8, 5.6],
       [3. , 5.8],
       [2.8, 6.1],
       [3.8, 6.4],
       [2.8, 5.6],
       [2.8, 5.1],
       [2.6, 5.6],
       [3. , 6.1],
       [3.4, 5.6],
       [3.1, 5.5],
       [3. , 4.8],
       [3.1, 5.4],
       [3.1, 5.6],
       [3.1, 5.1],
       [2.7, 5.1],
       [3.2, 5.9],
       [3.3, 5.7],
       [3. , 5.2],
       [2.5, 5. ],
       [3. , 5.2],
       [3.4, 5.4],
       [3. , 5.1]])

In [176]:
features[20:30,2:]

array([[1.7, 0.2],
       [1.5, 0.4],
       [1. , 0.2],
       [1.7, 0.5],
       [1.9, 0.2],
       [1.6, 0.2],
       [1.6, 0.4],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.6, 0.2]])

In [177]:
features[::2]

array([[5.1, 3.5, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [4.4, 2.9, 1.4, 0.2],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.4, 3.9, 1.3, 0.4],
       [5.7, 3.8, 1.7, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.4, 1.4, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.2, 4.1, 1.5, 0.1],
       [4.9, 3.1, 1.5, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.4, 3. , 1.3, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.8, 1.6, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.9, 3.1, 4.9, 1.5],
       [6.5, 2.8, 4.6, 1.5],
       [6.3, 3.3, 4.7, 1.6],
       [6.6, 2.9, 4.6, 1.3],
       [5. , 2. , 3.5, 1. ],
       [6. , 2.2, 4. , 1. ],
       [5.6, 2.9, 3.6, 1.3],
       [5.6, 3. , 4.5, 1.5],
       [6.2, 2.2, 4.5, 1.5],
       [5.9, 3.2, 4.8, 1.8],
       [6.3, 2.5, 4.9, 1.5],
       [6.4, 2.9, 4.3, 1.3],
       [6.8, 2.8, 4.8, 1.4],
       [6. , 2.9, 4.5, 1.5],
       [5.5, 2.4, 3.8, 1.1],
       [5.8, 2.7, 3.9, 1.2],
       [5.4, 3. , 4.5, 1.5],
       [6.7, 3.1, 4.7, 1.5],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [5.8, 2.6, 4. , 1.2],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 2.9, 4.2, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [6.3, 3.3, 6. , 2.5],
       [7.1, 3. , 5.9, 2.1],
       [6.5, 3. , 5.8, 2.2],
       [4.9, 2.5, 4.5, 1.7],
       [6.7, 2.5, 5.8, 1.8],
       [6.5, 3.2, 5.1, 2. ],
       [6.8, 3. , 5.5, 2.1],
       [5.8, 2.8, 5.1, 2.4],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 2.6, 6.9, 2.3],
       [6.9, 3.2, 5.7, 2.3],
       [7.7, 2.8, 6.7, 2. ],
       [6.7, 3.3, 5.7, 2.1],
       [6.2, 2.8, 4.8, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.4, 2.8, 6.1, 1.9],
       [6.4, 2.8, 5.6, 2.2],
       [6.1, 2.6, 5.6, 1.4],
       [6.3, 3.4, 5.6, 2.4],
       [6. , 3. , 4.8, 1.8],
       [6.7, 3.1, 5.6, 2.4],
       [5.8, 2.7, 5.1, 1.9],
       [6.7, 3.3, 5.7, 2.5],
       [6.3, 2.5, 5. , 1.9],
       [6.2, 3.4, 5.4, 2.3]])

In [178]:
features[::-1]

array([[5.9, 3. , 5.1, 1.8],
       [6.2, 3.4, 5.4, 2.3],
       [6.5, 3. , 5.2, 2. ],
       [6.3, 2.5, 5. , 1.9],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.8, 3.2, 5.9, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.9, 3.1, 5.1, 2.3],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.4, 2.1],
       [6. , 3. , 4.8, 1.8],
       [6.4, 3.1, 5.5, 1.8],
       [6.3, 3.4, 5.6, 2.4],
       [7.7, 3. , 6.1, 2.3],
       [6.1, 2.6, 5.6, 1.4],
       [6.3, 2.8, 5.1, 1.5],
       [6.4, 2.8, 5.6, 2.2],
       [7.9, 3.8, 6.4, 2. ],
       [7.4, 2.8, 6.1, 1.9],
       [7.2, 3. , 5.8, 1.6],
       [6.4, 2.8, 5.6, 2.1],
       [6.1, 3. , 4.9, 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [7.2, 3.2, 6. , 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [6.3, 2.7, 4.9, 1.8],
       [7.7, 2.8, 6.7, 2. ],
       [5.6, 2.8, 4.9, 2. ],
       [6.9, 3.2, 5.7, 2.3],
       [6. , 2.2, 5. , 1.5],
       [7.7, 2.6, 6.9, 2.3],
       [7.7, 3.8, 6.7, 2.2],
       [6.5, 3. , 5.5, 1.8],
       [6.4, 3.2, 5.3, 2.3],
       [5.8, 2.8, 5.1, 2.4],
       [5.7, 2.5, 5. , 2. ],
       [6.8, 3. , 5.5, 2.1],
       [6.4, 2.7, 5.3, 1.9],
       [6.5, 3.2, 5.1, 2. ],
       [7.2, 3.6, 6.1, 2.5],
       [6.7, 2.5, 5.8, 1.8],
       [7.3, 2.9, 6.3, 1.8],
       [4.9, 2.5, 4.5, 1.7],
       [7.6, 3. , 6.6, 2.1],
       [6.5, 3. , 5.8, 2.2],
       [6.3, 2.9, 5.6, 1.8],
       [7.1, 3. , 5.9, 2.1],
       [5.8, 2.7, 5.1, 1.9],
       [6.3, 3.3, 6. , 2.5],
       [5.7, 2.8, 4.1, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.9, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.6, 2.7, 4.2, 1.3],
       [5. , 2.3, 3.3, 1. ],
       [5.8, 2.6, 4. , 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.5, 2.6, 4.4, 1.2],
       [5.5, 2.5, 4. , 1.3],
       [5.6, 3. , 4.1, 1.3],
       [6.3, 2.3, 4.4, 1.3],
       [6.7, 3.1, 4.7, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 2.7, 5.1, 1.6],
       [5.8, 2.7, 3.9, 1.2],
       [5.5, 2.4, 3.7, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.7, 2.6, 3.5, 1. ],
       [6. , 2.9, 4.5, 1.5],
       [6.7, 3. , 5. , 1.7],
       [6.8, 2.8, 4.8, 1.4],
       [6.6, 3. , 4.4, 1.4],
       [6.4, 2.9, 4.3, 1.3],
       [6.1, 2.8, 4.7, 1.2],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4. , 1.3],
       [5.9, 3.2, 4.8, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [6.2, 2.2, 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [5.6, 3. , 4.5, 1.5],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.1, 2.9, 4.7, 1.4],
       [6. , 2.2, 4. , 1. ],
       [5.9, 3. , 4.2, 1.5],
       [5. , 2. , 3.5, 1. ],
       [5.2, 2.7, 3.9, 1.4],
       [6.6, 2.9, 4.6, 1.3],
       [4.9, 2.4, 3.3, 1. ],
       [6.3, 3.3, 4.7, 1.6],
       [5.7, 2.8, 4.5, 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.9, 3.1, 4.9, 1.5],
       [6.4, 3.2, 4.5, 1.5],
       [7. , 3.2, 4.7, 1.4],
       [5. , 3.3, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.1, 3.8, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 3.5, 1.6, 0.6],
       [4.4, 3.2, 1.3, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.4, 1.5, 0.2],
       [4.4, 3. , 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [5.5, 3.5, 1.3, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5.5, 4.2, 1.4, 0.2],
       [5.2, 4.1, 1.5, 0.1],
       [5.4, 3.4, 1.5, 0.4],
       [4.8, 3.1, 1.6, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [5.2, 3.5, 1.5, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5. , 3. , 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.8, 1.5, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.5, 1.4, 0.3],
       [5.4, 3.9, 1.3, 0.4],
       [5.7, 4.4, 1.5, 0.4],
       [5.8, 4. , 1.2, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [4.8, 3. , 1.4, 0.1],
       [4.8, 3.4, 1.6, 0.2],
       [5.4, 3.7, 1.5, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.4, 2.9, 1.4, 0.2],
       [5. , 3.4, 1.5, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 3.6, 1.4, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2]])

In [179]:
features[features[:,0] > 5]

array([[5.1, 3.5, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [5.1, 3.3, 1.7, 0.5],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.8, 1.6, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [180]:
features[features[:,2] > 4]

array([[7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.6, 2.9, 4.6, 1.3],
       [5.9, 3. , 4.2, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.9, 3.2, 4.8, 1.8],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [181]:
features[(features[:,0] > 5) & (features[:,2] > 4)]

array([[7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.6, 2.9, 4.6, 1.3],
       [5.9, 3. , 4.2, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.9, 3.2, 4.8, 1.8],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [182]:
# flatten into 1 dimension

flattened_features = features.reshape(600)

print(flattened_features.shape)
print(flattened_features[:12])

(600,)
[5.1 3.5 1.4 0.2 4.9 3.  1.4 0.2 4.7 3.2 1.3 0.2]

In [183]:
flattened_features = features.reshape(-1)

In [184]:
features_300_by_2 = features.reshape(300, 2)

print(features_300_by_2.shape)
print(features_300_by_2[:5])

(300, 2)
[[5.1 3.5]
 [1.4 0.2]
 [4.9 3. ]
 [1.4 0.2]
 [4.7 3.2]]

In [185]:
features_grouped = features.reshape(50, 3, 4)

print(features_grouped.shape)
print(features_grouped[0])

(50, 3, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]

In [186]:
features_auto = features.reshape(75, -1)

print(features_auto.shape)

(75, 8)

In [187]:
print(features[0, 0])
print(flattened_features[0])

5.1
5.1

In [188]:
print(features.size)
print(features_300_by_2.size)
print(features_grouped.size)

600
600
600

In [189]:
#features.reshape(100, 5)

In [190]:
# A NumPy array can only be reshaped when the new shape contains the same
# total number of elements as the original shape. The Iris feature array has
# 150 × 4 = 600 values, so any valid new shape must also contain 600 values.

In [191]:
transposed_features = features.T

print("Original shape:", features.shape)
print("Transposed shape:", transposed_features.shape)

Original shape: (150, 4)
Transposed shape: (4, 150)

In [192]:
print(transposed_features[0])

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]

In [193]:
transposed_features = np.transpose(features)

In [194]:
print(features[0, 2])
print(transposed_features[2, 0])

1.4
1.4

In [195]:
restored_features = transposed_features.T

print(restored_features.shape)
print(np.array_equal(features, restored_features))

(150, 4)
True

In [196]:
feature_means_using_transpose = []

for feature_row in transposed_features:
    feature_means_using_transpose.append(feature_row.mean())

print(feature_means_using_transpose)

[np.float64(5.843333333333334), np.float64(3.0573333333333337), np.float64(3.7580000000000005), np.float64(1.1993333333333336)]

In [197]:
# exercise
# 1. Reshape the feature array into shape (25, 6, 4).
# 2. Reshape it into a two-dimensional array with 120 rows.
# 3. Convert the array into one dimension.
# 4. Restore the flattened array to shape (150, 4).
# 5. Transpose the original array.
# 6. Extract all petal-width values from the transposed array.
# 7. Verify that transposing twice restores the original array.

In [198]:
# 1
reshaped_features = features.reshape(25, 6, 4)
print(reshaped_features.shape)

(25, 6, 4)

In [199]:
# 2
reshaped_features_120_rows = features.reshape(120, -1)
print(reshaped_features_120_rows.shape)

(120, 5)

In [200]:
# 3
flattened_features = features.reshape(-1)
print(flattened_features.shape)

(600,)

In [201]:
# 4
restored_features = flattened_features.reshape(150, 4) 
print(restored_features.shape)

(150, 4)

In [202]:
# 5
transposed_features = features.T
print(transposed_features.shape)

(4, 150)

In [203]:
# 6
print(df) # printed the dataframe to see which column is petal-width

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

       species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 5 columns]

In [204]:
# 6 continued
petal_width_values = transposed_features[3]
print(petal_width_values)

[0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 0.2 0.2 0.1 0.1 0.2 0.4 0.4 0.3
 0.3 0.3 0.2 0.4 0.2 0.5 0.2 0.2 0.4 0.2 0.2 0.2 0.2 0.4 0.1 0.2 0.2 0.2
 0.2 0.1 0.2 0.2 0.3 0.3 0.2 0.6 0.4 0.3 0.2 0.2 0.2 0.2 1.4 1.5 1.5 1.3
 1.5 1.3 1.6 1.  1.3 1.4 1.  1.5 1.  1.4 1.3 1.4 1.5 1.  1.5 1.1 1.8 1.3
 1.5 1.2 1.3 1.4 1.4 1.7 1.5 1.  1.1 1.  1.2 1.6 1.5 1.6 1.5 1.3 1.3 1.3
 1.2 1.4 1.2 1.  1.3 1.2 1.3 1.3 1.1 1.3 2.5 1.9 2.1 1.8 2.2 2.1 1.7 1.8
 1.8 2.5 2.  1.9 2.1 2.  2.4 2.3 1.8 2.2 2.3 1.5 2.3 2.  2.  1.8 2.1 1.8
 1.8 1.8 2.1 1.6 1.9 2.  2.2 1.5 1.4 2.3 2.4 1.8 1.8 2.1 2.4 2.3 1.9 2.3
 2.5 2.3 1.9 2.  2.3 1.8]

In [205]:
# 7
transposed_twice = transposed_features.T
print(np.array_equal(features, transposed_twice))

True

In [206]:
# NUMERICAL OPERATIONS

In [207]:
features + 1

array([[6.1, 4.5, 2.4, 1.2],
       [5.9, 4. , 2.4, 1.2],
       [5.7, 4.2, 2.3, 1.2],
       [5.6, 4.1, 2.5, 1.2],
       [6. , 4.6, 2.4, 1.2],
       [6.4, 4.9, 2.7, 1.4],
       [5.6, 4.4, 2.4, 1.3],
       [6. , 4.4, 2.5, 1.2],
       [5.4, 3.9, 2.4, 1.2],
       [5.9, 4.1, 2.5, 1.1],
       [6.4, 4.7, 2.5, 1.2],
       [5.8, 4.4, 2.6, 1.2],
       [5.8, 4. , 2.4, 1.1],
       [5.3, 4. , 2.1, 1.1],
       [6.8, 5. , 2.2, 1.2],
       [6.7, 5.4, 2.5, 1.4],
       [6.4, 4.9, 2.3, 1.4],
       [6.1, 4.5, 2.4, 1.3],
       [6.7, 4.8, 2.7, 1.3],
       [6.1, 4.8, 2.5, 1.3],
       [6.4, 4.4, 2.7, 1.2],
       [6.1, 4.7, 2.5, 1.4],
       [5.6, 4.6, 2. , 1.2],
       [6.1, 4.3, 2.7, 1.5],
       [5.8, 4.4, 2.9, 1.2],
       [6. , 4. , 2.6, 1.2],
       [6. , 4.4, 2.6, 1.4],
       [6.2, 4.5, 2.5, 1.2],
       [6.2, 4.4, 2.4, 1.2],
       [5.7, 4.2, 2.6, 1.2],
       [5.8, 4.1, 2.6, 1.2],
       [6.4, 4.4, 2.5, 1.4],
       [6.2, 5.1, 2.5, 1.1],
       [6.5, 5.2, 2.4, 1.2],
       [5.9, 4.1, 2.5, 1.2],
       [6. , 4.2, 2.2, 1.2],
       [6.5, 4.5, 2.3, 1.2],
       [5.9, 4.6, 2.4, 1.1],
       [5.4, 4. , 2.3, 1.2],
       [6.1, 4.4, 2.5, 1.2],
       [6. , 4.5, 2.3, 1.3],
       [5.5, 3.3, 2.3, 1.3],
       [5.4, 4.2, 2.3, 1.2],
       [6. , 4.5, 2.6, 1.6],
       [6.1, 4.8, 2.9, 1.4],
       [5.8, 4. , 2.4, 1.3],
       [6.1, 4.8, 2.6, 1.2],
       [5.6, 4.2, 2.4, 1.2],
       [6.3, 4.7, 2.5, 1.2],
       [6. , 4.3, 2.4, 1.2],
       [8. , 4.2, 5.7, 2.4],
       [7.4, 4.2, 5.5, 2.5],
       [7.9, 4.1, 5.9, 2.5],
       [6.5, 3.3, 5. , 2.3],
       [7.5, 3.8, 5.6, 2.5],
       [6.7, 3.8, 5.5, 2.3],
       [7.3, 4.3, 5.7, 2.6],
       [5.9, 3.4, 4.3, 2. ],
       [7.6, 3.9, 5.6, 2.3],
       [6.2, 3.7, 4.9, 2.4],
       [6. , 3. , 4.5, 2. ],
       [6.9, 4. , 5.2, 2.5],
       [7. , 3.2, 5. , 2. ],
       [7.1, 3.9, 5.7, 2.4],
       [6.6, 3.9, 4.6, 2.3],
       [7.7, 4.1, 5.4, 2.4],
       [6.6, 4. , 5.5, 2.5],
       [6.8, 3.7, 5.1, 2. ],
       [7.2, 3.2, 5.5, 2.5],
       [6.6, 3.5, 4.9, 2.1],
       [6.9, 4.2, 5.8, 2.8],
       [7.1, 3.8, 5. , 2.3],
       [7.3, 3.5, 5.9, 2.5],
       [7.1, 3.8, 5.7, 2.2],
       [7.4, 3.9, 5.3, 2.3],
       [7.6, 4. , 5.4, 2.4],
       [7.8, 3.8, 5.8, 2.4],
       [7.7, 4. , 6. , 2.7],
       [7. , 3.9, 5.5, 2.5],
       [6.7, 3.6, 4.5, 2. ],
       [6.5, 3.4, 4.8, 2.1],
       [6.5, 3.4, 4.7, 2. ],
       [6.8, 3.7, 4.9, 2.2],
       [7. , 3.7, 6.1, 2.6],
       [6.4, 4. , 5.5, 2.5],
       [7. , 4.4, 5.5, 2.6],
       [7.7, 4.1, 5.7, 2.5],
       [7.3, 3.3, 5.4, 2.3],
       [6.6, 4. , 5.1, 2.3],
       [6.5, 3.5, 5. , 2.3],
       [6.5, 3.6, 5.4, 2.2],
       [7.1, 4. , 5.6, 2.4],
       [6.8, 3.6, 5. , 2.2],
       [6. , 3.3, 4.3, 2. ],
       [6.6, 3.7, 5.2, 2.3],
       [6.7, 4. , 5.2, 2.2],
       [6.7, 3.9, 5.2, 2.3],
       [7.2, 3.9, 5.3, 2.3],
       [6.1, 3.5, 4. , 2.1],
       [6.7, 3.8, 5.1, 2.3],
       [7.3, 4.3, 7. , 3.5],
       [6.8, 3.7, 6.1, 2.9],
       [8.1, 4. , 6.9, 3.1],
       [7.3, 3.9, 6.6, 2.8],
       [7.5, 4. , 6.8, 3.2],
       [8.6, 4. , 7.6, 3.1],
       [5.9, 3.5, 5.5, 2.7],
       [8.3, 3.9, 7.3, 2.8],
       [7.7, 3.5, 6.8, 2.8],
       [8.2, 4.6, 7.1, 3.5],
       [7.5, 4.2, 6.1, 3. ],
       [7.4, 3.7, 6.3, 2.9],
       [7.8, 4. , 6.5, 3.1],
       [6.7, 3.5, 6. , 3. ],
       [6.8, 3.8, 6.1, 3.4],
       [7.4, 4.2, 6.3, 3.3],
       [7.5, 4. , 6.5, 2.8],
       [8.7, 4.8, 7.7, 3.2],
       [8.7, 3.6, 7.9, 3.3],
       [7. , 3.2, 6. , 2.5],
       [7.9, 4.2, 6.7, 3.3],
       [6.6, 3.8, 5.9, 3. ],
       [8.7, 3.8, 7.7, 3. ],
       [7.3, 3.7, 5.9, 2.8],
       [7.7, 4.3, 6.7, 3.1],
       [8.2, 4.2, 7. , 2.8],
       [7.2, 3.8, 5.8, 2.8],
       [7.1, 4. , 5.9, 2.8],
       [7.4, 3.8, 6.6, 3.1],
       [8.2, 4. , 6.8, 2.6],
       [8.4, 3.8, 7.1, 2.9],
       [8.9, 4.8, 7.4, 3. ],
       [7.4, 3.8, 6.6, 3.2],
       [7.3, 3.8, 6.1, 2.5],
       [7.1, 3.6, 6.6, 2.4],
       [8.7, 4. , 7.1, 3.3],
       [7.3, 4.4, 6.6, 3.4],
       [7.4, 4.1, 6.5, 2.8],
       [7. , 4. , 5.8, 2.8],
       [7.9, 4.1, 6.4, 3.1],
       [7.7, 4.1, 6.6, 3.4],
       [7.9, 4.1, 6.1, 3.3],
       [6.8, 3.7, 6.1, 2.9],
       [7.8, 4.2, 6.9, 3.3],
       [7.7, 4.3, 6.7, 3.5],
       [7.7, 4. , 6.2, 3.3],
       [7.3, 3.5, 6. , 2.9],
       [7.5, 4. , 6.2, 3. ],
       [7.2, 4.4, 6.4, 3.3],
       [6.9, 4. , 6.1, 2.8]])

In [208]:
features - 2

array([[ 3.1,  1.5, -0.6, -1.8],
       [ 2.9,  1. , -0.6, -1.8],
       [ 2.7,  1.2, -0.7, -1.8],
       [ 2.6,  1.1, -0.5, -1.8],
       [ 3. ,  1.6, -0.6, -1.8],
       [ 3.4,  1.9, -0.3, -1.6],
       [ 2.6,  1.4, -0.6, -1.7],
       [ 3. ,  1.4, -0.5, -1.8],
       [ 2.4,  0.9, -0.6, -1.8],
       [ 2.9,  1.1, -0.5, -1.9],
       [ 3.4,  1.7, -0.5, -1.8],
       [ 2.8,  1.4, -0.4, -1.8],
       [ 2.8,  1. , -0.6, -1.9],
       [ 2.3,  1. , -0.9, -1.9],
       [ 3.8,  2. , -0.8, -1.8],
       [ 3.7,  2.4, -0.5, -1.6],
       [ 3.4,  1.9, -0.7, -1.6],
       [ 3.1,  1.5, -0.6, -1.7],
       [ 3.7,  1.8, -0.3, -1.7],
       [ 3.1,  1.8, -0.5, -1.7],
       [ 3.4,  1.4, -0.3, -1.8],
       [ 3.1,  1.7, -0.5, -1.6],
       [ 2.6,  1.6, -1. , -1.8],
       [ 3.1,  1.3, -0.3, -1.5],
       [ 2.8,  1.4, -0.1, -1.8],
       [ 3. ,  1. , -0.4, -1.8],
       [ 3. ,  1.4, -0.4, -1.6],
       [ 3.2,  1.5, -0.5, -1.8],
       [ 3.2,  1.4, -0.6, -1.8],
       [ 2.7,  1.2, -0.4, -1.8],
       [ 2.8,  1.1, -0.4, -1.8],
       [ 3.4,  1.4, -0.5, -1.6],
       [ 3.2,  2.1, -0.5, -1.9],
       [ 3.5,  2.2, -0.6, -1.8],
       [ 2.9,  1.1, -0.5, -1.8],
       [ 3. ,  1.2, -0.8, -1.8],
       [ 3.5,  1.5, -0.7, -1.8],
       [ 2.9,  1.6, -0.6, -1.9],
       [ 2.4,  1. , -0.7, -1.8],
       [ 3.1,  1.4, -0.5, -1.8],
       [ 3. ,  1.5, -0.7, -1.7],
       [ 2.5,  0.3, -0.7, -1.7],
       [ 2.4,  1.2, -0.7, -1.8],
       [ 3. ,  1.5, -0.4, -1.4],
       [ 3.1,  1.8, -0.1, -1.6],
       [ 2.8,  1. , -0.6, -1.7],
       [ 3.1,  1.8, -0.4, -1.8],
       [ 2.6,  1.2, -0.6, -1.8],
       [ 3.3,  1.7, -0.5, -1.8],
       [ 3. ,  1.3, -0.6, -1.8],
       [ 5. ,  1.2,  2.7, -0.6],
       [ 4.4,  1.2,  2.5, -0.5],
       [ 4.9,  1.1,  2.9, -0.5],
       [ 3.5,  0.3,  2. , -0.7],
       [ 4.5,  0.8,  2.6, -0.5],
       [ 3.7,  0.8,  2.5, -0.7],
       [ 4.3,  1.3,  2.7, -0.4],
       [ 2.9,  0.4,  1.3, -1. ],
       [ 4.6,  0.9,  2.6, -0.7],
       [ 3.2,  0.7,  1.9, -0.6],
       [ 3. ,  0. ,  1.5, -1. ],
       [ 3.9,  1. ,  2.2, -0.5],
       [ 4. ,  0.2,  2. , -1. ],
       [ 4.1,  0.9,  2.7, -0.6],
       [ 3.6,  0.9,  1.6, -0.7],
       [ 4.7,  1.1,  2.4, -0.6],
       [ 3.6,  1. ,  2.5, -0.5],
       [ 3.8,  0.7,  2.1, -1. ],
       [ 4.2,  0.2,  2.5, -0.5],
       [ 3.6,  0.5,  1.9, -0.9],
       [ 3.9,  1.2,  2.8, -0.2],
       [ 4.1,  0.8,  2. , -0.7],
       [ 4.3,  0.5,  2.9, -0.5],
       [ 4.1,  0.8,  2.7, -0.8],
       [ 4.4,  0.9,  2.3, -0.7],
       [ 4.6,  1. ,  2.4, -0.6],
       [ 4.8,  0.8,  2.8, -0.6],
       [ 4.7,  1. ,  3. , -0.3],
       [ 4. ,  0.9,  2.5, -0.5],
       [ 3.7,  0.6,  1.5, -1. ],
       [ 3.5,  0.4,  1.8, -0.9],
       [ 3.5,  0.4,  1.7, -1. ],
       [ 3.8,  0.7,  1.9, -0.8],
       [ 4. ,  0.7,  3.1, -0.4],
       [ 3.4,  1. ,  2.5, -0.5],
       [ 4. ,  1.4,  2.5, -0.4],
       [ 4.7,  1.1,  2.7, -0.5],
       [ 4.3,  0.3,  2.4, -0.7],
       [ 3.6,  1. ,  2.1, -0.7],
       [ 3.5,  0.5,  2. , -0.7],
       [ 3.5,  0.6,  2.4, -0.8],
       [ 4.1,  1. ,  2.6, -0.6],
       [ 3.8,  0.6,  2. , -0.8],
       [ 3. ,  0.3,  1.3, -1. ],
       [ 3.6,  0.7,  2.2, -0.7],
       [ 3.7,  1. ,  2.2, -0.8],
       [ 3.7,  0.9,  2.2, -0.7],
       [ 4.2,  0.9,  2.3, -0.7],
       [ 3.1,  0.5,  1. , -0.9],
       [ 3.7,  0.8,  2.1, -0.7],
       [ 4.3,  1.3,  4. ,  0.5],
       [ 3.8,  0.7,  3.1, -0.1],
       [ 5.1,  1. ,  3.9,  0.1],
       [ 4.3,  0.9,  3.6, -0.2],
       [ 4.5,  1. ,  3.8,  0.2],
       [ 5.6,  1. ,  4.6,  0.1],
       [ 2.9,  0.5,  2.5, -0.3],
       [ 5.3,  0.9,  4.3, -0.2],
       [ 4.7,  0.5,  3.8, -0.2],
       [ 5.2,  1.6,  4.1,  0.5],
       [ 4.5,  1.2,  3.1,  0. ],
       [ 4.4,  0.7,  3.3, -0.1],
       [ 4.8,  1. ,  3.5,  0.1],
       [ 3.7,  0.5,  3. ,  0. ],
       [ 3.8,  0.8,  3.1,  0.4],
       [ 4.4,  1.2,  3.3,  0.3],
       [ 4.5,  1. ,  3.5, -0.2],
       [ 5.7,  1.8,  4.7,  0.2],
       [ 5.7,  0.6,  4.9,  0.3],
       [ 4. ,  0.2,  3. , -0.5],
       [ 4.9,  1.2,  3.7,  0.3],
       [ 3.6,  0.8,  2.9,  0. ],
       [ 5.7,  0.8,  4.7,  0. ],
       [ 4.3,  0.7,  2.9, -0.2],
       [ 4.7,  1.3,  3.7,  0.1],
       [ 5.2,  1.2,  4. , -0.2],
       [ 4.2,  0.8,  2.8, -0.2],
       [ 4.1,  1. ,  2.9, -0.2],
       [ 4.4,  0.8,  3.6,  0.1],
       [ 5.2,  1. ,  3.8, -0.4],
       [ 5.4,  0.8,  4.1, -0.1],
       [ 5.9,  1.8,  4.4,  0. ],
       [ 4.4,  0.8,  3.6,  0.2],
       [ 4.3,  0.8,  3.1, -0.5],
       [ 4.1,  0.6,  3.6, -0.6],
       [ 5.7,  1. ,  4.1,  0.3],
       [ 4.3,  1.4,  3.6,  0.4],
       [ 4.4,  1.1,  3.5, -0.2],
       [ 4. ,  1. ,  2.8, -0.2],
       [ 4.9,  1.1,  3.4,  0.1],
       [ 4.7,  1.1,  3.6,  0.4],
       [ 4.9,  1.1,  3.1,  0.3],
       [ 3.8,  0.7,  3.1, -0.1],
       [ 4.8,  1.2,  3.9,  0.3],
       [ 4.7,  1.3,  3.7,  0.5],
       [ 4.7,  1. ,  3.2,  0.3],
       [ 4.3,  0.5,  3. , -0.1],
       [ 4.5,  1. ,  3.2,  0. ],
       [ 4.2,  1.4,  3.4,  0.3],
       [ 3.9,  1. ,  3.1, -0.2]])

In [209]:
features * 3

array([[15.3, 10.5,  4.2,  0.6],
       [14.7,  9. ,  4.2,  0.6],
       [14.1,  9.6,  3.9,  0.6],
       [13.8,  9.3,  4.5,  0.6],
       [15. , 10.8,  4.2,  0.6],
       [16.2, 11.7,  5.1,  1.2],
       [13.8, 10.2,  4.2,  0.9],
       [15. , 10.2,  4.5,  0.6],
       [13.2,  8.7,  4.2,  0.6],
       [14.7,  9.3,  4.5,  0.3],
       [16.2, 11.1,  4.5,  0.6],
       [14.4, 10.2,  4.8,  0.6],
       [14.4,  9. ,  4.2,  0.3],
       [12.9,  9. ,  3.3,  0.3],
       [17.4, 12. ,  3.6,  0.6],
       [17.1, 13.2,  4.5,  1.2],
       [16.2, 11.7,  3.9,  1.2],
       [15.3, 10.5,  4.2,  0.9],
       [17.1, 11.4,  5.1,  0.9],
       [15.3, 11.4,  4.5,  0.9],
       [16.2, 10.2,  5.1,  0.6],
       [15.3, 11.1,  4.5,  1.2],
       [13.8, 10.8,  3. ,  0.6],
       [15.3,  9.9,  5.1,  1.5],
       [14.4, 10.2,  5.7,  0.6],
       [15. ,  9. ,  4.8,  0.6],
       [15. , 10.2,  4.8,  1.2],
       [15.6, 10.5,  4.5,  0.6],
       [15.6, 10.2,  4.2,  0.6],
       [14.1,  9.6,  4.8,  0.6],
       [14.4,  9.3,  4.8,  0.6],
       [16.2, 10.2,  4.5,  1.2],
       [15.6, 12.3,  4.5,  0.3],
       [16.5, 12.6,  4.2,  0.6],
       [14.7,  9.3,  4.5,  0.6],
       [15. ,  9.6,  3.6,  0.6],
       [16.5, 10.5,  3.9,  0.6],
       [14.7, 10.8,  4.2,  0.3],
       [13.2,  9. ,  3.9,  0.6],
       [15.3, 10.2,  4.5,  0.6],
       [15. , 10.5,  3.9,  0.9],
       [13.5,  6.9,  3.9,  0.9],
       [13.2,  9.6,  3.9,  0.6],
       [15. , 10.5,  4.8,  1.8],
       [15.3, 11.4,  5.7,  1.2],
       [14.4,  9. ,  4.2,  0.9],
       [15.3, 11.4,  4.8,  0.6],
       [13.8,  9.6,  4.2,  0.6],
       [15.9, 11.1,  4.5,  0.6],
       [15. ,  9.9,  4.2,  0.6],
       [21. ,  9.6, 14.1,  4.2],
       [19.2,  9.6, 13.5,  4.5],
       [20.7,  9.3, 14.7,  4.5],
       [16.5,  6.9, 12. ,  3.9],
       [19.5,  8.4, 13.8,  4.5],
       [17.1,  8.4, 13.5,  3.9],
       [18.9,  9.9, 14.1,  4.8],
       [14.7,  7.2,  9.9,  3. ],
       [19.8,  8.7, 13.8,  3.9],
       [15.6,  8.1, 11.7,  4.2],
       [15. ,  6. , 10.5,  3. ],
       [17.7,  9. , 12.6,  4.5],
       [18. ,  6.6, 12. ,  3. ],
       [18.3,  8.7, 14.1,  4.2],
       [16.8,  8.7, 10.8,  3.9],
       [20.1,  9.3, 13.2,  4.2],
       [16.8,  9. , 13.5,  4.5],
       [17.4,  8.1, 12.3,  3. ],
       [18.6,  6.6, 13.5,  4.5],
       [16.8,  7.5, 11.7,  3.3],
       [17.7,  9.6, 14.4,  5.4],
       [18.3,  8.4, 12. ,  3.9],
       [18.9,  7.5, 14.7,  4.5],
       [18.3,  8.4, 14.1,  3.6],
       [19.2,  8.7, 12.9,  3.9],
       [19.8,  9. , 13.2,  4.2],
       [20.4,  8.4, 14.4,  4.2],
       [20.1,  9. , 15. ,  5.1],
       [18. ,  8.7, 13.5,  4.5],
       [17.1,  7.8, 10.5,  3. ],
       [16.5,  7.2, 11.4,  3.3],
       [16.5,  7.2, 11.1,  3. ],
       [17.4,  8.1, 11.7,  3.6],
       [18. ,  8.1, 15.3,  4.8],
       [16.2,  9. , 13.5,  4.5],
       [18. , 10.2, 13.5,  4.8],
       [20.1,  9.3, 14.1,  4.5],
       [18.9,  6.9, 13.2,  3.9],
       [16.8,  9. , 12.3,  3.9],
       [16.5,  7.5, 12. ,  3.9],
       [16.5,  7.8, 13.2,  3.6],
       [18.3,  9. , 13.8,  4.2],
       [17.4,  7.8, 12. ,  3.6],
       [15. ,  6.9,  9.9,  3. ],
       [16.8,  8.1, 12.6,  3.9],
       [17.1,  9. , 12.6,  3.6],
       [17.1,  8.7, 12.6,  3.9],
       [18.6,  8.7, 12.9,  3.9],
       [15.3,  7.5,  9. ,  3.3],
       [17.1,  8.4, 12.3,  3.9],
       [18.9,  9.9, 18. ,  7.5],
       [17.4,  8.1, 15.3,  5.7],
       [21.3,  9. , 17.7,  6.3],
       [18.9,  8.7, 16.8,  5.4],
       [19.5,  9. , 17.4,  6.6],
       [22.8,  9. , 19.8,  6.3],
       [14.7,  7.5, 13.5,  5.1],
       [21.9,  8.7, 18.9,  5.4],
       [20.1,  7.5, 17.4,  5.4],
       [21.6, 10.8, 18.3,  7.5],
       [19.5,  9.6, 15.3,  6. ],
       [19.2,  8.1, 15.9,  5.7],
       [20.4,  9. , 16.5,  6.3],
       [17.1,  7.5, 15. ,  6. ],
       [17.4,  8.4, 15.3,  7.2],
       [19.2,  9.6, 15.9,  6.9],
       [19.5,  9. , 16.5,  5.4],
       [23.1, 11.4, 20.1,  6.6],
       [23.1,  7.8, 20.7,  6.9],
       [18. ,  6.6, 15. ,  4.5],
       [20.7,  9.6, 17.1,  6.9],
       [16.8,  8.4, 14.7,  6. ],
       [23.1,  8.4, 20.1,  6. ],
       [18.9,  8.1, 14.7,  5.4],
       [20.1,  9.9, 17.1,  6.3],
       [21.6,  9.6, 18. ,  5.4],
       [18.6,  8.4, 14.4,  5.4],
       [18.3,  9. , 14.7,  5.4],
       [19.2,  8.4, 16.8,  6.3],
       [21.6,  9. , 17.4,  4.8],
       [22.2,  8.4, 18.3,  5.7],
       [23.7, 11.4, 19.2,  6. ],
       [19.2,  8.4, 16.8,  6.6],
       [18.9,  8.4, 15.3,  4.5],
       [18.3,  7.8, 16.8,  4.2],
       [23.1,  9. , 18.3,  6.9],
       [18.9, 10.2, 16.8,  7.2],
       [19.2,  9.3, 16.5,  5.4],
       [18. ,  9. , 14.4,  5.4],
       [20.7,  9.3, 16.2,  6.3],
       [20.1,  9.3, 16.8,  7.2],
       [20.7,  9.3, 15.3,  6.9],
       [17.4,  8.1, 15.3,  5.7],
       [20.4,  9.6, 17.7,  6.9],
       [20.1,  9.9, 17.1,  7.5],
       [20.1,  9. , 15.6,  6.9],
       [18.9,  7.5, 15. ,  5.7],
       [19.5,  9. , 15.6,  6. ],
       [18.6, 10.2, 16.2,  6.9],
       [17.7,  9. , 15.3,  5.4]])

In [210]:
features / 2

array([[2.55, 1.75, 0.7 , 0.1 ],
       [2.45, 1.5 , 0.7 , 0.1 ],
       [2.35, 1.6 , 0.65, 0.1 ],
       [2.3 , 1.55, 0.75, 0.1 ],
       [2.5 , 1.8 , 0.7 , 0.1 ],
       [2.7 , 1.95, 0.85, 0.2 ],
       [2.3 , 1.7 , 0.7 , 0.15],
       [2.5 , 1.7 , 0.75, 0.1 ],
       [2.2 , 1.45, 0.7 , 0.1 ],
       [2.45, 1.55, 0.75, 0.05],
       [2.7 , 1.85, 0.75, 0.1 ],
       [2.4 , 1.7 , 0.8 , 0.1 ],
       [2.4 , 1.5 , 0.7 , 0.05],
       [2.15, 1.5 , 0.55, 0.05],
       [2.9 , 2.  , 0.6 , 0.1 ],
       [2.85, 2.2 , 0.75, 0.2 ],
       [2.7 , 1.95, 0.65, 0.2 ],
       [2.55, 1.75, 0.7 , 0.15],
       [2.85, 1.9 , 0.85, 0.15],
       [2.55, 1.9 , 0.75, 0.15],
       [2.7 , 1.7 , 0.85, 0.1 ],
       [2.55, 1.85, 0.75, 0.2 ],
       [2.3 , 1.8 , 0.5 , 0.1 ],
       [2.55, 1.65, 0.85, 0.25],
       [2.4 , 1.7 , 0.95, 0.1 ],
       [2.5 , 1.5 , 0.8 , 0.1 ],
       [2.5 , 1.7 , 0.8 , 0.2 ],
       [2.6 , 1.75, 0.75, 0.1 ],
       [2.6 , 1.7 , 0.7 , 0.1 ],
       [2.35, 1.6 , 0.8 , 0.1 ],
       [2.4 , 1.55, 0.8 , 0.1 ],
       [2.7 , 1.7 , 0.75, 0.2 ],
       [2.6 , 2.05, 0.75, 0.05],
       [2.75, 2.1 , 0.7 , 0.1 ],
       [2.45, 1.55, 0.75, 0.1 ],
       [2.5 , 1.6 , 0.6 , 0.1 ],
       [2.75, 1.75, 0.65, 0.1 ],
       [2.45, 1.8 , 0.7 , 0.05],
       [2.2 , 1.5 , 0.65, 0.1 ],
       [2.55, 1.7 , 0.75, 0.1 ],
       [2.5 , 1.75, 0.65, 0.15],
       [2.25, 1.15, 0.65, 0.15],
       [2.2 , 1.6 , 0.65, 0.1 ],
       [2.5 , 1.75, 0.8 , 0.3 ],
       [2.55, 1.9 , 0.95, 0.2 ],
       [2.4 , 1.5 , 0.7 , 0.15],
       [2.55, 1.9 , 0.8 , 0.1 ],
       [2.3 , 1.6 , 0.7 , 0.1 ],
       [2.65, 1.85, 0.75, 0.1 ],
       [2.5 , 1.65, 0.7 , 0.1 ],
       [3.5 , 1.6 , 2.35, 0.7 ],
       [3.2 , 1.6 , 2.25, 0.75],
       [3.45, 1.55, 2.45, 0.75],
       [2.75, 1.15, 2.  , 0.65],
       [3.25, 1.4 , 2.3 , 0.75],
       [2.85, 1.4 , 2.25, 0.65],
       [3.15, 1.65, 2.35, 0.8 ],
       [2.45, 1.2 , 1.65, 0.5 ],
       [3.3 , 1.45, 2.3 , 0.65],
       [2.6 , 1.35, 1.95, 0.7 ],
       [2.5 , 1.  , 1.75, 0.5 ],
       [2.95, 1.5 , 2.1 , 0.75],
       [3.  , 1.1 , 2.  , 0.5 ],
       [3.05, 1.45, 2.35, 0.7 ],
       [2.8 , 1.45, 1.8 , 0.65],
       [3.35, 1.55, 2.2 , 0.7 ],
       [2.8 , 1.5 , 2.25, 0.75],
       [2.9 , 1.35, 2.05, 0.5 ],
       [3.1 , 1.1 , 2.25, 0.75],
       [2.8 , 1.25, 1.95, 0.55],
       [2.95, 1.6 , 2.4 , 0.9 ],
       [3.05, 1.4 , 2.  , 0.65],
       [3.15, 1.25, 2.45, 0.75],
       [3.05, 1.4 , 2.35, 0.6 ],
       [3.2 , 1.45, 2.15, 0.65],
       [3.3 , 1.5 , 2.2 , 0.7 ],
       [3.4 , 1.4 , 2.4 , 0.7 ],
       [3.35, 1.5 , 2.5 , 0.85],
       [3.  , 1.45, 2.25, 0.75],
       [2.85, 1.3 , 1.75, 0.5 ],
       [2.75, 1.2 , 1.9 , 0.55],
       [2.75, 1.2 , 1.85, 0.5 ],
       [2.9 , 1.35, 1.95, 0.6 ],
       [3.  , 1.35, 2.55, 0.8 ],
       [2.7 , 1.5 , 2.25, 0.75],
       [3.  , 1.7 , 2.25, 0.8 ],
       [3.35, 1.55, 2.35, 0.75],
       [3.15, 1.15, 2.2 , 0.65],
       [2.8 , 1.5 , 2.05, 0.65],
       [2.75, 1.25, 2.  , 0.65],
       [2.75, 1.3 , 2.2 , 0.6 ],
       [3.05, 1.5 , 2.3 , 0.7 ],
       [2.9 , 1.3 , 2.  , 0.6 ],
       [2.5 , 1.15, 1.65, 0.5 ],
       [2.8 , 1.35, 2.1 , 0.65],
       [2.85, 1.5 , 2.1 , 0.6 ],
       [2.85, 1.45, 2.1 , 0.65],
       [3.1 , 1.45, 2.15, 0.65],
       [2.55, 1.25, 1.5 , 0.55],
       [2.85, 1.4 , 2.05, 0.65],
       [3.15, 1.65, 3.  , 1.25],
       [2.9 , 1.35, 2.55, 0.95],
       [3.55, 1.5 , 2.95, 1.05],
       [3.15, 1.45, 2.8 , 0.9 ],
       [3.25, 1.5 , 2.9 , 1.1 ],
       [3.8 , 1.5 , 3.3 , 1.05],
       [2.45, 1.25, 2.25, 0.85],
       [3.65, 1.45, 3.15, 0.9 ],
       [3.35, 1.25, 2.9 , 0.9 ],
       [3.6 , 1.8 , 3.05, 1.25],
       [3.25, 1.6 , 2.55, 1.  ],
       [3.2 , 1.35, 2.65, 0.95],
       [3.4 , 1.5 , 2.75, 1.05],
       [2.85, 1.25, 2.5 , 1.  ],
       [2.9 , 1.4 , 2.55, 1.2 ],
       [3.2 , 1.6 , 2.65, 1.15],
       [3.25, 1.5 , 2.75, 0.9 ],
       [3.85, 1.9 , 3.35, 1.1 ],
       [3.85, 1.3 , 3.45, 1.15],
       [3.  , 1.1 , 2.5 , 0.75],
       [3.45, 1.6 , 2.85, 1.15],
       [2.8 , 1.4 , 2.45, 1.  ],
       [3.85, 1.4 , 3.35, 1.  ],
       [3.15, 1.35, 2.45, 0.9 ],
       [3.35, 1.65, 2.85, 1.05],
       [3.6 , 1.6 , 3.  , 0.9 ],
       [3.1 , 1.4 , 2.4 , 0.9 ],
       [3.05, 1.5 , 2.45, 0.9 ],
       [3.2 , 1.4 , 2.8 , 1.05],
       [3.6 , 1.5 , 2.9 , 0.8 ],
       [3.7 , 1.4 , 3.05, 0.95],
       [3.95, 1.9 , 3.2 , 1.  ],
       [3.2 , 1.4 , 2.8 , 1.1 ],
       [3.15, 1.4 , 2.55, 0.75],
       [3.05, 1.3 , 2.8 , 0.7 ],
       [3.85, 1.5 , 3.05, 1.15],
       [3.15, 1.7 , 2.8 , 1.2 ],
       [3.2 , 1.55, 2.75, 0.9 ],
       [3.  , 1.5 , 2.4 , 0.9 ],
       [3.45, 1.55, 2.7 , 1.05],
       [3.35, 1.55, 2.8 , 1.2 ],
       [3.45, 1.55, 2.55, 1.15],
       [2.9 , 1.35, 2.55, 0.95],
       [3.4 , 1.6 , 2.95, 1.15],
       [3.35, 1.65, 2.85, 1.25],
       [3.35, 1.5 , 2.6 , 1.15],
       [3.15, 1.25, 2.5 , 0.95],
       [3.25, 1.5 , 2.6 , 1.  ],
       [3.1 , 1.7 , 2.7 , 1.15],
       [2.95, 1.5 , 2.55, 0.9 ]])

In [211]:
features ** 2

array([[2.601e+01, 1.225e+01, 1.960e+00, 4.000e-02],
       [2.401e+01, 9.000e+00, 1.960e+00, 4.000e-02],
       [2.209e+01, 1.024e+01, 1.690e+00, 4.000e-02],
       [2.116e+01, 9.610e+00, 2.250e+00, 4.000e-02],
       [2.500e+01, 1.296e+01, 1.960e+00, 4.000e-02],
       [2.916e+01, 1.521e+01, 2.890e+00, 1.600e-01],
       [2.116e+01, 1.156e+01, 1.960e+00, 9.000e-02],
       [2.500e+01, 1.156e+01, 2.250e+00, 4.000e-02],
       [1.936e+01, 8.410e+00, 1.960e+00, 4.000e-02],
       [2.401e+01, 9.610e+00, 2.250e+00, 1.000e-02],
       [2.916e+01, 1.369e+01, 2.250e+00, 4.000e-02],
       [2.304e+01, 1.156e+01, 2.560e+00, 4.000e-02],
       [2.304e+01, 9.000e+00, 1.960e+00, 1.000e-02],
       [1.849e+01, 9.000e+00, 1.210e+00, 1.000e-02],
       [3.364e+01, 1.600e+01, 1.440e+00, 4.000e-02],
       [3.249e+01, 1.936e+01, 2.250e+00, 1.600e-01],
       [2.916e+01, 1.521e+01, 1.690e+00, 1.600e-01],
       [2.601e+01, 1.225e+01, 1.960e+00, 9.000e-02],
       [3.249e+01, 1.444e+01, 2.890e+00, 9.000e-02],
       [2.601e+01, 1.444e+01, 2.250e+00, 9.000e-02],
       [2.916e+01, 1.156e+01, 2.890e+00, 4.000e-02],
       [2.601e+01, 1.369e+01, 2.250e+00, 1.600e-01],
       [2.116e+01, 1.296e+01, 1.000e+00, 4.000e-02],
       [2.601e+01, 1.089e+01, 2.890e+00, 2.500e-01],
       [2.304e+01, 1.156e+01, 3.610e+00, 4.000e-02],
       [2.500e+01, 9.000e+00, 2.560e+00, 4.000e-02],
       [2.500e+01, 1.156e+01, 2.560e+00, 1.600e-01],
       [2.704e+01, 1.225e+01, 2.250e+00, 4.000e-02],
       [2.704e+01, 1.156e+01, 1.960e+00, 4.000e-02],
       [2.209e+01, 1.024e+01, 2.560e+00, 4.000e-02],
       [2.304e+01, 9.610e+00, 2.560e+00, 4.000e-02],
       [2.916e+01, 1.156e+01, 2.250e+00, 1.600e-01],
       [2.704e+01, 1.681e+01, 2.250e+00, 1.000e-02],
       [3.025e+01, 1.764e+01, 1.960e+00, 4.000e-02],
       [2.401e+01, 9.610e+00, 2.250e+00, 4.000e-02],
       [2.500e+01, 1.024e+01, 1.440e+00, 4.000e-02],
       [3.025e+01, 1.225e+01, 1.690e+00, 4.000e-02],
       [2.401e+01, 1.296e+01, 1.960e+00, 1.000e-02],
       [1.936e+01, 9.000e+00, 1.690e+00, 4.000e-02],
       [2.601e+01, 1.156e+01, 2.250e+00, 4.000e-02],
       [2.500e+01, 1.225e+01, 1.690e+00, 9.000e-02],
       [2.025e+01, 5.290e+00, 1.690e+00, 9.000e-02],
       [1.936e+01, 1.024e+01, 1.690e+00, 4.000e-02],
       [2.500e+01, 1.225e+01, 2.560e+00, 3.600e-01],
       [2.601e+01, 1.444e+01, 3.610e+00, 1.600e-01],
       [2.304e+01, 9.000e+00, 1.960e+00, 9.000e-02],
       [2.601e+01, 1.444e+01, 2.560e+00, 4.000e-02],
       [2.116e+01, 1.024e+01, 1.960e+00, 4.000e-02],
       [2.809e+01, 1.369e+01, 2.250e+00, 4.000e-02],
       [2.500e+01, 1.089e+01, 1.960e+00, 4.000e-02],
       [4.900e+01, 1.024e+01, 2.209e+01, 1.960e+00],
       [4.096e+01, 1.024e+01, 2.025e+01, 2.250e+00],
       [4.761e+01, 9.610e+00, 2.401e+01, 2.250e+00],
       [3.025e+01, 5.290e+00, 1.600e+01, 1.690e+00],
       [4.225e+01, 7.840e+00, 2.116e+01, 2.250e+00],
       [3.249e+01, 7.840e+00, 2.025e+01, 1.690e+00],
       [3.969e+01, 1.089e+01, 2.209e+01, 2.560e+00],
       [2.401e+01, 5.760e+00, 1.089e+01, 1.000e+00],
       [4.356e+01, 8.410e+00, 2.116e+01, 1.690e+00],
       [2.704e+01, 7.290e+00, 1.521e+01, 1.960e+00],
       [2.500e+01, 4.000e+00, 1.225e+01, 1.000e+00],
       [3.481e+01, 9.000e+00, 1.764e+01, 2.250e+00],
       [3.600e+01, 4.840e+00, 1.600e+01, 1.000e+00],
       [3.721e+01, 8.410e+00, 2.209e+01, 1.960e+00],
       [3.136e+01, 8.410e+00, 1.296e+01, 1.690e+00],
       [4.489e+01, 9.610e+00, 1.936e+01, 1.960e+00],
       [3.136e+01, 9.000e+00, 2.025e+01, 2.250e+00],
       [3.364e+01, 7.290e+00, 1.681e+01, 1.000e+00],
       [3.844e+01, 4.840e+00, 2.025e+01, 2.250e+00],
       [3.136e+01, 6.250e+00, 1.521e+01, 1.210e+00],
       [3.481e+01, 1.024e+01, 2.304e+01, 3.240e+00],
       [3.721e+01, 7.840e+00, 1.600e+01, 1.690e+00],
       [3.969e+01, 6.250e+00, 2.401e+01, 2.250e+00],
       [3.721e+01, 7.840e+00, 2.209e+01, 1.440e+00],
       [4.096e+01, 8.410e+00, 1.849e+01, 1.690e+00],
       [4.356e+01, 9.000e+00, 1.936e+01, 1.960e+00],
       [4.624e+01, 7.840e+00, 2.304e+01, 1.960e+00],
       [4.489e+01, 9.000e+00, 2.500e+01, 2.890e+00],
       [3.600e+01, 8.410e+00, 2.025e+01, 2.250e+00],
       [3.249e+01, 6.760e+00, 1.225e+01, 1.000e+00],
       [3.025e+01, 5.760e+00, 1.444e+01, 1.210e+00],
       [3.025e+01, 5.760e+00, 1.369e+01, 1.000e+00],
       [3.364e+01, 7.290e+00, 1.521e+01, 1.440e+00],
       [3.600e+01, 7.290e+00, 2.601e+01, 2.560e+00],
       [2.916e+01, 9.000e+00, 2.025e+01, 2.250e+00],
       [3.600e+01, 1.156e+01, 2.025e+01, 2.560e+00],
       [4.489e+01, 9.610e+00, 2.209e+01, 2.250e+00],
       [3.969e+01, 5.290e+00, 1.936e+01, 1.690e+00],
       [3.136e+01, 9.000e+00, 1.681e+01, 1.690e+00],
       [3.025e+01, 6.250e+00, 1.600e+01, 1.690e+00],
       [3.025e+01, 6.760e+00, 1.936e+01, 1.440e+00],
       [3.721e+01, 9.000e+00, 2.116e+01, 1.960e+00],
       [3.364e+01, 6.760e+00, 1.600e+01, 1.440e+00],
       [2.500e+01, 5.290e+00, 1.089e+01, 1.000e+00],
       [3.136e+01, 7.290e+00, 1.764e+01, 1.690e+00],
       [3.249e+01, 9.000e+00, 1.764e+01, 1.440e+00],
       [3.249e+01, 8.410e+00, 1.764e+01, 1.690e+00],
       [3.844e+01, 8.410e+00, 1.849e+01, 1.690e+00],
       [2.601e+01, 6.250e+00, 9.000e+00, 1.210e+00],
       [3.249e+01, 7.840e+00, 1.681e+01, 1.690e+00],
       [3.969e+01, 1.089e+01, 3.600e+01, 6.250e+00],
       [3.364e+01, 7.290e+00, 2.601e+01, 3.610e+00],
       [5.041e+01, 9.000e+00, 3.481e+01, 4.410e+00],
       [3.969e+01, 8.410e+00, 3.136e+01, 3.240e+00],
       [4.225e+01, 9.000e+00, 3.364e+01, 4.840e+00],
       [5.776e+01, 9.000e+00, 4.356e+01, 4.410e+00],
       [2.401e+01, 6.250e+00, 2.025e+01, 2.890e+00],
       [5.329e+01, 8.410e+00, 3.969e+01, 3.240e+00],
       [4.489e+01, 6.250e+00, 3.364e+01, 3.240e+00],
       [5.184e+01, 1.296e+01, 3.721e+01, 6.250e+00],
       [4.225e+01, 1.024e+01, 2.601e+01, 4.000e+00],
       [4.096e+01, 7.290e+00, 2.809e+01, 3.610e+00],
       [4.624e+01, 9.000e+00, 3.025e+01, 4.410e+00],
       [3.249e+01, 6.250e+00, 2.500e+01, 4.000e+00],
       [3.364e+01, 7.840e+00, 2.601e+01, 5.760e+00],
       [4.096e+01, 1.024e+01, 2.809e+01, 5.290e+00],
       [4.225e+01, 9.000e+00, 3.025e+01, 3.240e+00],
       [5.929e+01, 1.444e+01, 4.489e+01, 4.840e+00],
       [5.929e+01, 6.760e+00, 4.761e+01, 5.290e+00],
       [3.600e+01, 4.840e+00, 2.500e+01, 2.250e+00],
       [4.761e+01, 1.024e+01, 3.249e+01, 5.290e+00],
       [3.136e+01, 7.840e+00, 2.401e+01, 4.000e+00],
       [5.929e+01, 7.840e+00, 4.489e+01, 4.000e+00],
       [3.969e+01, 7.290e+00, 2.401e+01, 3.240e+00],
       [4.489e+01, 1.089e+01, 3.249e+01, 4.410e+00],
       [5.184e+01, 1.024e+01, 3.600e+01, 3.240e+00],
       [3.844e+01, 7.840e+00, 2.304e+01, 3.240e+00],
       [3.721e+01, 9.000e+00, 2.401e+01, 3.240e+00],
       [4.096e+01, 7.840e+00, 3.136e+01, 4.410e+00],
       [5.184e+01, 9.000e+00, 3.364e+01, 2.560e+00],
       [5.476e+01, 7.840e+00, 3.721e+01, 3.610e+00],
       [6.241e+01, 1.444e+01, 4.096e+01, 4.000e+00],
       [4.096e+01, 7.840e+00, 3.136e+01, 4.840e+00],
       [3.969e+01, 7.840e+00, 2.601e+01, 2.250e+00],
       [3.721e+01, 6.760e+00, 3.136e+01, 1.960e+00],
       [5.929e+01, 9.000e+00, 3.721e+01, 5.290e+00],
       [3.969e+01, 1.156e+01, 3.136e+01, 5.760e+00],
       [4.096e+01, 9.610e+00, 3.025e+01, 3.240e+00],
       [3.600e+01, 9.000e+00, 2.304e+01, 3.240e+00],
       [4.761e+01, 9.610e+00, 2.916e+01, 4.410e+00],
       [4.489e+01, 9.610e+00, 3.136e+01, 5.760e+00],
       [4.761e+01, 9.610e+00, 2.601e+01, 5.290e+00],
       [3.364e+01, 7.290e+00, 2.601e+01, 3.610e+00],
       [4.624e+01, 1.024e+01, 3.481e+01, 5.290e+00],
       [4.489e+01, 1.089e+01, 3.249e+01, 6.250e+00],
       [4.489e+01, 9.000e+00, 2.704e+01, 5.290e+00],
       [3.969e+01, 6.250e+00, 2.500e+01, 3.610e+00],
       [4.225e+01, 9.000e+00, 2.704e+01, 4.000e+00],
       [3.844e+01, 1.156e+01, 2.916e+01, 5.290e+00],
       [3.481e+01, 9.000e+00, 2.601e+01, 3.240e+00]])

In [212]:
np.sqrt(features)

array([[2.25831796, 1.87082869, 1.18321596, 0.4472136 ],
       [2.21359436, 1.73205081, 1.18321596, 0.4472136 ],
       [2.16794834, 1.78885438, 1.14017543, 0.4472136 ],
       [2.14476106, 1.76068169, 1.22474487, 0.4472136 ],
       [2.23606798, 1.8973666 , 1.18321596, 0.4472136 ],
       [2.32379001, 1.97484177, 1.30384048, 0.63245553],
       [2.14476106, 1.84390889, 1.18321596, 0.54772256],
       [2.23606798, 1.84390889, 1.22474487, 0.4472136 ],
       [2.0976177 , 1.70293864, 1.18321596, 0.4472136 ],
       [2.21359436, 1.76068169, 1.22474487, 0.31622777],
       [2.32379001, 1.92353841, 1.22474487, 0.4472136 ],
       [2.19089023, 1.84390889, 1.26491106, 0.4472136 ],
       [2.19089023, 1.73205081, 1.18321596, 0.31622777],
       [2.07364414, 1.73205081, 1.04880885, 0.31622777],
       [2.40831892, 2.        , 1.09544512, 0.4472136 ],
       [2.38746728, 2.0976177 , 1.22474487, 0.63245553],
       [2.32379001, 1.97484177, 1.14017543, 0.63245553],
       [2.25831796, 1.87082869, 1.18321596, 0.54772256],
       [2.38746728, 1.94935887, 1.30384048, 0.54772256],
       [2.25831796, 1.94935887, 1.22474487, 0.54772256],
       [2.32379001, 1.84390889, 1.30384048, 0.4472136 ],
       [2.25831796, 1.92353841, 1.22474487, 0.63245553],
       [2.14476106, 1.8973666 , 1.        , 0.4472136 ],
       [2.25831796, 1.81659021, 1.30384048, 0.70710678],
       [2.19089023, 1.84390889, 1.37840488, 0.4472136 ],
       [2.23606798, 1.73205081, 1.26491106, 0.4472136 ],
       [2.23606798, 1.84390889, 1.26491106, 0.63245553],
       [2.28035085, 1.87082869, 1.22474487, 0.4472136 ],
       [2.28035085, 1.84390889, 1.18321596, 0.4472136 ],
       [2.16794834, 1.78885438, 1.26491106, 0.4472136 ],
       [2.19089023, 1.76068169, 1.26491106, 0.4472136 ],
       [2.32379001, 1.84390889, 1.22474487, 0.63245553],
       [2.28035085, 2.02484567, 1.22474487, 0.31622777],
       [2.34520788, 2.04939015, 1.18321596, 0.4472136 ],
       [2.21359436, 1.76068169, 1.22474487, 0.4472136 ],
       [2.23606798, 1.78885438, 1.09544512, 0.4472136 ],
       [2.34520788, 1.87082869, 1.14017543, 0.4472136 ],
       [2.21359436, 1.8973666 , 1.18321596, 0.31622777],
       [2.0976177 , 1.73205081, 1.14017543, 0.4472136 ],
       [2.25831796, 1.84390889, 1.22474487, 0.4472136 ],
       [2.23606798, 1.87082869, 1.14017543, 0.54772256],
       [2.12132034, 1.51657509, 1.14017543, 0.54772256],
       [2.0976177 , 1.78885438, 1.14017543, 0.4472136 ],
       [2.23606798, 1.87082869, 1.26491106, 0.77459667],
       [2.25831796, 1.94935887, 1.37840488, 0.63245553],
       [2.19089023, 1.73205081, 1.18321596, 0.54772256],
       [2.25831796, 1.94935887, 1.26491106, 0.4472136 ],
       [2.14476106, 1.78885438, 1.18321596, 0.4472136 ],
       [2.30217289, 1.92353841, 1.22474487, 0.4472136 ],
       [2.23606798, 1.81659021, 1.18321596, 0.4472136 ],
       [2.64575131, 1.78885438, 2.16794834, 1.18321596],
       [2.52982213, 1.78885438, 2.12132034, 1.22474487],
       [2.62678511, 1.76068169, 2.21359436, 1.22474487],
       [2.34520788, 1.51657509, 2.        , 1.14017543],
       [2.54950976, 1.67332005, 2.14476106, 1.22474487],
       [2.38746728, 1.67332005, 2.12132034, 1.14017543],
       [2.50998008, 1.81659021, 2.16794834, 1.26491106],
       [2.21359436, 1.54919334, 1.81659021, 1.        ],
       [2.56904652, 1.70293864, 2.14476106, 1.14017543],
       [2.28035085, 1.64316767, 1.97484177, 1.18321596],
       [2.23606798, 1.41421356, 1.87082869, 1.        ],
       [2.42899156, 1.73205081, 2.04939015, 1.22474487],
       [2.44948974, 1.4832397 , 2.        , 1.        ],
       [2.46981781, 1.70293864, 2.16794834, 1.18321596],
       [2.36643191, 1.70293864, 1.8973666 , 1.14017543],
       [2.58843582, 1.76068169, 2.0976177 , 1.18321596],
       [2.36643191, 1.73205081, 2.12132034, 1.22474487],
       [2.40831892, 1.64316767, 2.02484567, 1.        ],
       [2.48997992, 1.4832397 , 2.12132034, 1.22474487],
       [2.36643191, 1.58113883, 1.97484177, 1.04880885],
       [2.42899156, 1.78885438, 2.19089023, 1.34164079],
       [2.46981781, 1.67332005, 2.        , 1.14017543],
       [2.50998008, 1.58113883, 2.21359436, 1.22474487],
       [2.46981781, 1.67332005, 2.16794834, 1.09544512],
       [2.52982213, 1.70293864, 2.07364414, 1.14017543],
       [2.56904652, 1.73205081, 2.0976177 , 1.18321596],
       [2.60768096, 1.67332005, 2.19089023, 1.18321596],
       [2.58843582, 1.73205081, 2.23606798, 1.30384048],
       [2.44948974, 1.70293864, 2.12132034, 1.22474487],
       [2.38746728, 1.61245155, 1.87082869, 1.        ],
       [2.34520788, 1.54919334, 1.94935887, 1.04880885],
       [2.34520788, 1.54919334, 1.92353841, 1.        ],
       [2.40831892, 1.64316767, 1.97484177, 1.09544512],
       [2.44948974, 1.64316767, 2.25831796, 1.26491106],
       [2.32379001, 1.73205081, 2.12132034, 1.22474487],
       [2.44948974, 1.84390889, 2.12132034, 1.26491106],
       [2.58843582, 1.76068169, 2.16794834, 1.22474487],
       [2.50998008, 1.51657509, 2.0976177 , 1.14017543],
       [2.36643191, 1.73205081, 2.02484567, 1.14017543],
       [2.34520788, 1.58113883, 2.        , 1.14017543],
       [2.34520788, 1.61245155, 2.0976177 , 1.09544512],
       [2.46981781, 1.73205081, 2.14476106, 1.18321596],
       [2.40831892, 1.61245155, 2.        , 1.09544512],
       [2.23606798, 1.51657509, 1.81659021, 1.        ],
       [2.36643191, 1.64316767, 2.04939015, 1.14017543],
       [2.38746728, 1.73205081, 2.04939015, 1.09544512],
       [2.38746728, 1.70293864, 2.04939015, 1.14017543],
       [2.48997992, 1.70293864, 2.07364414, 1.14017543],
       [2.25831796, 1.58113883, 1.73205081, 1.04880885],
       [2.38746728, 1.67332005, 2.02484567, 1.14017543],
       [2.50998008, 1.81659021, 2.44948974, 1.58113883],
       [2.40831892, 1.64316767, 2.25831796, 1.37840488],
       [2.66458252, 1.73205081, 2.42899156, 1.44913767],
       [2.50998008, 1.70293864, 2.36643191, 1.34164079],
       [2.54950976, 1.73205081, 2.40831892, 1.4832397 ],
       [2.75680975, 1.73205081, 2.56904652, 1.44913767],
       [2.21359436, 1.58113883, 2.12132034, 1.30384048],
       [2.70185122, 1.70293864, 2.50998008, 1.34164079],
       [2.58843582, 1.58113883, 2.40831892, 1.34164079],
       [2.68328157, 1.8973666 , 2.46981781, 1.58113883],
       [2.54950976, 1.78885438, 2.25831796, 1.41421356],
       [2.52982213, 1.64316767, 2.30217289, 1.37840488],
       [2.60768096, 1.73205081, 2.34520788, 1.44913767],
       [2.38746728, 1.58113883, 2.23606798, 1.41421356],
       [2.40831892, 1.67332005, 2.25831796, 1.54919334],
       [2.52982213, 1.78885438, 2.30217289, 1.51657509],
       [2.54950976, 1.73205081, 2.34520788, 1.34164079],
       [2.77488739, 1.94935887, 2.58843582, 1.4832397 ],
       [2.77488739, 1.61245155, 2.62678511, 1.51657509],
       [2.44948974, 1.4832397 , 2.23606798, 1.22474487],
       [2.62678511, 1.78885438, 2.38746728, 1.51657509],
       [2.36643191, 1.67332005, 2.21359436, 1.41421356],
       [2.77488739, 1.67332005, 2.58843582, 1.41421356],
       [2.50998008, 1.64316767, 2.21359436, 1.34164079],
       [2.58843582, 1.81659021, 2.38746728, 1.44913767],
       [2.68328157, 1.78885438, 2.44948974, 1.34164079],
       [2.48997992, 1.67332005, 2.19089023, 1.34164079],
       [2.46981781, 1.73205081, 2.21359436, 1.34164079],
       [2.52982213, 1.67332005, 2.36643191, 1.44913767],
       [2.68328157, 1.73205081, 2.40831892, 1.26491106],
       [2.7202941 , 1.67332005, 2.46981781, 1.37840488],
       [2.81069386, 1.94935887, 2.52982213, 1.41421356],
       [2.52982213, 1.67332005, 2.36643191, 1.4832397 ],
       [2.50998008, 1.67332005, 2.25831796, 1.22474487],
       [2.46981781, 1.61245155, 2.36643191, 1.18321596],
       [2.77488739, 1.73205081, 2.46981781, 1.51657509],
       [2.50998008, 1.84390889, 2.36643191, 1.54919334],
       [2.52982213, 1.76068169, 2.34520788, 1.34164079],
       [2.44948974, 1.73205081, 2.19089023, 1.34164079],
       [2.62678511, 1.76068169, 2.32379001, 1.44913767],
       [2.58843582, 1.76068169, 2.36643191, 1.54919334],
       [2.62678511, 1.76068169, 2.25831796, 1.51657509],
       [2.40831892, 1.64316767, 2.25831796, 1.37840488],
       [2.60768096, 1.78885438, 2.42899156, 1.51657509],
       [2.58843582, 1.81659021, 2.38746728, 1.58113883],
       [2.58843582, 1.73205081, 2.28035085, 1.51657509],
       [2.50998008, 1.58113883, 2.23606798, 1.37840488],
       [2.54950976, 1.73205081, 2.28035085, 1.41421356],
       [2.48997992, 1.84390889, 2.32379001, 1.51657509],
       [2.42899156, 1.73205081, 2.25831796, 1.34164079]])

In [213]:
example = np.array([-4, -2, 0, 2, 5])

np.abs(example)

array([4, 2, 0, 2, 5])

In [214]:
ones = np.ones_like(features)

In [215]:
features + ones

array([[6.1, 4.5, 2.4, 1.2],
       [5.9, 4. , 2.4, 1.2],
       [5.7, 4.2, 2.3, 1.2],
       [5.6, 4.1, 2.5, 1.2],
       [6. , 4.6, 2.4, 1.2],
       [6.4, 4.9, 2.7, 1.4],
       [5.6, 4.4, 2.4, 1.3],
       [6. , 4.4, 2.5, 1.2],
       [5.4, 3.9, 2.4, 1.2],
       [5.9, 4.1, 2.5, 1.1],
       [6.4, 4.7, 2.5, 1.2],
       [5.8, 4.4, 2.6, 1.2],
       [5.8, 4. , 2.4, 1.1],
       [5.3, 4. , 2.1, 1.1],
       [6.8, 5. , 2.2, 1.2],
       [6.7, 5.4, 2.5, 1.4],
       [6.4, 4.9, 2.3, 1.4],
       [6.1, 4.5, 2.4, 1.3],
       [6.7, 4.8, 2.7, 1.3],
       [6.1, 4.8, 2.5, 1.3],
       [6.4, 4.4, 2.7, 1.2],
       [6.1, 4.7, 2.5, 1.4],
       [5.6, 4.6, 2. , 1.2],
       [6.1, 4.3, 2.7, 1.5],
       [5.8, 4.4, 2.9, 1.2],
       [6. , 4. , 2.6, 1.2],
       [6. , 4.4, 2.6, 1.4],
       [6.2, 4.5, 2.5, 1.2],
       [6.2, 4.4, 2.4, 1.2],
       [5.7, 4.2, 2.6, 1.2],
       [5.8, 4.1, 2.6, 1.2],
       [6.4, 4.4, 2.5, 1.4],
       [6.2, 5.1, 2.5, 1.1],
       [6.5, 5.2, 2.4, 1.2],
       [5.9, 4.1, 2.5, 1.2],
       [6. , 4.2, 2.2, 1.2],
       [6.5, 4.5, 2.3, 1.2],
       [5.9, 4.6, 2.4, 1.1],
       [5.4, 4. , 2.3, 1.2],
       [6.1, 4.4, 2.5, 1.2],
       [6. , 4.5, 2.3, 1.3],
       [5.5, 3.3, 2.3, 1.3],
       [5.4, 4.2, 2.3, 1.2],
       [6. , 4.5, 2.6, 1.6],
       [6.1, 4.8, 2.9, 1.4],
       [5.8, 4. , 2.4, 1.3],
       [6.1, 4.8, 2.6, 1.2],
       [5.6, 4.2, 2.4, 1.2],
       [6.3, 4.7, 2.5, 1.2],
       [6. , 4.3, 2.4, 1.2],
       [8. , 4.2, 5.7, 2.4],
       [7.4, 4.2, 5.5, 2.5],
       [7.9, 4.1, 5.9, 2.5],
       [6.5, 3.3, 5. , 2.3],
       [7.5, 3.8, 5.6, 2.5],
       [6.7, 3.8, 5.5, 2.3],
       [7.3, 4.3, 5.7, 2.6],
       [5.9, 3.4, 4.3, 2. ],
       [7.6, 3.9, 5.6, 2.3],
       [6.2, 3.7, 4.9, 2.4],
       [6. , 3. , 4.5, 2. ],
       [6.9, 4. , 5.2, 2.5],
       [7. , 3.2, 5. , 2. ],
       [7.1, 3.9, 5.7, 2.4],
       [6.6, 3.9, 4.6, 2.3],
       [7.7, 4.1, 5.4, 2.4],
       [6.6, 4. , 5.5, 2.5],
       [6.8, 3.7, 5.1, 2. ],
       [7.2, 3.2, 5.5, 2.5],
       [6.6, 3.5, 4.9, 2.1],
       [6.9, 4.2, 5.8, 2.8],
       [7.1, 3.8, 5. , 2.3],
       [7.3, 3.5, 5.9, 2.5],
       [7.1, 3.8, 5.7, 2.2],
       [7.4, 3.9, 5.3, 2.3],
       [7.6, 4. , 5.4, 2.4],
       [7.8, 3.8, 5.8, 2.4],
       [7.7, 4. , 6. , 2.7],
       [7. , 3.9, 5.5, 2.5],
       [6.7, 3.6, 4.5, 2. ],
       [6.5, 3.4, 4.8, 2.1],
       [6.5, 3.4, 4.7, 2. ],
       [6.8, 3.7, 4.9, 2.2],
       [7. , 3.7, 6.1, 2.6],
       [6.4, 4. , 5.5, 2.5],
       [7. , 4.4, 5.5, 2.6],
       [7.7, 4.1, 5.7, 2.5],
       [7.3, 3.3, 5.4, 2.3],
       [6.6, 4. , 5.1, 2.3],
       [6.5, 3.5, 5. , 2.3],
       [6.5, 3.6, 5.4, 2.2],
       [7.1, 4. , 5.6, 2.4],
       [6.8, 3.6, 5. , 2.2],
       [6. , 3.3, 4.3, 2. ],
       [6.6, 3.7, 5.2, 2.3],
       [6.7, 4. , 5.2, 2.2],
       [6.7, 3.9, 5.2, 2.3],
       [7.2, 3.9, 5.3, 2.3],
       [6.1, 3.5, 4. , 2.1],
       [6.7, 3.8, 5.1, 2.3],
       [7.3, 4.3, 7. , 3.5],
       [6.8, 3.7, 6.1, 2.9],
       [8.1, 4. , 6.9, 3.1],
       [7.3, 3.9, 6.6, 2.8],
       [7.5, 4. , 6.8, 3.2],
       [8.6, 4. , 7.6, 3.1],
       [5.9, 3.5, 5.5, 2.7],
       [8.3, 3.9, 7.3, 2.8],
       [7.7, 3.5, 6.8, 2.8],
       [8.2, 4.6, 7.1, 3.5],
       [7.5, 4.2, 6.1, 3. ],
       [7.4, 3.7, 6.3, 2.9],
       [7.8, 4. , 6.5, 3.1],
       [6.7, 3.5, 6. , 3. ],
       [6.8, 3.8, 6.1, 3.4],
       [7.4, 4.2, 6.3, 3.3],
       [7.5, 4. , 6.5, 2.8],
       [8.7, 4.8, 7.7, 3.2],
       [8.7, 3.6, 7.9, 3.3],
       [7. , 3.2, 6. , 2.5],
       [7.9, 4.2, 6.7, 3.3],
       [6.6, 3.8, 5.9, 3. ],
       [8.7, 3.8, 7.7, 3. ],
       [7.3, 3.7, 5.9, 2.8],
       [7.7, 4.3, 6.7, 3.1],
       [8.2, 4.2, 7. , 2.8],
       [7.2, 3.8, 5.8, 2.8],
       [7.1, 4. , 5.9, 2.8],
       [7.4, 3.8, 6.6, 3.1],
       [8.2, 4. , 6.8, 2.6],
       [8.4, 3.8, 7.1, 2.9],
       [8.9, 4.8, 7.4, 3. ],
       [7.4, 3.8, 6.6, 3.2],
       [7.3, 3.8, 6.1, 2.5],
       [7.1, 3.6, 6.6, 2.4],
       [8.7, 4. , 7.1, 3.3],
       [7.3, 4.4, 6.6, 3.4],
       [7.4, 4.1, 6.5, 2.8],
       [7. , 4. , 5.8, 2.8],
       [7.9, 4.1, 6.4, 3.1],
       [7.7, 4.1, 6.6, 3.4],
       [7.9, 4.1, 6.1, 3.3],
       [6.8, 3.7, 6.1, 2.9],
       [7.8, 4.2, 6.9, 3.3],
       [7.7, 4.3, 6.7, 3.5],
       [7.7, 4. , 6.2, 3.3],
       [7.3, 3.5, 6. , 2.9],
       [7.5, 4. , 6.2, 3. ],
       [7.2, 4.4, 6.4, 3.3],
       [6.9, 4. , 6.1, 2.8]])

In [216]:
features - ones

array([[ 4.1,  2.5,  0.4, -0.8],
       [ 3.9,  2. ,  0.4, -0.8],
       [ 3.7,  2.2,  0.3, -0.8],
       [ 3.6,  2.1,  0.5, -0.8],
       [ 4. ,  2.6,  0.4, -0.8],
       [ 4.4,  2.9,  0.7, -0.6],
       [ 3.6,  2.4,  0.4, -0.7],
       [ 4. ,  2.4,  0.5, -0.8],
       [ 3.4,  1.9,  0.4, -0.8],
       [ 3.9,  2.1,  0.5, -0.9],
       [ 4.4,  2.7,  0.5, -0.8],
       [ 3.8,  2.4,  0.6, -0.8],
       [ 3.8,  2. ,  0.4, -0.9],
       [ 3.3,  2. ,  0.1, -0.9],
       [ 4.8,  3. ,  0.2, -0.8],
       [ 4.7,  3.4,  0.5, -0.6],
       [ 4.4,  2.9,  0.3, -0.6],
       [ 4.1,  2.5,  0.4, -0.7],
       [ 4.7,  2.8,  0.7, -0.7],
       [ 4.1,  2.8,  0.5, -0.7],
       [ 4.4,  2.4,  0.7, -0.8],
       [ 4.1,  2.7,  0.5, -0.6],
       [ 3.6,  2.6,  0. , -0.8],
       [ 4.1,  2.3,  0.7, -0.5],
       [ 3.8,  2.4,  0.9, -0.8],
       [ 4. ,  2. ,  0.6, -0.8],
       [ 4. ,  2.4,  0.6, -0.6],
       [ 4.2,  2.5,  0.5, -0.8],
       [ 4.2,  2.4,  0.4, -0.8],
       [ 3.7,  2.2,  0.6, -0.8],
       [ 3.8,  2.1,  0.6, -0.8],
       [ 4.4,  2.4,  0.5, -0.6],
       [ 4.2,  3.1,  0.5, -0.9],
       [ 4.5,  3.2,  0.4, -0.8],
       [ 3.9,  2.1,  0.5, -0.8],
       [ 4. ,  2.2,  0.2, -0.8],
       [ 4.5,  2.5,  0.3, -0.8],
       [ 3.9,  2.6,  0.4, -0.9],
       [ 3.4,  2. ,  0.3, -0.8],
       [ 4.1,  2.4,  0.5, -0.8],
       [ 4. ,  2.5,  0.3, -0.7],
       [ 3.5,  1.3,  0.3, -0.7],
       [ 3.4,  2.2,  0.3, -0.8],
       [ 4. ,  2.5,  0.6, -0.4],
       [ 4.1,  2.8,  0.9, -0.6],
       [ 3.8,  2. ,  0.4, -0.7],
       [ 4.1,  2.8,  0.6, -0.8],
       [ 3.6,  2.2,  0.4, -0.8],
       [ 4.3,  2.7,  0.5, -0.8],
       [ 4. ,  2.3,  0.4, -0.8],
       [ 6. ,  2.2,  3.7,  0.4],
       [ 5.4,  2.2,  3.5,  0.5],
       [ 5.9,  2.1,  3.9,  0.5],
       [ 4.5,  1.3,  3. ,  0.3],
       [ 5.5,  1.8,  3.6,  0.5],
       [ 4.7,  1.8,  3.5,  0.3],
       [ 5.3,  2.3,  3.7,  0.6],
       [ 3.9,  1.4,  2.3,  0. ],
       [ 5.6,  1.9,  3.6,  0.3],
       [ 4.2,  1.7,  2.9,  0.4],
       [ 4. ,  1. ,  2.5,  0. ],
       [ 4.9,  2. ,  3.2,  0.5],
       [ 5. ,  1.2,  3. ,  0. ],
       [ 5.1,  1.9,  3.7,  0.4],
       [ 4.6,  1.9,  2.6,  0.3],
       [ 5.7,  2.1,  3.4,  0.4],
       [ 4.6,  2. ,  3.5,  0.5],
       [ 4.8,  1.7,  3.1,  0. ],
       [ 5.2,  1.2,  3.5,  0.5],
       [ 4.6,  1.5,  2.9,  0.1],
       [ 4.9,  2.2,  3.8,  0.8],
       [ 5.1,  1.8,  3. ,  0.3],
       [ 5.3,  1.5,  3.9,  0.5],
       [ 5.1,  1.8,  3.7,  0.2],
       [ 5.4,  1.9,  3.3,  0.3],
       [ 5.6,  2. ,  3.4,  0.4],
       [ 5.8,  1.8,  3.8,  0.4],
       [ 5.7,  2. ,  4. ,  0.7],
       [ 5. ,  1.9,  3.5,  0.5],
       [ 4.7,  1.6,  2.5,  0. ],
       [ 4.5,  1.4,  2.8,  0.1],
       [ 4.5,  1.4,  2.7,  0. ],
       [ 4.8,  1.7,  2.9,  0.2],
       [ 5. ,  1.7,  4.1,  0.6],
       [ 4.4,  2. ,  3.5,  0.5],
       [ 5. ,  2.4,  3.5,  0.6],
       [ 5.7,  2.1,  3.7,  0.5],
       [ 5.3,  1.3,  3.4,  0.3],
       [ 4.6,  2. ,  3.1,  0.3],
       [ 4.5,  1.5,  3. ,  0.3],
       [ 4.5,  1.6,  3.4,  0.2],
       [ 5.1,  2. ,  3.6,  0.4],
       [ 4.8,  1.6,  3. ,  0.2],
       [ 4. ,  1.3,  2.3,  0. ],
       [ 4.6,  1.7,  3.2,  0.3],
       [ 4.7,  2. ,  3.2,  0.2],
       [ 4.7,  1.9,  3.2,  0.3],
       [ 5.2,  1.9,  3.3,  0.3],
       [ 4.1,  1.5,  2. ,  0.1],
       [ 4.7,  1.8,  3.1,  0.3],
       [ 5.3,  2.3,  5. ,  1.5],
       [ 4.8,  1.7,  4.1,  0.9],
       [ 6.1,  2. ,  4.9,  1.1],
       [ 5.3,  1.9,  4.6,  0.8],
       [ 5.5,  2. ,  4.8,  1.2],
       [ 6.6,  2. ,  5.6,  1.1],
       [ 3.9,  1.5,  3.5,  0.7],
       [ 6.3,  1.9,  5.3,  0.8],
       [ 5.7,  1.5,  4.8,  0.8],
       [ 6.2,  2.6,  5.1,  1.5],
       [ 5.5,  2.2,  4.1,  1. ],
       [ 5.4,  1.7,  4.3,  0.9],
       [ 5.8,  2. ,  4.5,  1.1],
       [ 4.7,  1.5,  4. ,  1. ],
       [ 4.8,  1.8,  4.1,  1.4],
       [ 5.4,  2.2,  4.3,  1.3],
       [ 5.5,  2. ,  4.5,  0.8],
       [ 6.7,  2.8,  5.7,  1.2],
       [ 6.7,  1.6,  5.9,  1.3],
       [ 5. ,  1.2,  4. ,  0.5],
       [ 5.9,  2.2,  4.7,  1.3],
       [ 4.6,  1.8,  3.9,  1. ],
       [ 6.7,  1.8,  5.7,  1. ],
       [ 5.3,  1.7,  3.9,  0.8],
       [ 5.7,  2.3,  4.7,  1.1],
       [ 6.2,  2.2,  5. ,  0.8],
       [ 5.2,  1.8,  3.8,  0.8],
       [ 5.1,  2. ,  3.9,  0.8],
       [ 5.4,  1.8,  4.6,  1.1],
       [ 6.2,  2. ,  4.8,  0.6],
       [ 6.4,  1.8,  5.1,  0.9],
       [ 6.9,  2.8,  5.4,  1. ],
       [ 5.4,  1.8,  4.6,  1.2],
       [ 5.3,  1.8,  4.1,  0.5],
       [ 5.1,  1.6,  4.6,  0.4],
       [ 6.7,  2. ,  5.1,  1.3],
       [ 5.3,  2.4,  4.6,  1.4],
       [ 5.4,  2.1,  4.5,  0.8],
       [ 5. ,  2. ,  3.8,  0.8],
       [ 5.9,  2.1,  4.4,  1.1],
       [ 5.7,  2.1,  4.6,  1.4],
       [ 5.9,  2.1,  4.1,  1.3],
       [ 4.8,  1.7,  4.1,  0.9],
       [ 5.8,  2.2,  4.9,  1.3],
       [ 5.7,  2.3,  4.7,  1.5],
       [ 5.7,  2. ,  4.2,  1.3],
       [ 5.3,  1.5,  4. ,  0.9],
       [ 5.5,  2. ,  4.2,  1. ],
       [ 5.2,  2.4,  4.4,  1.3],
       [ 4.9,  2. ,  4.1,  0.8]])

In [217]:
features * ones

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [218]:
features / ones

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [219]:
np.sum(features)

np.float64(2078.7)

In [220]:
np.prod(features)

np.float64(6.575098460317463e+251)

In [221]:
np.sum(features, axis=0)

array([876.5, 458.6, 563.7, 179.9])

In [222]:
np.sum(features, axis=1)

array([10.2,  9.5,  9.4,  9.4, 10.2, 11.4,  9.7, 10.1,  8.9,  9.6, 10.8,
       10. ,  9.3,  8.5, 11.2, 12. , 11. , 10.3, 11.5, 10.7, 10.7, 10.7,
        9.4, 10.6, 10.3,  9.8, 10.4, 10.4, 10.2,  9.7,  9.7, 10.7, 10.9,
       11.3,  9.7,  9.6, 10.5, 10. ,  8.9, 10.2, 10.1,  8.4,  9.1, 10.7,
       11.2,  9.5, 10.7,  9.4, 10.7,  9.9, 16.3, 15.6, 16.4, 13.1, 15.4,
       14.3, 15.9, 11.6, 15.4, 13.2, 11.5, 14.6, 13.2, 15.1, 13.4, 15.6,
       14.6, 13.6, 14.4, 13.1, 15.7, 14.2, 15.2, 14.8, 14.9, 15.4, 15.8,
       16.4, 14.9, 12.8, 12.8, 12.6, 13.6, 15.4, 14.4, 15.5, 16. , 14.3,
       14. , 13.3, 13.7, 15.1, 13.6, 11.6, 13.8, 14.1, 14.1, 14.7, 11.7,
       13.9, 18.1, 15.5, 18.1, 16.6, 17.5, 19.3, 13.6, 18.3, 16.8, 19.4,
       16.8, 16.3, 17.4, 15.2, 16.1, 17.2, 16.8, 20.4, 19.5, 14.7, 18.1,
       15.3, 19.2, 15.7, 17.8, 18.2, 15.6, 15.8, 16.9, 17.6, 18.2, 20.1,
       17. , 15.7, 15.7, 19.1, 17.7, 16.8, 15.6, 17.5, 17.8, 17.4, 15.5,
       18.2, 18.2, 17.2, 15.7, 16.7, 17.3, 15.8])

In [223]:
np.mean(features, axis=0)

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [224]:
np.min(features, axis=0)

array([4.3, 2. , 1. , 0.1])

In [225]:
np.max(features, axis=0)

array([7.9, 4.4, 6.9, 2.5])

In [226]:
np.std(features, axis=0)

array([0.82530129, 0.43441097, 1.75940407, 0.75969263])

In [227]:
np.std(features, axis=0)

array([0.82530129, 0.43441097, 1.75940407, 0.75969263])

In [228]:
np.round(features)

array([[5., 4., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 2., 0.],
       [5., 4., 1., 0.],
       [5., 4., 2., 0.],
       [5., 3., 1., 0.],
       [5., 3., 2., 0.],
       [4., 3., 1., 0.],
       [5., 3., 2., 0.],
       [5., 4., 2., 0.],
       [5., 3., 2., 0.],
       [5., 3., 1., 0.],
       [4., 3., 1., 0.],
       [6., 4., 1., 0.],
       [6., 4., 2., 0.],
       [5., 4., 1., 0.],
       [5., 4., 1., 0.],
       [6., 4., 2., 0.],
       [5., 4., 2., 0.],
       [5., 3., 2., 0.],
       [5., 4., 2., 0.],
       [5., 4., 1., 0.],
       [5., 3., 2., 0.],
       [5., 3., 2., 0.],
       [5., 3., 2., 0.],
       [5., 3., 2., 0.],
       [5., 4., 2., 0.],
       [5., 3., 1., 0.],
       [5., 3., 2., 0.],
       [5., 3., 2., 0.],
       [5., 3., 2., 0.],
       [5., 4., 2., 0.],
       [6., 4., 1., 0.],
       [5., 3., 2., 0.],
       [5., 3., 1., 0.],
       [6., 4., 1., 0.],
       [5., 4., 1., 0.],
       [4., 3., 1., 0.],
       [5., 3., 2., 0.],
       [5., 4., 1., 0.],
       [4., 2., 1., 0.],
       [4., 3., 1., 0.],
       [5., 4., 2., 1.],
       [5., 4., 2., 0.],
       [5., 3., 1., 0.],
       [5., 4., 2., 0.],
       [5., 3., 1., 0.],
       [5., 4., 2., 0.],
       [5., 3., 1., 0.],
       [7., 3., 5., 1.],
       [6., 3., 4., 2.],
       [7., 3., 5., 2.],
       [6., 2., 4., 1.],
       [6., 3., 5., 2.],
       [6., 3., 4., 1.],
       [6., 3., 5., 2.],
       [5., 2., 3., 1.],
       [7., 3., 5., 1.],
       [5., 3., 4., 1.],
       [5., 2., 4., 1.],
       [6., 3., 4., 2.],
       [6., 2., 4., 1.],
       [6., 3., 5., 1.],
       [6., 3., 4., 1.],
       [7., 3., 4., 1.],
       [6., 3., 4., 2.],
       [6., 3., 4., 1.],
       [6., 2., 4., 2.],
       [6., 2., 4., 1.],
       [6., 3., 5., 2.],
       [6., 3., 4., 1.],
       [6., 2., 5., 2.],
       [6., 3., 5., 1.],
       [6., 3., 4., 1.],
       [7., 3., 4., 1.],
       [7., 3., 5., 1.],
       [7., 3., 5., 2.],
       [6., 3., 4., 2.],
       [6., 3., 4., 1.],
       [6., 2., 4., 1.],
       [6., 2., 4., 1.],
       [6., 3., 4., 1.],
       [6., 3., 5., 2.],
       [5., 3., 4., 2.],
       [6., 3., 4., 2.],
       [7., 3., 5., 2.],
       [6., 2., 4., 1.],
       [6., 3., 4., 1.],
       [6., 2., 4., 1.],
       [6., 3., 4., 1.],
       [6., 3., 5., 1.],
       [6., 3., 4., 1.],
       [5., 2., 3., 1.],
       [6., 3., 4., 1.],
       [6., 3., 4., 1.],
       [6., 3., 4., 1.],
       [6., 3., 4., 1.],
       [5., 2., 3., 1.],
       [6., 3., 4., 1.],
       [6., 3., 6., 2.],
       [6., 3., 5., 2.],
       [7., 3., 6., 2.],
       [6., 3., 6., 2.],
       [6., 3., 6., 2.],
       [8., 3., 7., 2.],
       [5., 2., 4., 2.],
       [7., 3., 6., 2.],
       [7., 2., 6., 2.],
       [7., 4., 6., 2.],
       [6., 3., 5., 2.],
       [6., 3., 5., 2.],
       [7., 3., 6., 2.],
       [6., 2., 5., 2.],
       [6., 3., 5., 2.],
       [6., 3., 5., 2.],
       [6., 3., 6., 2.],
       [8., 4., 7., 2.],
       [8., 3., 7., 2.],
       [6., 2., 5., 2.],
       [7., 3., 6., 2.],
       [6., 3., 5., 2.],
       [8., 3., 7., 2.],
       [6., 3., 5., 2.],
       [7., 3., 6., 2.],
       [7., 3., 6., 2.],
       [6., 3., 5., 2.],
       [6., 3., 5., 2.],
       [6., 3., 6., 2.],
       [7., 3., 6., 2.],
       [7., 3., 6., 2.],
       [8., 4., 6., 2.],
       [6., 3., 6., 2.],
       [6., 3., 5., 2.],
       [6., 3., 6., 1.],
       [8., 3., 6., 2.],
       [6., 3., 6., 2.],
       [6., 3., 6., 2.],
       [6., 3., 5., 2.],
       [7., 3., 5., 2.],
       [7., 3., 6., 2.],
       [7., 3., 5., 2.],
       [6., 3., 5., 2.],
       [7., 3., 6., 2.],
       [7., 3., 6., 2.],
       [7., 3., 5., 2.],
       [6., 2., 5., 2.],
       [6., 3., 5., 2.],
       [6., 3., 5., 2.],
       [6., 3., 5., 2.]])

In [229]:
np.floor(features)

array([[5., 3., 1., 0.],
       [4., 3., 1., 0.],
       [4., 3., 1., 0.],
       [4., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [4., 3., 1., 0.],
       [5., 3., 1., 0.],
       [4., 2., 1., 0.],
       [4., 3., 1., 0.],
       [5., 3., 1., 0.],
       [4., 3., 1., 0.],
       [4., 3., 1., 0.],
       [4., 3., 1., 0.],
       [5., 4., 1., 0.],
       [5., 4., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [4., 3., 1., 0.],
       [5., 3., 1., 0.],
       [4., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [4., 3., 1., 0.],
       [4., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 4., 1., 0.],
       [5., 4., 1., 0.],
       [4., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [4., 3., 1., 0.],
       [4., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [4., 2., 1., 0.],
       [4., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [4., 3., 1., 0.],
       [5., 3., 1., 0.],
       [4., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [7., 3., 4., 1.],
       [6., 3., 4., 1.],
       [6., 3., 4., 1.],
       [5., 2., 4., 1.],
       [6., 2., 4., 1.],
       [5., 2., 4., 1.],
       [6., 3., 4., 1.],
       [4., 2., 3., 1.],
       [6., 2., 4., 1.],
       [5., 2., 3., 1.],
       [5., 2., 3., 1.],
       [5., 3., 4., 1.],
       [6., 2., 4., 1.],
       [6., 2., 4., 1.],
       [5., 2., 3., 1.],
       [6., 3., 4., 1.],
       [5., 3., 4., 1.],
       [5., 2., 4., 1.],
       [6., 2., 4., 1.],
       [5., 2., 3., 1.],
       [5., 3., 4., 1.],
       [6., 2., 4., 1.],
       [6., 2., 4., 1.],
       [6., 2., 4., 1.],
       [6., 2., 4., 1.],
       [6., 3., 4., 1.],
       [6., 2., 4., 1.],
       [6., 3., 5., 1.],
       [6., 2., 4., 1.],
       [5., 2., 3., 1.],
       [5., 2., 3., 1.],
       [5., 2., 3., 1.],
       [5., 2., 3., 1.],
       [6., 2., 5., 1.],
       [5., 3., 4., 1.],
       [6., 3., 4., 1.],
       [6., 3., 4., 1.],
       [6., 2., 4., 1.],
       [5., 3., 4., 1.],
       [5., 2., 4., 1.],
       [5., 2., 4., 1.],
       [6., 3., 4., 1.],
       [5., 2., 4., 1.],
       [5., 2., 3., 1.],
       [5., 2., 4., 1.],
       [5., 3., 4., 1.],
       [5., 2., 4., 1.],
       [6., 2., 4., 1.],
       [5., 2., 3., 1.],
       [5., 2., 4., 1.],
       [6., 3., 6., 2.],
       [5., 2., 5., 1.],
       [7., 3., 5., 2.],
       [6., 2., 5., 1.],
       [6., 3., 5., 2.],
       [7., 3., 6., 2.],
       [4., 2., 4., 1.],
       [7., 2., 6., 1.],
       [6., 2., 5., 1.],
       [7., 3., 6., 2.],
       [6., 3., 5., 2.],
       [6., 2., 5., 1.],
       [6., 3., 5., 2.],
       [5., 2., 5., 2.],
       [5., 2., 5., 2.],
       [6., 3., 5., 2.],
       [6., 3., 5., 1.],
       [7., 3., 6., 2.],
       [7., 2., 6., 2.],
       [6., 2., 5., 1.],
       [6., 3., 5., 2.],
       [5., 2., 4., 2.],
       [7., 2., 6., 2.],
       [6., 2., 4., 1.],
       [6., 3., 5., 2.],
       [7., 3., 6., 1.],
       [6., 2., 4., 1.],
       [6., 3., 4., 1.],
       [6., 2., 5., 2.],
       [7., 3., 5., 1.],
       [7., 2., 6., 1.],
       [7., 3., 6., 2.],
       [6., 2., 5., 2.],
       [6., 2., 5., 1.],
       [6., 2., 5., 1.],
       [7., 3., 6., 2.],
       [6., 3., 5., 2.],
       [6., 3., 5., 1.],
       [6., 3., 4., 1.],
       [6., 3., 5., 2.],
       [6., 3., 5., 2.],
       [6., 3., 5., 2.],
       [5., 2., 5., 1.],
       [6., 3., 5., 2.],
       [6., 3., 5., 2.],
       [6., 3., 5., 2.],
       [6., 2., 5., 1.],
       [6., 3., 5., 2.],
       [6., 3., 5., 2.],
       [5., 3., 5., 1.]])

In [230]:
np.ceil(features)

array([[6., 4., 2., 1.],
       [5., 3., 2., 1.],
       [5., 4., 2., 1.],
       [5., 4., 2., 1.],
       [5., 4., 2., 1.],
       [6., 4., 2., 1.],
       [5., 4., 2., 1.],
       [5., 4., 2., 1.],
       [5., 3., 2., 1.],
       [5., 4., 2., 1.],
       [6., 4., 2., 1.],
       [5., 4., 2., 1.],
       [5., 3., 2., 1.],
       [5., 3., 2., 1.],
       [6., 4., 2., 1.],
       [6., 5., 2., 1.],
       [6., 4., 2., 1.],
       [6., 4., 2., 1.],
       [6., 4., 2., 1.],
       [6., 4., 2., 1.],
       [6., 4., 2., 1.],
       [6., 4., 2., 1.],
       [5., 4., 1., 1.],
       [6., 4., 2., 1.],
       [5., 4., 2., 1.],
       [5., 3., 2., 1.],
       [5., 4., 2., 1.],
       [6., 4., 2., 1.],
       [6., 4., 2., 1.],
       [5., 4., 2., 1.],
       [5., 4., 2., 1.],
       [6., 4., 2., 1.],
       [6., 5., 2., 1.],
       [6., 5., 2., 1.],
       [5., 4., 2., 1.],
       [5., 4., 2., 1.],
       [6., 4., 2., 1.],
       [5., 4., 2., 1.],
       [5., 3., 2., 1.],
       [6., 4., 2., 1.],
       [5., 4., 2., 1.],
       [5., 3., 2., 1.],
       [5., 4., 2., 1.],
       [5., 4., 2., 1.],
       [6., 4., 2., 1.],
       [5., 3., 2., 1.],
       [6., 4., 2., 1.],
       [5., 4., 2., 1.],
       [6., 4., 2., 1.],
       [5., 4., 2., 1.],
       [7., 4., 5., 2.],
       [7., 4., 5., 2.],
       [7., 4., 5., 2.],
       [6., 3., 4., 2.],
       [7., 3., 5., 2.],
       [6., 3., 5., 2.],
       [7., 4., 5., 2.],
       [5., 3., 4., 1.],
       [7., 3., 5., 2.],
       [6., 3., 4., 2.],
       [5., 2., 4., 1.],
       [6., 3., 5., 2.],
       [6., 3., 4., 1.],
       [7., 3., 5., 2.],
       [6., 3., 4., 2.],
       [7., 4., 5., 2.],
       [6., 3., 5., 2.],
       [6., 3., 5., 1.],
       [7., 3., 5., 2.],
       [6., 3., 4., 2.],
       [6., 4., 5., 2.],
       [7., 3., 4., 2.],
       [7., 3., 5., 2.],
       [7., 3., 5., 2.],
       [7., 3., 5., 2.],
       [7., 3., 5., 2.],
       [7., 3., 5., 2.],
       [7., 3., 5., 2.],
       [6., 3., 5., 2.],
       [6., 3., 4., 1.],
       [6., 3., 4., 2.],
       [6., 3., 4., 1.],
       [6., 3., 4., 2.],
       [6., 3., 6., 2.],
       [6., 3., 5., 2.],
       [6., 4., 5., 2.],
       [7., 4., 5., 2.],
       [7., 3., 5., 2.],
       [6., 3., 5., 2.],
       [6., 3., 4., 2.],
       [6., 3., 5., 2.],
       [7., 3., 5., 2.],
       [6., 3., 4., 2.],
       [5., 3., 4., 1.],
       [6., 3., 5., 2.],
       [6., 3., 5., 2.],
       [6., 3., 5., 2.],
       [7., 3., 5., 2.],
       [6., 3., 3., 2.],
       [6., 3., 5., 2.],
       [7., 4., 6., 3.],
       [6., 3., 6., 2.],
       [8., 3., 6., 3.],
       [7., 3., 6., 2.],
       [7., 3., 6., 3.],
       [8., 3., 7., 3.],
       [5., 3., 5., 2.],
       [8., 3., 7., 2.],
       [7., 3., 6., 2.],
       [8., 4., 7., 3.],
       [7., 4., 6., 2.],
       [7., 3., 6., 2.],
       [7., 3., 6., 3.],
       [6., 3., 5., 2.],
       [6., 3., 6., 3.],
       [7., 4., 6., 3.],
       [7., 3., 6., 2.],
       [8., 4., 7., 3.],
       [8., 3., 7., 3.],
       [6., 3., 5., 2.],
       [7., 4., 6., 3.],
       [6., 3., 5., 2.],
       [8., 3., 7., 2.],
       [7., 3., 5., 2.],
       [7., 4., 6., 3.],
       [8., 4., 6., 2.],
       [7., 3., 5., 2.],
       [7., 3., 5., 2.],
       [7., 3., 6., 3.],
       [8., 3., 6., 2.],
       [8., 3., 7., 2.],
       [8., 4., 7., 2.],
       [7., 3., 6., 3.],
       [7., 3., 6., 2.],
       [7., 3., 6., 2.],
       [8., 3., 7., 3.],
       [7., 4., 6., 3.],
       [7., 4., 6., 2.],
       [6., 3., 5., 2.],
       [7., 4., 6., 3.],
       [7., 4., 6., 3.],
       [7., 4., 6., 3.],
       [6., 3., 6., 2.],
       [7., 4., 6., 3.],
       [7., 4., 6., 3.],
       [7., 3., 6., 3.],
       [7., 3., 5., 2.],
       [7., 3., 6., 2.],
       [7., 4., 6., 3.],
       [6., 3., 6., 2.]])

In [231]:
np.clip(features, 2, 6) # clip values below 2 to 2 and above 6 to 6

array([[5.1, 3.5, 2. , 2. ],
       [4.9, 3. , 2. , 2. ],
       [4.7, 3.2, 2. , 2. ],
       [4.6, 3.1, 2. , 2. ],
       [5. , 3.6, 2. , 2. ],
       [5.4, 3.9, 2. , 2. ],
       [4.6, 3.4, 2. , 2. ],
       [5. , 3.4, 2. , 2. ],
       [4.4, 2.9, 2. , 2. ],
       [4.9, 3.1, 2. , 2. ],
       [5.4, 3.7, 2. , 2. ],
       [4.8, 3.4, 2. , 2. ],
       [4.8, 3. , 2. , 2. ],
       [4.3, 3. , 2. , 2. ],
       [5.8, 4. , 2. , 2. ],
       [5.7, 4.4, 2. , 2. ],
       [5.4, 3.9, 2. , 2. ],
       [5.1, 3.5, 2. , 2. ],
       [5.7, 3.8, 2. , 2. ],
       [5.1, 3.8, 2. , 2. ],
       [5.4, 3.4, 2. , 2. ],
       [5.1, 3.7, 2. , 2. ],
       [4.6, 3.6, 2. , 2. ],
       [5.1, 3.3, 2. , 2. ],
       [4.8, 3.4, 2. , 2. ],
       [5. , 3. , 2. , 2. ],
       [5. , 3.4, 2. , 2. ],
       [5.2, 3.5, 2. , 2. ],
       [5.2, 3.4, 2. , 2. ],
       [4.7, 3.2, 2. , 2. ],
       [4.8, 3.1, 2. , 2. ],
       [5.4, 3.4, 2. , 2. ],
       [5.2, 4.1, 2. , 2. ],
       [5.5, 4.2, 2. , 2. ],
       [4.9, 3.1, 2. , 2. ],
       [5. , 3.2, 2. , 2. ],
       [5.5, 3.5, 2. , 2. ],
       [4.9, 3.6, 2. , 2. ],
       [4.4, 3. , 2. , 2. ],
       [5.1, 3.4, 2. , 2. ],
       [5. , 3.5, 2. , 2. ],
       [4.5, 2.3, 2. , 2. ],
       [4.4, 3.2, 2. , 2. ],
       [5. , 3.5, 2. , 2. ],
       [5.1, 3.8, 2. , 2. ],
       [4.8, 3. , 2. , 2. ],
       [5.1, 3.8, 2. , 2. ],
       [4.6, 3.2, 2. , 2. ],
       [5.3, 3.7, 2. , 2. ],
       [5. , 3.3, 2. , 2. ],
       [6. , 3.2, 4.7, 2. ],
       [6. , 3.2, 4.5, 2. ],
       [6. , 3.1, 4.9, 2. ],
       [5.5, 2.3, 4. , 2. ],
       [6. , 2.8, 4.6, 2. ],
       [5.7, 2.8, 4.5, 2. ],
       [6. , 3.3, 4.7, 2. ],
       [4.9, 2.4, 3.3, 2. ],
       [6. , 2.9, 4.6, 2. ],
       [5.2, 2.7, 3.9, 2. ],
       [5. , 2. , 3.5, 2. ],
       [5.9, 3. , 4.2, 2. ],
       [6. , 2.2, 4. , 2. ],
       [6. , 2.9, 4.7, 2. ],
       [5.6, 2.9, 3.6, 2. ],
       [6. , 3.1, 4.4, 2. ],
       [5.6, 3. , 4.5, 2. ],
       [5.8, 2.7, 4.1, 2. ],
       [6. , 2.2, 4.5, 2. ],
       [5.6, 2.5, 3.9, 2. ],
       [5.9, 3.2, 4.8, 2. ],
       [6. , 2.8, 4. , 2. ],
       [6. , 2.5, 4.9, 2. ],
       [6. , 2.8, 4.7, 2. ],
       [6. , 2.9, 4.3, 2. ],
       [6. , 3. , 4.4, 2. ],
       [6. , 2.8, 4.8, 2. ],
       [6. , 3. , 5. , 2. ],
       [6. , 2.9, 4.5, 2. ],
       [5.7, 2.6, 3.5, 2. ],
       [5.5, 2.4, 3.8, 2. ],
       [5.5, 2.4, 3.7, 2. ],
       [5.8, 2.7, 3.9, 2. ],
       [6. , 2.7, 5.1, 2. ],
       [5.4, 3. , 4.5, 2. ],
       [6. , 3.4, 4.5, 2. ],
       [6. , 3.1, 4.7, 2. ],
       [6. , 2.3, 4.4, 2. ],
       [5.6, 3. , 4.1, 2. ],
       [5.5, 2.5, 4. , 2. ],
       [5.5, 2.6, 4.4, 2. ],
       [6. , 3. , 4.6, 2. ],
       [5.8, 2.6, 4. , 2. ],
       [5. , 2.3, 3.3, 2. ],
       [5.6, 2.7, 4.2, 2. ],
       [5.7, 3. , 4.2, 2. ],
       [5.7, 2.9, 4.2, 2. ],
       [6. , 2.9, 4.3, 2. ],
       [5.1, 2.5, 3. , 2. ],
       [5.7, 2.8, 4.1, 2. ],
       [6. , 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 2. ],
       [6. , 3. , 5.9, 2.1],
       [6. , 2.9, 5.6, 2. ],
       [6. , 3. , 5.8, 2.2],
       [6. , 3. , 6. , 2.1],
       [4.9, 2.5, 4.5, 2. ],
       [6. , 2.9, 6. , 2. ],
       [6. , 2.5, 5.8, 2. ],
       [6. , 3.6, 6. , 2.5],
       [6. , 3.2, 5.1, 2. ],
       [6. , 2.7, 5.3, 2. ],
       [6. , 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6. , 3.2, 5.3, 2.3],
       [6. , 3. , 5.5, 2. ],
       [6. , 3.8, 6. , 2.2],
       [6. , 2.6, 6. , 2.3],
       [6. , 2.2, 5. , 2. ],
       [6. , 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [6. , 2.8, 6. , 2. ],
       [6. , 2.7, 4.9, 2. ],
       [6. , 3.3, 5.7, 2.1],
       [6. , 3.2, 6. , 2. ],
       [6. , 2.8, 4.8, 2. ],
       [6. , 3. , 4.9, 2. ],
       [6. , 2.8, 5.6, 2.1],
       [6. , 3. , 5.8, 2. ],
       [6. , 2.8, 6. , 2. ],
       [6. , 3.8, 6. , 2. ],
       [6. , 2.8, 5.6, 2.2],
       [6. , 2.8, 5.1, 2. ],
       [6. , 2.6, 5.6, 2. ],
       [6. , 3. , 6. , 2.3],
       [6. , 3.4, 5.6, 2.4],
       [6. , 3.1, 5.5, 2. ],
       [6. , 3. , 4.8, 2. ],
       [6. , 3.1, 5.4, 2.1],
       [6. , 3.1, 5.6, 2.4],
       [6. , 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 2. ],
       [6. , 3.2, 5.9, 2.3],
       [6. , 3.3, 5.7, 2.5],
       [6. , 3. , 5.2, 2.3],
       [6. , 2.5, 5. , 2. ],
       [6. , 3. , 5.2, 2. ],
       [6. , 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 2. ]])

In [232]:
a = np.array([1,2,3])

b = np.array([4,5,6])

In [233]:
np.dot(a,b)

np.int64(32)

In [234]:
A = features[:4]

print(A.shape)

(4, 4)

In [235]:
AT = A.T

In [236]:
A @ AT

array([[40.26, 37.49, 37.03, 36.45],
       [37.49, 35.01, 34.49, 33.98],
       [37.03, 34.49, 34.06, 33.53],
       [36.45, 33.98, 33.53, 33.06]])

In [237]:
np.matmul(A, AT)

array([[40.26, 37.49, 37.03, 36.45],
       [37.49, 35.01, 34.49, 33.98],
       [37.03, 34.49, 34.06, 33.53],
       [36.45, 33.98, 33.53, 33.06]])

In [238]:
# LOGICAL OPERATIONS

In [239]:
features > 5

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False,  True, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [False, False, False, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False, False, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False, False, False],
       [ True, False,  True, False],
       [ True, False, False, False],
       [ True, False,  True, False],
       [ True, False, False, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False, False, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False, False, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [240]:
features[features[:, 0] > 5] # select all rows where the first column is greater than 5

array([[5.1, 3.5, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [5.1, 3.3, 1.7, 0.5],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.8, 1.6, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [241]:
features[features[:, 3] < 1] # select all rows where the fourth column is less than 1

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2]])

In [242]:
features[
    (features[:,0] > 5) &
    (features[:,2] > 4)
] # select all rows where the first column is greater than 5 and the third column is greater than 4

array([[7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.6, 2.9, 4.6, 1.3],
       [5.9, 3. , 4.2, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.9, 3.2, 4.8, 1.8],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [243]:
features[
    (features[:,0] < 5) |
    (features[:,2] > 5)
] # select all rows where the first column is less than 5 or the third column is greater than 5

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [4.6, 3.6, 1. , 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [4.6, 3.2, 1.4, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [6. , 2.7, 5.1, 1.6],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6.9, 3.2, 5.7, 2.3],
       [7.7, 2.8, 6.7, 2. ],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [244]:
features[
    ~(features[:,0] > 5)
] # select all rows where the first column is NOT greater than 5

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [4.6, 3.6, 1. , 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [4.8, 3. , 1.4, 0.3],
       [4.6, 3.2, 1.4, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [5. , 2. , 3.5, 1. ],
       [5. , 2.3, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [245]:
mask = features[:,2] > 4

np.sum(mask)

np.int64(84)

In [246]:
np.count_nonzero(mask)

np.int64(84)

In [247]:
np.any(features > 7)

np.True_

In [248]:
np.all(features > 0)

np.True_

In [249]:
condition1 = features[:,0] > 5
condition2 = features[:,2] > 4

print(np.logical_and(condition1, condition2))
print(np.logical_or(condition1, condition2))
print(np.logical_not(condition1))

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False  True  True  True False  True  True  True False  True False
 False  True False  True False  True  True  True  True False  True False
  True  True  True  True  True  True  True False False False False  True
  True  True  True  True  True False  True  True False False  True  True
  True  True False  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True]
[ True False False False False  True False False False False  True False
 False False  True  True  True  True  True  True  True  True False  True
 False False False  True  True False False  True  True  True False False
  True False False  True False False False False  True False  True False
  True False  True  True  True  True  True  True  True False  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True False  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True]
[False  True  True  True  True False  True  True  True  True False  True
  True  True False False False False False False False False  True False
  True  True  True False False  True  True False False False  True  True
 False  True  True False  True  True  True  True False  True False  True
 False  True False False False False False False False  True False False
  True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False  True False False
 False False False False False False False False False False  True False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False]

In [250]:
np.where(
    features[:,0] > 5,
    "Large",
    "Small"
) # returns an array of the same shape as the first argument,
  # where each element is "Large" if the corresponding element in features[:,0] is
  # greater than 5, and "Small" otherwise.

array(['Large', 'Small', 'Small', 'Small', 'Small', 'Large', 'Small',
       'Small', 'Small', 'Small', 'Large', 'Small', 'Small', 'Small',
       'Large', 'Large', 'Large', 'Large', 'Large', 'Large', 'Large',
       'Large', 'Small', 'Large', 'Small', 'Small', 'Small', 'Large',
       'Large', 'Small', 'Small', 'Large', 'Large', 'Large', 'Small',
       'Small', 'Large', 'Small', 'Small', 'Large', 'Small', 'Small',
       'Small', 'Small', 'Large', 'Small', 'Large', 'Small', 'Large',
       'Small', 'Large', 'Large', 'Large', 'Large', 'Large', 'Large',
       'Large', 'Small', 'Large', 'Large', 'Small', 'Large', 'Large',
       'Large', 'Large', 'Large', 'Large', 'Large', 'Large', 'Large',
       'Large', 'Large', 'Large', 'Large', 'Large', 'Large', 'Large',
       'Large', 'Large', 'Large', 'Large', 'Large', 'Large', 'Large',
       'Large', 'Large', 'Large', 'Large', 'Large', 'Large', 'Large',
       'Large', 'Large', 'Small', 'Large', 'Large', 'Large', 'Large',
       'Large', 'Large', 'Large', 'Large', 'Large', 'Large', 'Large',
       'Large', 'Small', 'Large', 'Large', 'Large', 'Large', 'Large',
       'Large', 'Large', 'Large', 'Large', 'Large', 'Large', 'Large',
       'Large', 'Large', 'Large', 'Large', 'Large', 'Large', 'Large',
       'Large', 'Large', 'Large', 'Large', 'Large', 'Large', 'Large',
       'Large', 'Large', 'Large', 'Large', 'Large', 'Large', 'Large',
       'Large', 'Large', 'Large', 'Large', 'Large', 'Large', 'Large',
       'Large', 'Large', 'Large'], dtype='<U5')

In [251]:
labels

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica'], dtype=object)

In [252]:
features[labels == "setosa"]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2]])

In [253]:
# exercise
# 1. Select all flowers with a sepal width greater than 3.
# 2. Select all flowers with a petal length between 2 and 5.
# 3. Count how many flowers have a petal width greater than 1.5.
# 4. Check whether any flower has a sepal length greater than 8.
# 5. Check whether all petal widths are positive.
# 6. Create a new array where every value greater than 5 becomes 100, and every other value becomes 0 using np.where().
# 7. Select all virginica flowers whose petal length is greater than 5.

In [254]:
# 1
print(features[features[:,1] > 3])

[[5.1 3.5 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [6.3 3.3 4.7 1.6]
 [6.7 3.1 4.4 1.4]
 [5.9 3.2 4.8 1.8]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 3.3 6.  2.5]
 [7.2 3.6 6.1 2.5]
 [6.5 3.2 5.1 2. ]
 [6.4 3.2 5.3 2.3]
 [7.7 3.8 6.7 2.2]
 [6.9 3.2 5.7 2.3]
 [6.7 3.3 5.7 2.1]
 [7.2 3.2 6.  1.8]
 [7.9 3.8 6.4 2. ]
 [6.3 3.4 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [6.9 3.1 5.4 2.1]
 [6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.2 3.4 5.4 2.3]]

In [255]:
# 2
print(features[(features[:,2] > 2) & (features[:,2] < 5)])

[[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.  2.3 3.3 1. ]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.1 1.3]
 [4.9 2.5 4.5 1.7]
 [5.6 2.8 4.9 2. ]
 [6.3 2.7 4.9 1.8]
 [6.2 2.8 4.8 1.8]
 [6.1 3.  4.9 1.8]
 [6.  3.  4.8 1.8]]

In [256]:
# 3
print(np.sum(features[:,3] > 1.5))

52

In [257]:
# 4
print(np.any(features[:,0] > 8))

False

In [258]:
# 5
print(np.all(features[:,3] > 0))

True

In [259]:
# 6
print(np.where(features > 5,100,0))

[[100   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]
 [100   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]
 [100   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [  0   0   0   0]
 [100   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]
 [100   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]
 [100   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]
 [100   0   0   0]
 [  0   0   0   0]
 [100   0   0   0]
 [  0   0   0   0]
 [100   0   0   0]
 [  0   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [  0   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [  0   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0 100   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [  0   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [  0   0   0   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0   0   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0   0   0]
 [100   0 100   0]
 [100   0   0   0]
 [100   0 100   0]
 [100   0   0   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0   0   0]
 [100   0   0   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0   0   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0   0   0]
 [100   0 100   0]
 [100   0 100   0]
 [100   0 100   0]]

In [260]:
# 7
con1 = labels == "virginica"
con2 = features[:,2] > 5
print(features[con1 & con2])

[[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]
 [6.5 3.2 5.1 2. ]
 [6.4 2.7 5.3 1.9]
 [6.8 3.  5.5 2.1]
 [5.8 2.8 5.1 2.4]
 [6.4 3.2 5.3 2.3]
 [6.5 3.  5.5 1.8]
 [7.7 3.8 6.7 2.2]
 [7.7 2.6 6.9 2.3]
 [6.9 3.2 5.7 2.3]
 [7.7 2.8 6.7 2. ]
 [6.7 3.3 5.7 2.1]
 [7.2 3.2 6.  1.8]
 [6.4 2.8 5.6 2.1]
 [7.2 3.  5.8 1.6]
 [7.4 2.8 6.1 1.9]
 [7.9 3.8 6.4 2. ]
 [6.4 2.8 5.6 2.2]
 [6.3 2.8 5.1 1.5]
 [6.1 2.6 5.6 1.4]
 [7.7 3.  6.1 2.3]
 [6.3 3.4 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [6.9 3.1 5.4 2.1]
 [6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]

In [261]:
# Broadcasting

In [262]:
a = np.array([1, 2, 3])

b = 5

In [263]:
a + b # It did not actually make  a new array [5,5,5] then add it, it acts as if it did

array([6, 7, 8])

In [264]:
offset = np.array([1, 2, 3, 4])

offset.shape

(4,)

In [265]:
features + offset

array([[6.1, 5.5, 4.4, 4.2],
       [5.9, 5. , 4.4, 4.2],
       [5.7, 5.2, 4.3, 4.2],
       [5.6, 5.1, 4.5, 4.2],
       [6. , 5.6, 4.4, 4.2],
       [6.4, 5.9, 4.7, 4.4],
       [5.6, 5.4, 4.4, 4.3],
       [6. , 5.4, 4.5, 4.2],
       [5.4, 4.9, 4.4, 4.2],
       [5.9, 5.1, 4.5, 4.1],
       [6.4, 5.7, 4.5, 4.2],
       [5.8, 5.4, 4.6, 4.2],
       [5.8, 5. , 4.4, 4.1],
       [5.3, 5. , 4.1, 4.1],
       [6.8, 6. , 4.2, 4.2],
       [6.7, 6.4, 4.5, 4.4],
       [6.4, 5.9, 4.3, 4.4],
       [6.1, 5.5, 4.4, 4.3],
       [6.7, 5.8, 4.7, 4.3],
       [6.1, 5.8, 4.5, 4.3],
       [6.4, 5.4, 4.7, 4.2],
       [6.1, 5.7, 4.5, 4.4],
       [5.6, 5.6, 4. , 4.2],
       [6.1, 5.3, 4.7, 4.5],
       [5.8, 5.4, 4.9, 4.2],
       [6. , 5. , 4.6, 4.2],
       [6. , 5.4, 4.6, 4.4],
       [6.2, 5.5, 4.5, 4.2],
       [6.2, 5.4, 4.4, 4.2],
       [5.7, 5.2, 4.6, 4.2],
       [5.8, 5.1, 4.6, 4.2],
       [6.4, 5.4, 4.5, 4.4],
       [6.2, 6.1, 4.5, 4.1],
       [6.5, 6.2, 4.4, 4.2],
       [5.9, 5.1, 4.5, 4.2],
       [6. , 5.2, 4.2, 4.2],
       [6.5, 5.5, 4.3, 4.2],
       [5.9, 5.6, 4.4, 4.1],
       [5.4, 5. , 4.3, 4.2],
       [6.1, 5.4, 4.5, 4.2],
       [6. , 5.5, 4.3, 4.3],
       [5.5, 4.3, 4.3, 4.3],
       [5.4, 5.2, 4.3, 4.2],
       [6. , 5.5, 4.6, 4.6],
       [6.1, 5.8, 4.9, 4.4],
       [5.8, 5. , 4.4, 4.3],
       [6.1, 5.8, 4.6, 4.2],
       [5.6, 5.2, 4.4, 4.2],
       [6.3, 5.7, 4.5, 4.2],
       [6. , 5.3, 4.4, 4.2],
       [8. , 5.2, 7.7, 5.4],
       [7.4, 5.2, 7.5, 5.5],
       [7.9, 5.1, 7.9, 5.5],
       [6.5, 4.3, 7. , 5.3],
       [7.5, 4.8, 7.6, 5.5],
       [6.7, 4.8, 7.5, 5.3],
       [7.3, 5.3, 7.7, 5.6],
       [5.9, 4.4, 6.3, 5. ],
       [7.6, 4.9, 7.6, 5.3],
       [6.2, 4.7, 6.9, 5.4],
       [6. , 4. , 6.5, 5. ],
       [6.9, 5. , 7.2, 5.5],
       [7. , 4.2, 7. , 5. ],
       [7.1, 4.9, 7.7, 5.4],
       [6.6, 4.9, 6.6, 5.3],
       [7.7, 5.1, 7.4, 5.4],
       [6.6, 5. , 7.5, 5.5],
       [6.8, 4.7, 7.1, 5. ],
       [7.2, 4.2, 7.5, 5.5],
       [6.6, 4.5, 6.9, 5.1],
       [6.9, 5.2, 7.8, 5.8],
       [7.1, 4.8, 7. , 5.3],
       [7.3, 4.5, 7.9, 5.5],
       [7.1, 4.8, 7.7, 5.2],
       [7.4, 4.9, 7.3, 5.3],
       [7.6, 5. , 7.4, 5.4],
       [7.8, 4.8, 7.8, 5.4],
       [7.7, 5. , 8. , 5.7],
       [7. , 4.9, 7.5, 5.5],
       [6.7, 4.6, 6.5, 5. ],
       [6.5, 4.4, 6.8, 5.1],
       [6.5, 4.4, 6.7, 5. ],
       [6.8, 4.7, 6.9, 5.2],
       [7. , 4.7, 8.1, 5.6],
       [6.4, 5. , 7.5, 5.5],
       [7. , 5.4, 7.5, 5.6],
       [7.7, 5.1, 7.7, 5.5],
       [7.3, 4.3, 7.4, 5.3],
       [6.6, 5. , 7.1, 5.3],
       [6.5, 4.5, 7. , 5.3],
       [6.5, 4.6, 7.4, 5.2],
       [7.1, 5. , 7.6, 5.4],
       [6.8, 4.6, 7. , 5.2],
       [6. , 4.3, 6.3, 5. ],
       [6.6, 4.7, 7.2, 5.3],
       [6.7, 5. , 7.2, 5.2],
       [6.7, 4.9, 7.2, 5.3],
       [7.2, 4.9, 7.3, 5.3],
       [6.1, 4.5, 6. , 5.1],
       [6.7, 4.8, 7.1, 5.3],
       [7.3, 5.3, 9. , 6.5],
       [6.8, 4.7, 8.1, 5.9],
       [8.1, 5. , 8.9, 6.1],
       [7.3, 4.9, 8.6, 5.8],
       [7.5, 5. , 8.8, 6.2],
       [8.6, 5. , 9.6, 6.1],
       [5.9, 4.5, 7.5, 5.7],
       [8.3, 4.9, 9.3, 5.8],
       [7.7, 4.5, 8.8, 5.8],
       [8.2, 5.6, 9.1, 6.5],
       [7.5, 5.2, 8.1, 6. ],
       [7.4, 4.7, 8.3, 5.9],
       [7.8, 5. , 8.5, 6.1],
       [6.7, 4.5, 8. , 6. ],
       [6.8, 4.8, 8.1, 6.4],
       [7.4, 5.2, 8.3, 6.3],
       [7.5, 5. , 8.5, 5.8],
       [8.7, 5.8, 9.7, 6.2],
       [8.7, 4.6, 9.9, 6.3],
       [7. , 4.2, 8. , 5.5],
       [7.9, 5.2, 8.7, 6.3],
       [6.6, 4.8, 7.9, 6. ],
       [8.7, 4.8, 9.7, 6. ],
       [7.3, 4.7, 7.9, 5.8],
       [7.7, 5.3, 8.7, 6.1],
       [8.2, 5.2, 9. , 5.8],
       [7.2, 4.8, 7.8, 5.8],
       [7.1, 5. , 7.9, 5.8],
       [7.4, 4.8, 8.6, 6.1],
       [8.2, 5. , 8.8, 5.6],
       [8.4, 4.8, 9.1, 5.9],
       [8.9, 5.8, 9.4, 6. ],
       [7.4, 4.8, 8.6, 6.2],
       [7.3, 4.8, 8.1, 5.5],
       [7.1, 4.6, 8.6, 5.4],
       [8.7, 5. , 9.1, 6.3],
       [7.3, 5.4, 8.6, 6.4],
       [7.4, 5.1, 8.5, 5.8],
       [7. , 5. , 7.8, 5.8],
       [7.9, 5.1, 8.4, 6.1],
       [7.7, 5.1, 8.6, 6.4],
       [7.9, 5.1, 8.1, 6.3],
       [6.8, 4.7, 8.1, 5.9],
       [7.8, 5.2, 8.9, 6.3],
       [7.7, 5.3, 8.7, 6.5],
       [7.7, 5. , 8.2, 6.3],
       [7.3, 4.5, 8. , 5.9],
       [7.5, 5. , 8.2, 6. ],
       [7.2, 5.4, 8.4, 6.3],
       [6.9, 5. , 8.1, 5.8]])

In [266]:
row_offset = np.arange(150)

row_offset.shape

(150,)

In [267]:
#features + row_offset

In [268]:
row_offset = row_offset.reshape(150,1)

row_offset.shape

(150, 1)

In [269]:
features + row_offset

array([[  5.1,   3.5,   1.4,   0.2],
       [  5.9,   4. ,   2.4,   1.2],
       [  6.7,   5.2,   3.3,   2.2],
       [  7.6,   6.1,   4.5,   3.2],
       [  9. ,   7.6,   5.4,   4.2],
       [ 10.4,   8.9,   6.7,   5.4],
       [ 10.6,   9.4,   7.4,   6.3],
       [ 12. ,  10.4,   8.5,   7.2],
       [ 12.4,  10.9,   9.4,   8.2],
       [ 13.9,  12.1,  10.5,   9.1],
       [ 15.4,  13.7,  11.5,  10.2],
       [ 15.8,  14.4,  12.6,  11.2],
       [ 16.8,  15. ,  13.4,  12.1],
       [ 17.3,  16. ,  14.1,  13.1],
       [ 19.8,  18. ,  15.2,  14.2],
       [ 20.7,  19.4,  16.5,  15.4],
       [ 21.4,  19.9,  17.3,  16.4],
       [ 22.1,  20.5,  18.4,  17.3],
       [ 23.7,  21.8,  19.7,  18.3],
       [ 24.1,  22.8,  20.5,  19.3],
       [ 25.4,  23.4,  21.7,  20.2],
       [ 26.1,  24.7,  22.5,  21.4],
       [ 26.6,  25.6,  23. ,  22.2],
       [ 28.1,  26.3,  24.7,  23.5],
       [ 28.8,  27.4,  25.9,  24.2],
       [ 30. ,  28. ,  26.6,  25.2],
       [ 31. ,  29.4,  27.6,  26.4],
       [ 32.2,  30.5,  28.5,  27.2],
       [ 33.2,  31.4,  29.4,  28.2],
       [ 33.7,  32.2,  30.6,  29.2],
       [ 34.8,  33.1,  31.6,  30.2],
       [ 36.4,  34.4,  32.5,  31.4],
       [ 37.2,  36.1,  33.5,  32.1],
       [ 38.5,  37.2,  34.4,  33.2],
       [ 38.9,  37.1,  35.5,  34.2],
       [ 40. ,  38.2,  36.2,  35.2],
       [ 41.5,  39.5,  37.3,  36.2],
       [ 41.9,  40.6,  38.4,  37.1],
       [ 42.4,  41. ,  39.3,  38.2],
       [ 44.1,  42.4,  40.5,  39.2],
       [ 45. ,  43.5,  41.3,  40.3],
       [ 45.5,  43.3,  42.3,  41.3],
       [ 46.4,  45.2,  43.3,  42.2],
       [ 48. ,  46.5,  44.6,  43.6],
       [ 49.1,  47.8,  45.9,  44.4],
       [ 49.8,  48. ,  46.4,  45.3],
       [ 51.1,  49.8,  47.6,  46.2],
       [ 51.6,  50.2,  48.4,  47.2],
       [ 53.3,  51.7,  49.5,  48.2],
       [ 54. ,  52.3,  50.4,  49.2],
       [ 57. ,  53.2,  54.7,  51.4],
       [ 57.4,  54.2,  55.5,  52.5],
       [ 58.9,  55.1,  56.9,  53.5],
       [ 58.5,  55.3,  57. ,  54.3],
       [ 60.5,  56.8,  58.6,  55.5],
       [ 60.7,  57.8,  59.5,  56.3],
       [ 62.3,  59.3,  60.7,  57.6],
       [ 61.9,  59.4,  60.3,  58. ],
       [ 64.6,  60.9,  62.6,  59.3],
       [ 64.2,  61.7,  62.9,  60.4],
       [ 65. ,  62. ,  63.5,  61. ],
       [ 66.9,  64. ,  65.2,  62.5],
       [ 68. ,  64.2,  66. ,  63. ],
       [ 69.1,  65.9,  67.7,  64.4],
       [ 69.6,  66.9,  67.6,  65.3],
       [ 71.7,  68.1,  69.4,  66.4],
       [ 71.6,  69. ,  70.5,  67.5],
       [ 72.8,  69.7,  71.1,  68. ],
       [ 74.2,  70.2,  72.5,  69.5],
       [ 74.6,  71.5,  72.9,  70.1],
       [ 75.9,  73.2,  74.8,  71.8],
       [ 77.1,  73.8,  75. ,  72.3],
       [ 78.3,  74.5,  76.9,  73.5],
       [ 79.1,  75.8,  77.7,  74.2],
       [ 80.4,  76.9,  78.3,  75.3],
       [ 81.6,  78. ,  79.4,  76.4],
       [ 82.8,  78.8,  80.8,  77.4],
       [ 83.7,  80. ,  82. ,  78.7],
       [ 84. ,  80.9,  82.5,  79.5],
       [ 84.7,  81.6,  82.5,  80. ],
       [ 85.5,  82.4,  83.8,  81.1],
       [ 86.5,  83.4,  84.7,  82. ],
       [ 87.8,  84.7,  85.9,  83.2],
       [ 89. ,  85.7,  88.1,  84.6],
       [ 89.4,  87. ,  88.5,  85.5],
       [ 91. ,  88.4,  89.5,  86.6],
       [ 92.7,  89.1,  90.7,  87.5],
       [ 93.3,  89.3,  91.4,  88.3],
       [ 93.6,  91. ,  92.1,  89.3],
       [ 94.5,  91.5,  93. ,  90.3],
       [ 95.5,  92.6,  94.4,  91.2],
       [ 97.1,  94. ,  95.6,  92.4],
       [ 97.8,  94.6,  96. ,  93.2],
       [ 98. ,  95.3,  96.3,  94. ],
       [ 99.6,  96.7,  98.2,  95.3],
       [100.7,  98. ,  99.2,  96.2],
       [101.7,  98.9, 100.2,  97.3],
       [103.2,  99.9, 101.3,  98.3],
       [103.1, 100.5, 101. ,  99.1],
       [104.7, 101.8, 103.1, 100.3],
       [106.3, 103.3, 106. , 102.5],
       [106.8, 103.7, 106.1, 102.9],
       [109.1, 105. , 107.9, 104.1],
       [109.3, 105.9, 108.6, 104.8],
       [110.5, 107. , 109.8, 106.2],
       [112.6, 108. , 111.6, 107.1],
       [110.9, 108.5, 110.5, 107.7],
       [114.3, 109.9, 113.3, 108.8],
       [114.7, 110.5, 113.8, 109.8],
       [116.2, 112.6, 115.1, 111.5],
       [116.5, 113.2, 115.1, 112. ],
       [117.4, 113.7, 116.3, 112.9],
       [118.8, 115. , 117.5, 114.1],
       [118.7, 115.5, 118. , 115. ],
       [119.8, 116.8, 119.1, 116.4],
       [121.4, 118.2, 120.3, 117.3],
       [122.5, 119. , 121.5, 117.8],
       [124.7, 120.8, 123.7, 119.2],
       [125.7, 120.6, 124.9, 120.3],
       [125. , 121.2, 124. , 120.5],
       [126.9, 123.2, 125.7, 122.3],
       [126.6, 123.8, 125.9, 123. ],
       [129.7, 124.8, 128.7, 124. ],
       [129.3, 125.7, 127.9, 124.8],
       [130.7, 127.3, 129.7, 126.1],
       [132.2, 128.2, 131. , 126.8],
       [132.2, 128.8, 130.8, 127.8],
       [133.1, 130. , 131.9, 128.8],
       [134.4, 130.8, 133.6, 130.1],
       [136.2, 132. , 134.8, 130.6],
       [137.4, 132.8, 136.1, 131.9],
       [138.9, 134.8, 137.4, 133. ],
       [138.4, 134.8, 137.6, 134.2],
       [139.3, 135.8, 138.1, 134.5],
       [140.1, 136.6, 139.6, 135.4],
       [142.7, 138. , 141.1, 137.3],
       [142.3, 139.4, 141.6, 138.4],
       [143.4, 140.1, 142.5, 138.8],
       [144. , 141. , 142.8, 139.8],
       [145.9, 142.1, 144.4, 141.1],
       [146.7, 143.1, 145.6, 142.4],
       [147.9, 144.1, 146.1, 143.3],
       [147.8, 144.7, 147.1, 143.9],
       [149.8, 146.2, 148.9, 145.3],
       [150.7, 147.3, 149.7, 146.5],
       [151.7, 148. , 150.2, 147.3],
       [152.3, 148.5, 151. , 147.9],
       [153.5, 150. , 152.2, 149. ],
       [154.2, 151.4, 153.4, 150.3],
       [154.9, 152. , 154.1, 150.8]])

In [270]:
scale = np.array([1,10,100,1000])

In [271]:
features * scale

array([[   5.1,   35. ,  140. ,  200. ],
       [   4.9,   30. ,  140. ,  200. ],
       [   4.7,   32. ,  130. ,  200. ],
       [   4.6,   31. ,  150. ,  200. ],
       [   5. ,   36. ,  140. ,  200. ],
       [   5.4,   39. ,  170. ,  400. ],
       [   4.6,   34. ,  140. ,  300. ],
       [   5. ,   34. ,  150. ,  200. ],
       [   4.4,   29. ,  140. ,  200. ],
       [   4.9,   31. ,  150. ,  100. ],
       [   5.4,   37. ,  150. ,  200. ],
       [   4.8,   34. ,  160. ,  200. ],
       [   4.8,   30. ,  140. ,  100. ],
       [   4.3,   30. ,  110. ,  100. ],
       [   5.8,   40. ,  120. ,  200. ],
       [   5.7,   44. ,  150. ,  400. ],
       [   5.4,   39. ,  130. ,  400. ],
       [   5.1,   35. ,  140. ,  300. ],
       [   5.7,   38. ,  170. ,  300. ],
       [   5.1,   38. ,  150. ,  300. ],
       [   5.4,   34. ,  170. ,  200. ],
       [   5.1,   37. ,  150. ,  400. ],
       [   4.6,   36. ,  100. ,  200. ],
       [   5.1,   33. ,  170. ,  500. ],
       [   4.8,   34. ,  190. ,  200. ],
       [   5. ,   30. ,  160. ,  200. ],
       [   5. ,   34. ,  160. ,  400. ],
       [   5.2,   35. ,  150. ,  200. ],
       [   5.2,   34. ,  140. ,  200. ],
       [   4.7,   32. ,  160. ,  200. ],
       [   4.8,   31. ,  160. ,  200. ],
       [   5.4,   34. ,  150. ,  400. ],
       [   5.2,   41. ,  150. ,  100. ],
       [   5.5,   42. ,  140. ,  200. ],
       [   4.9,   31. ,  150. ,  200. ],
       [   5. ,   32. ,  120. ,  200. ],
       [   5.5,   35. ,  130. ,  200. ],
       [   4.9,   36. ,  140. ,  100. ],
       [   4.4,   30. ,  130. ,  200. ],
       [   5.1,   34. ,  150. ,  200. ],
       [   5. ,   35. ,  130. ,  300. ],
       [   4.5,   23. ,  130. ,  300. ],
       [   4.4,   32. ,  130. ,  200. ],
       [   5. ,   35. ,  160. ,  600. ],
       [   5.1,   38. ,  190. ,  400. ],
       [   4.8,   30. ,  140. ,  300. ],
       [   5.1,   38. ,  160. ,  200. ],
       [   4.6,   32. ,  140. ,  200. ],
       [   5.3,   37. ,  150. ,  200. ],
       [   5. ,   33. ,  140. ,  200. ],
       [   7. ,   32. ,  470. , 1400. ],
       [   6.4,   32. ,  450. , 1500. ],
       [   6.9,   31. ,  490. , 1500. ],
       [   5.5,   23. ,  400. , 1300. ],
       [   6.5,   28. ,  460. , 1500. ],
       [   5.7,   28. ,  450. , 1300. ],
       [   6.3,   33. ,  470. , 1600. ],
       [   4.9,   24. ,  330. , 1000. ],
       [   6.6,   29. ,  460. , 1300. ],
       [   5.2,   27. ,  390. , 1400. ],
       [   5. ,   20. ,  350. , 1000. ],
       [   5.9,   30. ,  420. , 1500. ],
       [   6. ,   22. ,  400. , 1000. ],
       [   6.1,   29. ,  470. , 1400. ],
       [   5.6,   29. ,  360. , 1300. ],
       [   6.7,   31. ,  440. , 1400. ],
       [   5.6,   30. ,  450. , 1500. ],
       [   5.8,   27. ,  410. , 1000. ],
       [   6.2,   22. ,  450. , 1500. ],
       [   5.6,   25. ,  390. , 1100. ],
       [   5.9,   32. ,  480. , 1800. ],
       [   6.1,   28. ,  400. , 1300. ],
       [   6.3,   25. ,  490. , 1500. ],
       [   6.1,   28. ,  470. , 1200. ],
       [   6.4,   29. ,  430. , 1300. ],
       [   6.6,   30. ,  440. , 1400. ],
       [   6.8,   28. ,  480. , 1400. ],
       [   6.7,   30. ,  500. , 1700. ],
       [   6. ,   29. ,  450. , 1500. ],
       [   5.7,   26. ,  350. , 1000. ],
       [   5.5,   24. ,  380. , 1100. ],
       [   5.5,   24. ,  370. , 1000. ],
       [   5.8,   27. ,  390. , 1200. ],
       [   6. ,   27. ,  510. , 1600. ],
       [   5.4,   30. ,  450. , 1500. ],
       [   6. ,   34. ,  450. , 1600. ],
       [   6.7,   31. ,  470. , 1500. ],
       [   6.3,   23. ,  440. , 1300. ],
       [   5.6,   30. ,  410. , 1300. ],
       [   5.5,   25. ,  400. , 1300. ],
       [   5.5,   26. ,  440. , 1200. ],
       [   6.1,   30. ,  460. , 1400. ],
       [   5.8,   26. ,  400. , 1200. ],
       [   5. ,   23. ,  330. , 1000. ],
       [   5.6,   27. ,  420. , 1300. ],
       [   5.7,   30. ,  420. , 1200. ],
       [   5.7,   29. ,  420. , 1300. ],
       [   6.2,   29. ,  430. , 1300. ],
       [   5.1,   25. ,  300. , 1100. ],
       [   5.7,   28. ,  410. , 1300. ],
       [   6.3,   33. ,  600. , 2500. ],
       [   5.8,   27. ,  510. , 1900. ],
       [   7.1,   30. ,  590. , 2100. ],
       [   6.3,   29. ,  560. , 1800. ],
       [   6.5,   30. ,  580. , 2200. ],
       [   7.6,   30. ,  660. , 2100. ],
       [   4.9,   25. ,  450. , 1700. ],
       [   7.3,   29. ,  630. , 1800. ],
       [   6.7,   25. ,  580. , 1800. ],
       [   7.2,   36. ,  610. , 2500. ],
       [   6.5,   32. ,  510. , 2000. ],
       [   6.4,   27. ,  530. , 1900. ],
       [   6.8,   30. ,  550. , 2100. ],
       [   5.7,   25. ,  500. , 2000. ],
       [   5.8,   28. ,  510. , 2400. ],
       [   6.4,   32. ,  530. , 2300. ],
       [   6.5,   30. ,  550. , 1800. ],
       [   7.7,   38. ,  670. , 2200. ],
       [   7.7,   26. ,  690. , 2300. ],
       [   6. ,   22. ,  500. , 1500. ],
       [   6.9,   32. ,  570. , 2300. ],
       [   5.6,   28. ,  490. , 2000. ],
       [   7.7,   28. ,  670. , 2000. ],
       [   6.3,   27. ,  490. , 1800. ],
       [   6.7,   33. ,  570. , 2100. ],
       [   7.2,   32. ,  600. , 1800. ],
       [   6.2,   28. ,  480. , 1800. ],
       [   6.1,   30. ,  490. , 1800. ],
       [   6.4,   28. ,  560. , 2100. ],
       [   7.2,   30. ,  580. , 1600. ],
       [   7.4,   28. ,  610. , 1900. ],
       [   7.9,   38. ,  640. , 2000. ],
       [   6.4,   28. ,  560. , 2200. ],
       [   6.3,   28. ,  510. , 1500. ],
       [   6.1,   26. ,  560. , 1400. ],
       [   7.7,   30. ,  610. , 2300. ],
       [   6.3,   34. ,  560. , 2400. ],
       [   6.4,   31. ,  550. , 1800. ],
       [   6. ,   30. ,  480. , 1800. ],
       [   6.9,   31. ,  540. , 2100. ],
       [   6.7,   31. ,  560. , 2400. ],
       [   6.9,   31. ,  510. , 2300. ],
       [   5.8,   27. ,  510. , 1900. ],
       [   6.8,   32. ,  590. , 2300. ],
       [   6.7,   33. ,  570. , 2500. ],
       [   6.7,   30. ,  520. , 2300. ],
       [   6.3,   25. ,  500. , 1900. ],
       [   6.5,   30. ,  520. , 2000. ],
       [   6.2,   34. ,  540. , 2300. ],
       [   5.9,   30. ,  510. , 1800. ]])

In [272]:
means = np.mean(features, axis=0)

means.shape

(4,)

In [273]:
centered = features - means

In [274]:
np.mean(centered, axis=0)

array([-3.31586610e-16, -3.55271368e-16, -6.63173220e-16, -2.36847579e-16])

In [275]:
means = np.mean(features, axis=0)

stds = np.std(features, axis=0)

standardized = (features - means) / stds

In [276]:
np.mean(standardized, axis=0)

array([-4.73695157e-16, -7.81597009e-16, -4.26325641e-16, -4.73695157e-16])

In [277]:
np.std(standardized, axis=0)

array([1., 1., 1., 1.])

In [278]:
# exercise
# 1. Add [10, 20, 30, 40] to every row.
# 2. Multiply each feature by [2, 4, 6, 8].
# 3. Add a different number to every row using broadcasting.
# 4. Subtract the minimum value of each feature from that feature.
# 5. Divide every feature by its maximum value.
# 6. Standardize the dataset using broadcasting.
# 7. Verify that every standardized feature has mean ≈ 0 and standard deviation ≈ 1.

In [279]:
# 1
features + [10, 20, 30, 40]

array([[15.1, 23.5, 31.4, 40.2],
       [14.9, 23. , 31.4, 40.2],
       [14.7, 23.2, 31.3, 40.2],
       [14.6, 23.1, 31.5, 40.2],
       [15. , 23.6, 31.4, 40.2],
       [15.4, 23.9, 31.7, 40.4],
       [14.6, 23.4, 31.4, 40.3],
       [15. , 23.4, 31.5, 40.2],
       [14.4, 22.9, 31.4, 40.2],
       [14.9, 23.1, 31.5, 40.1],
       [15.4, 23.7, 31.5, 40.2],
       [14.8, 23.4, 31.6, 40.2],
       [14.8, 23. , 31.4, 40.1],
       [14.3, 23. , 31.1, 40.1],
       [15.8, 24. , 31.2, 40.2],
       [15.7, 24.4, 31.5, 40.4],
       [15.4, 23.9, 31.3, 40.4],
       [15.1, 23.5, 31.4, 40.3],
       [15.7, 23.8, 31.7, 40.3],
       [15.1, 23.8, 31.5, 40.3],
       [15.4, 23.4, 31.7, 40.2],
       [15.1, 23.7, 31.5, 40.4],
       [14.6, 23.6, 31. , 40.2],
       [15.1, 23.3, 31.7, 40.5],
       [14.8, 23.4, 31.9, 40.2],
       [15. , 23. , 31.6, 40.2],
       [15. , 23.4, 31.6, 40.4],
       [15.2, 23.5, 31.5, 40.2],
       [15.2, 23.4, 31.4, 40.2],
       [14.7, 23.2, 31.6, 40.2],
       [14.8, 23.1, 31.6, 40.2],
       [15.4, 23.4, 31.5, 40.4],
       [15.2, 24.1, 31.5, 40.1],
       [15.5, 24.2, 31.4, 40.2],
       [14.9, 23.1, 31.5, 40.2],
       [15. , 23.2, 31.2, 40.2],
       [15.5, 23.5, 31.3, 40.2],
       [14.9, 23.6, 31.4, 40.1],
       [14.4, 23. , 31.3, 40.2],
       [15.1, 23.4, 31.5, 40.2],
       [15. , 23.5, 31.3, 40.3],
       [14.5, 22.3, 31.3, 40.3],
       [14.4, 23.2, 31.3, 40.2],
       [15. , 23.5, 31.6, 40.6],
       [15.1, 23.8, 31.9, 40.4],
       [14.8, 23. , 31.4, 40.3],
       [15.1, 23.8, 31.6, 40.2],
       [14.6, 23.2, 31.4, 40.2],
       [15.3, 23.7, 31.5, 40.2],
       [15. , 23.3, 31.4, 40.2],
       [17. , 23.2, 34.7, 41.4],
       [16.4, 23.2, 34.5, 41.5],
       [16.9, 23.1, 34.9, 41.5],
       [15.5, 22.3, 34. , 41.3],
       [16.5, 22.8, 34.6, 41.5],
       [15.7, 22.8, 34.5, 41.3],
       [16.3, 23.3, 34.7, 41.6],
       [14.9, 22.4, 33.3, 41. ],
       [16.6, 22.9, 34.6, 41.3],
       [15.2, 22.7, 33.9, 41.4],
       [15. , 22. , 33.5, 41. ],
       [15.9, 23. , 34.2, 41.5],
       [16. , 22.2, 34. , 41. ],
       [16.1, 22.9, 34.7, 41.4],
       [15.6, 22.9, 33.6, 41.3],
       [16.7, 23.1, 34.4, 41.4],
       [15.6, 23. , 34.5, 41.5],
       [15.8, 22.7, 34.1, 41. ],
       [16.2, 22.2, 34.5, 41.5],
       [15.6, 22.5, 33.9, 41.1],
       [15.9, 23.2, 34.8, 41.8],
       [16.1, 22.8, 34. , 41.3],
       [16.3, 22.5, 34.9, 41.5],
       [16.1, 22.8, 34.7, 41.2],
       [16.4, 22.9, 34.3, 41.3],
       [16.6, 23. , 34.4, 41.4],
       [16.8, 22.8, 34.8, 41.4],
       [16.7, 23. , 35. , 41.7],
       [16. , 22.9, 34.5, 41.5],
       [15.7, 22.6, 33.5, 41. ],
       [15.5, 22.4, 33.8, 41.1],
       [15.5, 22.4, 33.7, 41. ],
       [15.8, 22.7, 33.9, 41.2],
       [16. , 22.7, 35.1, 41.6],
       [15.4, 23. , 34.5, 41.5],
       [16. , 23.4, 34.5, 41.6],
       [16.7, 23.1, 34.7, 41.5],
       [16.3, 22.3, 34.4, 41.3],
       [15.6, 23. , 34.1, 41.3],
       [15.5, 22.5, 34. , 41.3],
       [15.5, 22.6, 34.4, 41.2],
       [16.1, 23. , 34.6, 41.4],
       [15.8, 22.6, 34. , 41.2],
       [15. , 22.3, 33.3, 41. ],
       [15.6, 22.7, 34.2, 41.3],
       [15.7, 23. , 34.2, 41.2],
       [15.7, 22.9, 34.2, 41.3],
       [16.2, 22.9, 34.3, 41.3],
       [15.1, 22.5, 33. , 41.1],
       [15.7, 22.8, 34.1, 41.3],
       [16.3, 23.3, 36. , 42.5],
       [15.8, 22.7, 35.1, 41.9],
       [17.1, 23. , 35.9, 42.1],
       [16.3, 22.9, 35.6, 41.8],
       [16.5, 23. , 35.8, 42.2],
       [17.6, 23. , 36.6, 42.1],
       [14.9, 22.5, 34.5, 41.7],
       [17.3, 22.9, 36.3, 41.8],
       [16.7, 22.5, 35.8, 41.8],
       [17.2, 23.6, 36.1, 42.5],
       [16.5, 23.2, 35.1, 42. ],
       [16.4, 22.7, 35.3, 41.9],
       [16.8, 23. , 35.5, 42.1],
       [15.7, 22.5, 35. , 42. ],
       [15.8, 22.8, 35.1, 42.4],
       [16.4, 23.2, 35.3, 42.3],
       [16.5, 23. , 35.5, 41.8],
       [17.7, 23.8, 36.7, 42.2],
       [17.7, 22.6, 36.9, 42.3],
       [16. , 22.2, 35. , 41.5],
       [16.9, 23.2, 35.7, 42.3],
       [15.6, 22.8, 34.9, 42. ],
       [17.7, 22.8, 36.7, 42. ],
       [16.3, 22.7, 34.9, 41.8],
       [16.7, 23.3, 35.7, 42.1],
       [17.2, 23.2, 36. , 41.8],
       [16.2, 22.8, 34.8, 41.8],
       [16.1, 23. , 34.9, 41.8],
       [16.4, 22.8, 35.6, 42.1],
       [17.2, 23. , 35.8, 41.6],
       [17.4, 22.8, 36.1, 41.9],
       [17.9, 23.8, 36.4, 42. ],
       [16.4, 22.8, 35.6, 42.2],
       [16.3, 22.8, 35.1, 41.5],
       [16.1, 22.6, 35.6, 41.4],
       [17.7, 23. , 36.1, 42.3],
       [16.3, 23.4, 35.6, 42.4],
       [16.4, 23.1, 35.5, 41.8],
       [16. , 23. , 34.8, 41.8],
       [16.9, 23.1, 35.4, 42.1],
       [16.7, 23.1, 35.6, 42.4],
       [16.9, 23.1, 35.1, 42.3],
       [15.8, 22.7, 35.1, 41.9],
       [16.8, 23.2, 35.9, 42.3],
       [16.7, 23.3, 35.7, 42.5],
       [16.7, 23. , 35.2, 42.3],
       [16.3, 22.5, 35. , 41.9],
       [16.5, 23. , 35.2, 42. ],
       [16.2, 23.4, 35.4, 42.3],
       [15.9, 23. , 35.1, 41.8]])

In [280]:
# 2
features * [2, 4, 6, 8]

array([[10.2, 14. ,  8.4,  1.6],
       [ 9.8, 12. ,  8.4,  1.6],
       [ 9.4, 12.8,  7.8,  1.6],
       [ 9.2, 12.4,  9. ,  1.6],
       [10. , 14.4,  8.4,  1.6],
       [10.8, 15.6, 10.2,  3.2],
       [ 9.2, 13.6,  8.4,  2.4],
       [10. , 13.6,  9. ,  1.6],
       [ 8.8, 11.6,  8.4,  1.6],
       [ 9.8, 12.4,  9. ,  0.8],
       [10.8, 14.8,  9. ,  1.6],
       [ 9.6, 13.6,  9.6,  1.6],
       [ 9.6, 12. ,  8.4,  0.8],
       [ 8.6, 12. ,  6.6,  0.8],
       [11.6, 16. ,  7.2,  1.6],
       [11.4, 17.6,  9. ,  3.2],
       [10.8, 15.6,  7.8,  3.2],
       [10.2, 14. ,  8.4,  2.4],
       [11.4, 15.2, 10.2,  2.4],
       [10.2, 15.2,  9. ,  2.4],
       [10.8, 13.6, 10.2,  1.6],
       [10.2, 14.8,  9. ,  3.2],
       [ 9.2, 14.4,  6. ,  1.6],
       [10.2, 13.2, 10.2,  4. ],
       [ 9.6, 13.6, 11.4,  1.6],
       [10. , 12. ,  9.6,  1.6],
       [10. , 13.6,  9.6,  3.2],
       [10.4, 14. ,  9. ,  1.6],
       [10.4, 13.6,  8.4,  1.6],
       [ 9.4, 12.8,  9.6,  1.6],
       [ 9.6, 12.4,  9.6,  1.6],
       [10.8, 13.6,  9. ,  3.2],
       [10.4, 16.4,  9. ,  0.8],
       [11. , 16.8,  8.4,  1.6],
       [ 9.8, 12.4,  9. ,  1.6],
       [10. , 12.8,  7.2,  1.6],
       [11. , 14. ,  7.8,  1.6],
       [ 9.8, 14.4,  8.4,  0.8],
       [ 8.8, 12. ,  7.8,  1.6],
       [10.2, 13.6,  9. ,  1.6],
       [10. , 14. ,  7.8,  2.4],
       [ 9. ,  9.2,  7.8,  2.4],
       [ 8.8, 12.8,  7.8,  1.6],
       [10. , 14. ,  9.6,  4.8],
       [10.2, 15.2, 11.4,  3.2],
       [ 9.6, 12. ,  8.4,  2.4],
       [10.2, 15.2,  9.6,  1.6],
       [ 9.2, 12.8,  8.4,  1.6],
       [10.6, 14.8,  9. ,  1.6],
       [10. , 13.2,  8.4,  1.6],
       [14. , 12.8, 28.2, 11.2],
       [12.8, 12.8, 27. , 12. ],
       [13.8, 12.4, 29.4, 12. ],
       [11. ,  9.2, 24. , 10.4],
       [13. , 11.2, 27.6, 12. ],
       [11.4, 11.2, 27. , 10.4],
       [12.6, 13.2, 28.2, 12.8],
       [ 9.8,  9.6, 19.8,  8. ],
       [13.2, 11.6, 27.6, 10.4],
       [10.4, 10.8, 23.4, 11.2],
       [10. ,  8. , 21. ,  8. ],
       [11.8, 12. , 25.2, 12. ],
       [12. ,  8.8, 24. ,  8. ],
       [12.2, 11.6, 28.2, 11.2],
       [11.2, 11.6, 21.6, 10.4],
       [13.4, 12.4, 26.4, 11.2],
       [11.2, 12. , 27. , 12. ],
       [11.6, 10.8, 24.6,  8. ],
       [12.4,  8.8, 27. , 12. ],
       [11.2, 10. , 23.4,  8.8],
       [11.8, 12.8, 28.8, 14.4],
       [12.2, 11.2, 24. , 10.4],
       [12.6, 10. , 29.4, 12. ],
       [12.2, 11.2, 28.2,  9.6],
       [12.8, 11.6, 25.8, 10.4],
       [13.2, 12. , 26.4, 11.2],
       [13.6, 11.2, 28.8, 11.2],
       [13.4, 12. , 30. , 13.6],
       [12. , 11.6, 27. , 12. ],
       [11.4, 10.4, 21. ,  8. ],
       [11. ,  9.6, 22.8,  8.8],
       [11. ,  9.6, 22.2,  8. ],
       [11.6, 10.8, 23.4,  9.6],
       [12. , 10.8, 30.6, 12.8],
       [10.8, 12. , 27. , 12. ],
       [12. , 13.6, 27. , 12.8],
       [13.4, 12.4, 28.2, 12. ],
       [12.6,  9.2, 26.4, 10.4],
       [11.2, 12. , 24.6, 10.4],
       [11. , 10. , 24. , 10.4],
       [11. , 10.4, 26.4,  9.6],
       [12.2, 12. , 27.6, 11.2],
       [11.6, 10.4, 24. ,  9.6],
       [10. ,  9.2, 19.8,  8. ],
       [11.2, 10.8, 25.2, 10.4],
       [11.4, 12. , 25.2,  9.6],
       [11.4, 11.6, 25.2, 10.4],
       [12.4, 11.6, 25.8, 10.4],
       [10.2, 10. , 18. ,  8.8],
       [11.4, 11.2, 24.6, 10.4],
       [12.6, 13.2, 36. , 20. ],
       [11.6, 10.8, 30.6, 15.2],
       [14.2, 12. , 35.4, 16.8],
       [12.6, 11.6, 33.6, 14.4],
       [13. , 12. , 34.8, 17.6],
       [15.2, 12. , 39.6, 16.8],
       [ 9.8, 10. , 27. , 13.6],
       [14.6, 11.6, 37.8, 14.4],
       [13.4, 10. , 34.8, 14.4],
       [14.4, 14.4, 36.6, 20. ],
       [13. , 12.8, 30.6, 16. ],
       [12.8, 10.8, 31.8, 15.2],
       [13.6, 12. , 33. , 16.8],
       [11.4, 10. , 30. , 16. ],
       [11.6, 11.2, 30.6, 19.2],
       [12.8, 12.8, 31.8, 18.4],
       [13. , 12. , 33. , 14.4],
       [15.4, 15.2, 40.2, 17.6],
       [15.4, 10.4, 41.4, 18.4],
       [12. ,  8.8, 30. , 12. ],
       [13.8, 12.8, 34.2, 18.4],
       [11.2, 11.2, 29.4, 16. ],
       [15.4, 11.2, 40.2, 16. ],
       [12.6, 10.8, 29.4, 14.4],
       [13.4, 13.2, 34.2, 16.8],
       [14.4, 12.8, 36. , 14.4],
       [12.4, 11.2, 28.8, 14.4],
       [12.2, 12. , 29.4, 14.4],
       [12.8, 11.2, 33.6, 16.8],
       [14.4, 12. , 34.8, 12.8],
       [14.8, 11.2, 36.6, 15.2],
       [15.8, 15.2, 38.4, 16. ],
       [12.8, 11.2, 33.6, 17.6],
       [12.6, 11.2, 30.6, 12. ],
       [12.2, 10.4, 33.6, 11.2],
       [15.4, 12. , 36.6, 18.4],
       [12.6, 13.6, 33.6, 19.2],
       [12.8, 12.4, 33. , 14.4],
       [12. , 12. , 28.8, 14.4],
       [13.8, 12.4, 32.4, 16.8],
       [13.4, 12.4, 33.6, 19.2],
       [13.8, 12.4, 30.6, 18.4],
       [11.6, 10.8, 30.6, 15.2],
       [13.6, 12.8, 35.4, 18.4],
       [13.4, 13.2, 34.2, 20. ],
       [13.4, 12. , 31.2, 18.4],
       [12.6, 10. , 30. , 15.2],
       [13. , 12. , 31.2, 16. ],
       [12.4, 13.6, 32.4, 18.4],
       [11.8, 12. , 30.6, 14.4]])

In [281]:
# 3
temp = np.arange(150).reshape(150,1)
features + temp

array([[  5.1,   3.5,   1.4,   0.2],
       [  5.9,   4. ,   2.4,   1.2],
       [  6.7,   5.2,   3.3,   2.2],
       [  7.6,   6.1,   4.5,   3.2],
       [  9. ,   7.6,   5.4,   4.2],
       [ 10.4,   8.9,   6.7,   5.4],
       [ 10.6,   9.4,   7.4,   6.3],
       [ 12. ,  10.4,   8.5,   7.2],
       [ 12.4,  10.9,   9.4,   8.2],
       [ 13.9,  12.1,  10.5,   9.1],
       [ 15.4,  13.7,  11.5,  10.2],
       [ 15.8,  14.4,  12.6,  11.2],
       [ 16.8,  15. ,  13.4,  12.1],
       [ 17.3,  16. ,  14.1,  13.1],
       [ 19.8,  18. ,  15.2,  14.2],
       [ 20.7,  19.4,  16.5,  15.4],
       [ 21.4,  19.9,  17.3,  16.4],
       [ 22.1,  20.5,  18.4,  17.3],
       [ 23.7,  21.8,  19.7,  18.3],
       [ 24.1,  22.8,  20.5,  19.3],
       [ 25.4,  23.4,  21.7,  20.2],
       [ 26.1,  24.7,  22.5,  21.4],
       [ 26.6,  25.6,  23. ,  22.2],
       [ 28.1,  26.3,  24.7,  23.5],
       [ 28.8,  27.4,  25.9,  24.2],
       [ 30. ,  28. ,  26.6,  25.2],
       [ 31. ,  29.4,  27.6,  26.4],
       [ 32.2,  30.5,  28.5,  27.2],
       [ 33.2,  31.4,  29.4,  28.2],
       [ 33.7,  32.2,  30.6,  29.2],
       [ 34.8,  33.1,  31.6,  30.2],
       [ 36.4,  34.4,  32.5,  31.4],
       [ 37.2,  36.1,  33.5,  32.1],
       [ 38.5,  37.2,  34.4,  33.2],
       [ 38.9,  37.1,  35.5,  34.2],
       [ 40. ,  38.2,  36.2,  35.2],
       [ 41.5,  39.5,  37.3,  36.2],
       [ 41.9,  40.6,  38.4,  37.1],
       [ 42.4,  41. ,  39.3,  38.2],
       [ 44.1,  42.4,  40.5,  39.2],
       [ 45. ,  43.5,  41.3,  40.3],
       [ 45.5,  43.3,  42.3,  41.3],
       [ 46.4,  45.2,  43.3,  42.2],
       [ 48. ,  46.5,  44.6,  43.6],
       [ 49.1,  47.8,  45.9,  44.4],
       [ 49.8,  48. ,  46.4,  45.3],
       [ 51.1,  49.8,  47.6,  46.2],
       [ 51.6,  50.2,  48.4,  47.2],
       [ 53.3,  51.7,  49.5,  48.2],
       [ 54. ,  52.3,  50.4,  49.2],
       [ 57. ,  53.2,  54.7,  51.4],
       [ 57.4,  54.2,  55.5,  52.5],
       [ 58.9,  55.1,  56.9,  53.5],
       [ 58.5,  55.3,  57. ,  54.3],
       [ 60.5,  56.8,  58.6,  55.5],
       [ 60.7,  57.8,  59.5,  56.3],
       [ 62.3,  59.3,  60.7,  57.6],
       [ 61.9,  59.4,  60.3,  58. ],
       [ 64.6,  60.9,  62.6,  59.3],
       [ 64.2,  61.7,  62.9,  60.4],
       [ 65. ,  62. ,  63.5,  61. ],
       [ 66.9,  64. ,  65.2,  62.5],
       [ 68. ,  64.2,  66. ,  63. ],
       [ 69.1,  65.9,  67.7,  64.4],
       [ 69.6,  66.9,  67.6,  65.3],
       [ 71.7,  68.1,  69.4,  66.4],
       [ 71.6,  69. ,  70.5,  67.5],
       [ 72.8,  69.7,  71.1,  68. ],
       [ 74.2,  70.2,  72.5,  69.5],
       [ 74.6,  71.5,  72.9,  70.1],
       [ 75.9,  73.2,  74.8,  71.8],
       [ 77.1,  73.8,  75. ,  72.3],
       [ 78.3,  74.5,  76.9,  73.5],
       [ 79.1,  75.8,  77.7,  74.2],
       [ 80.4,  76.9,  78.3,  75.3],
       [ 81.6,  78. ,  79.4,  76.4],
       [ 82.8,  78.8,  80.8,  77.4],
       [ 83.7,  80. ,  82. ,  78.7],
       [ 84. ,  80.9,  82.5,  79.5],
       [ 84.7,  81.6,  82.5,  80. ],
       [ 85.5,  82.4,  83.8,  81.1],
       [ 86.5,  83.4,  84.7,  82. ],
       [ 87.8,  84.7,  85.9,  83.2],
       [ 89. ,  85.7,  88.1,  84.6],
       [ 89.4,  87. ,  88.5,  85.5],
       [ 91. ,  88.4,  89.5,  86.6],
       [ 92.7,  89.1,  90.7,  87.5],
       [ 93.3,  89.3,  91.4,  88.3],
       [ 93.6,  91. ,  92.1,  89.3],
       [ 94.5,  91.5,  93. ,  90.3],
       [ 95.5,  92.6,  94.4,  91.2],
       [ 97.1,  94. ,  95.6,  92.4],
       [ 97.8,  94.6,  96. ,  93.2],
       [ 98. ,  95.3,  96.3,  94. ],
       [ 99.6,  96.7,  98.2,  95.3],
       [100.7,  98. ,  99.2,  96.2],
       [101.7,  98.9, 100.2,  97.3],
       [103.2,  99.9, 101.3,  98.3],
       [103.1, 100.5, 101. ,  99.1],
       [104.7, 101.8, 103.1, 100.3],
       [106.3, 103.3, 106. , 102.5],
       [106.8, 103.7, 106.1, 102.9],
       [109.1, 105. , 107.9, 104.1],
       [109.3, 105.9, 108.6, 104.8],
       [110.5, 107. , 109.8, 106.2],
       [112.6, 108. , 111.6, 107.1],
       [110.9, 108.5, 110.5, 107.7],
       [114.3, 109.9, 113.3, 108.8],
       [114.7, 110.5, 113.8, 109.8],
       [116.2, 112.6, 115.1, 111.5],
       [116.5, 113.2, 115.1, 112. ],
       [117.4, 113.7, 116.3, 112.9],
       [118.8, 115. , 117.5, 114.1],
       [118.7, 115.5, 118. , 115. ],
       [119.8, 116.8, 119.1, 116.4],
       [121.4, 118.2, 120.3, 117.3],
       [122.5, 119. , 121.5, 117.8],
       [124.7, 120.8, 123.7, 119.2],
       [125.7, 120.6, 124.9, 120.3],
       [125. , 121.2, 124. , 120.5],
       [126.9, 123.2, 125.7, 122.3],
       [126.6, 123.8, 125.9, 123. ],
       [129.7, 124.8, 128.7, 124. ],
       [129.3, 125.7, 127.9, 124.8],
       [130.7, 127.3, 129.7, 126.1],
       [132.2, 128.2, 131. , 126.8],
       [132.2, 128.8, 130.8, 127.8],
       [133.1, 130. , 131.9, 128.8],
       [134.4, 130.8, 133.6, 130.1],
       [136.2, 132. , 134.8, 130.6],
       [137.4, 132.8, 136.1, 131.9],
       [138.9, 134.8, 137.4, 133. ],
       [138.4, 134.8, 137.6, 134.2],
       [139.3, 135.8, 138.1, 134.5],
       [140.1, 136.6, 139.6, 135.4],
       [142.7, 138. , 141.1, 137.3],
       [142.3, 139.4, 141.6, 138.4],
       [143.4, 140.1, 142.5, 138.8],
       [144. , 141. , 142.8, 139.8],
       [145.9, 142.1, 144.4, 141.1],
       [146.7, 143.1, 145.6, 142.4],
       [147.9, 144.1, 146.1, 143.3],
       [147.8, 144.7, 147.1, 143.9],
       [149.8, 146.2, 148.9, 145.3],
       [150.7, 147.3, 149.7, 146.5],
       [151.7, 148. , 150.2, 147.3],
       [152.3, 148.5, 151. , 147.9],
       [153.5, 150. , 152.2, 149. ],
       [154.2, 151.4, 153.4, 150.3],
       [154.9, 152. , 154.1, 150.8]])

In [282]:
# 4
min_feat = np.min(features, axis=0)
features - min_feat

array([[0.8, 1.5, 0.4, 0.1],
       [0.6, 1. , 0.4, 0.1],
       [0.4, 1.2, 0.3, 0.1],
       [0.3, 1.1, 0.5, 0.1],
       [0.7, 1.6, 0.4, 0.1],
       [1.1, 1.9, 0.7, 0.3],
       [0.3, 1.4, 0.4, 0.2],
       [0.7, 1.4, 0.5, 0.1],
       [0.1, 0.9, 0.4, 0.1],
       [0.6, 1.1, 0.5, 0. ],
       [1.1, 1.7, 0.5, 0.1],
       [0.5, 1.4, 0.6, 0.1],
       [0.5, 1. , 0.4, 0. ],
       [0. , 1. , 0.1, 0. ],
       [1.5, 2. , 0.2, 0.1],
       [1.4, 2.4, 0.5, 0.3],
       [1.1, 1.9, 0.3, 0.3],
       [0.8, 1.5, 0.4, 0.2],
       [1.4, 1.8, 0.7, 0.2],
       [0.8, 1.8, 0.5, 0.2],
       [1.1, 1.4, 0.7, 0.1],
       [0.8, 1.7, 0.5, 0.3],
       [0.3, 1.6, 0. , 0.1],
       [0.8, 1.3, 0.7, 0.4],
       [0.5, 1.4, 0.9, 0.1],
       [0.7, 1. , 0.6, 0.1],
       [0.7, 1.4, 0.6, 0.3],
       [0.9, 1.5, 0.5, 0.1],
       [0.9, 1.4, 0.4, 0.1],
       [0.4, 1.2, 0.6, 0.1],
       [0.5, 1.1, 0.6, 0.1],
       [1.1, 1.4, 0.5, 0.3],
       [0.9, 2.1, 0.5, 0. ],
       [1.2, 2.2, 0.4, 0.1],
       [0.6, 1.1, 0.5, 0.1],
       [0.7, 1.2, 0.2, 0.1],
       [1.2, 1.5, 0.3, 0.1],
       [0.6, 1.6, 0.4, 0. ],
       [0.1, 1. , 0.3, 0.1],
       [0.8, 1.4, 0.5, 0.1],
       [0.7, 1.5, 0.3, 0.2],
       [0.2, 0.3, 0.3, 0.2],
       [0.1, 1.2, 0.3, 0.1],
       [0.7, 1.5, 0.6, 0.5],
       [0.8, 1.8, 0.9, 0.3],
       [0.5, 1. , 0.4, 0.2],
       [0.8, 1.8, 0.6, 0.1],
       [0.3, 1.2, 0.4, 0.1],
       [1. , 1.7, 0.5, 0.1],
       [0.7, 1.3, 0.4, 0.1],
       [2.7, 1.2, 3.7, 1.3],
       [2.1, 1.2, 3.5, 1.4],
       [2.6, 1.1, 3.9, 1.4],
       [1.2, 0.3, 3. , 1.2],
       [2.2, 0.8, 3.6, 1.4],
       [1.4, 0.8, 3.5, 1.2],
       [2. , 1.3, 3.7, 1.5],
       [0.6, 0.4, 2.3, 0.9],
       [2.3, 0.9, 3.6, 1.2],
       [0.9, 0.7, 2.9, 1.3],
       [0.7, 0. , 2.5, 0.9],
       [1.6, 1. , 3.2, 1.4],
       [1.7, 0.2, 3. , 0.9],
       [1.8, 0.9, 3.7, 1.3],
       [1.3, 0.9, 2.6, 1.2],
       [2.4, 1.1, 3.4, 1.3],
       [1.3, 1. , 3.5, 1.4],
       [1.5, 0.7, 3.1, 0.9],
       [1.9, 0.2, 3.5, 1.4],
       [1.3, 0.5, 2.9, 1. ],
       [1.6, 1.2, 3.8, 1.7],
       [1.8, 0.8, 3. , 1.2],
       [2. , 0.5, 3.9, 1.4],
       [1.8, 0.8, 3.7, 1.1],
       [2.1, 0.9, 3.3, 1.2],
       [2.3, 1. , 3.4, 1.3],
       [2.5, 0.8, 3.8, 1.3],
       [2.4, 1. , 4. , 1.6],
       [1.7, 0.9, 3.5, 1.4],
       [1.4, 0.6, 2.5, 0.9],
       [1.2, 0.4, 2.8, 1. ],
       [1.2, 0.4, 2.7, 0.9],
       [1.5, 0.7, 2.9, 1.1],
       [1.7, 0.7, 4.1, 1.5],
       [1.1, 1. , 3.5, 1.4],
       [1.7, 1.4, 3.5, 1.5],
       [2.4, 1.1, 3.7, 1.4],
       [2. , 0.3, 3.4, 1.2],
       [1.3, 1. , 3.1, 1.2],
       [1.2, 0.5, 3. , 1.2],
       [1.2, 0.6, 3.4, 1.1],
       [1.8, 1. , 3.6, 1.3],
       [1.5, 0.6, 3. , 1.1],
       [0.7, 0.3, 2.3, 0.9],
       [1.3, 0.7, 3.2, 1.2],
       [1.4, 1. , 3.2, 1.1],
       [1.4, 0.9, 3.2, 1.2],
       [1.9, 0.9, 3.3, 1.2],
       [0.8, 0.5, 2. , 1. ],
       [1.4, 0.8, 3.1, 1.2],
       [2. , 1.3, 5. , 2.4],
       [1.5, 0.7, 4.1, 1.8],
       [2.8, 1. , 4.9, 2. ],
       [2. , 0.9, 4.6, 1.7],
       [2.2, 1. , 4.8, 2.1],
       [3.3, 1. , 5.6, 2. ],
       [0.6, 0.5, 3.5, 1.6],
       [3. , 0.9, 5.3, 1.7],
       [2.4, 0.5, 4.8, 1.7],
       [2.9, 1.6, 5.1, 2.4],
       [2.2, 1.2, 4.1, 1.9],
       [2.1, 0.7, 4.3, 1.8],
       [2.5, 1. , 4.5, 2. ],
       [1.4, 0.5, 4. , 1.9],
       [1.5, 0.8, 4.1, 2.3],
       [2.1, 1.2, 4.3, 2.2],
       [2.2, 1. , 4.5, 1.7],
       [3.4, 1.8, 5.7, 2.1],
       [3.4, 0.6, 5.9, 2.2],
       [1.7, 0.2, 4. , 1.4],
       [2.6, 1.2, 4.7, 2.2],
       [1.3, 0.8, 3.9, 1.9],
       [3.4, 0.8, 5.7, 1.9],
       [2. , 0.7, 3.9, 1.7],
       [2.4, 1.3, 4.7, 2. ],
       [2.9, 1.2, 5. , 1.7],
       [1.9, 0.8, 3.8, 1.7],
       [1.8, 1. , 3.9, 1.7],
       [2.1, 0.8, 4.6, 2. ],
       [2.9, 1. , 4.8, 1.5],
       [3.1, 0.8, 5.1, 1.8],
       [3.6, 1.8, 5.4, 1.9],
       [2.1, 0.8, 4.6, 2.1],
       [2. , 0.8, 4.1, 1.4],
       [1.8, 0.6, 4.6, 1.3],
       [3.4, 1. , 5.1, 2.2],
       [2. , 1.4, 4.6, 2.3],
       [2.1, 1.1, 4.5, 1.7],
       [1.7, 1. , 3.8, 1.7],
       [2.6, 1.1, 4.4, 2. ],
       [2.4, 1.1, 4.6, 2.3],
       [2.6, 1.1, 4.1, 2.2],
       [1.5, 0.7, 4.1, 1.8],
       [2.5, 1.2, 4.9, 2.2],
       [2.4, 1.3, 4.7, 2.4],
       [2.4, 1. , 4.2, 2.2],
       [2. , 0.5, 4. , 1.8],
       [2.2, 1. , 4.2, 1.9],
       [1.9, 1.4, 4.4, 2.2],
       [1.6, 1. , 4.1, 1.7]])

In [283]:
# 5
max_feat = np.max(features, axis=0)
features / max_feat

array([[0.64556962, 0.79545455, 0.20289855, 0.08      ],
       [0.62025316, 0.68181818, 0.20289855, 0.08      ],
       [0.59493671, 0.72727273, 0.1884058 , 0.08      ],
       [0.58227848, 0.70454545, 0.2173913 , 0.08      ],
       [0.63291139, 0.81818182, 0.20289855, 0.08      ],
       [0.6835443 , 0.88636364, 0.24637681, 0.16      ],
       [0.58227848, 0.77272727, 0.20289855, 0.12      ],
       [0.63291139, 0.77272727, 0.2173913 , 0.08      ],
       [0.55696203, 0.65909091, 0.20289855, 0.08      ],
       [0.62025316, 0.70454545, 0.2173913 , 0.04      ],
       [0.6835443 , 0.84090909, 0.2173913 , 0.08      ],
       [0.60759494, 0.77272727, 0.23188406, 0.08      ],
       [0.60759494, 0.68181818, 0.20289855, 0.04      ],
       [0.5443038 , 0.68181818, 0.15942029, 0.04      ],
       [0.73417722, 0.90909091, 0.17391304, 0.08      ],
       [0.72151899, 1.        , 0.2173913 , 0.16      ],
       [0.6835443 , 0.88636364, 0.1884058 , 0.16      ],
       [0.64556962, 0.79545455, 0.20289855, 0.12      ],
       [0.72151899, 0.86363636, 0.24637681, 0.12      ],
       [0.64556962, 0.86363636, 0.2173913 , 0.12      ],
       [0.6835443 , 0.77272727, 0.24637681, 0.08      ],
       [0.64556962, 0.84090909, 0.2173913 , 0.16      ],
       [0.58227848, 0.81818182, 0.14492754, 0.08      ],
       [0.64556962, 0.75      , 0.24637681, 0.2       ],
       [0.60759494, 0.77272727, 0.27536232, 0.08      ],
       [0.63291139, 0.68181818, 0.23188406, 0.08      ],
       [0.63291139, 0.77272727, 0.23188406, 0.16      ],
       [0.65822785, 0.79545455, 0.2173913 , 0.08      ],
       [0.65822785, 0.77272727, 0.20289855, 0.08      ],
       [0.59493671, 0.72727273, 0.23188406, 0.08      ],
       [0.60759494, 0.70454545, 0.23188406, 0.08      ],
       [0.6835443 , 0.77272727, 0.2173913 , 0.16      ],
       [0.65822785, 0.93181818, 0.2173913 , 0.04      ],
       [0.69620253, 0.95454545, 0.20289855, 0.08      ],
       [0.62025316, 0.70454545, 0.2173913 , 0.08      ],
       [0.63291139, 0.72727273, 0.17391304, 0.08      ],
       [0.69620253, 0.79545455, 0.1884058 , 0.08      ],
       [0.62025316, 0.81818182, 0.20289855, 0.04      ],
       [0.55696203, 0.68181818, 0.1884058 , 0.08      ],
       [0.64556962, 0.77272727, 0.2173913 , 0.08      ],
       [0.63291139, 0.79545455, 0.1884058 , 0.12      ],
       [0.56962025, 0.52272727, 0.1884058 , 0.12      ],
       [0.55696203, 0.72727273, 0.1884058 , 0.08      ],
       [0.63291139, 0.79545455, 0.23188406, 0.24      ],
       [0.64556962, 0.86363636, 0.27536232, 0.16      ],
       [0.60759494, 0.68181818, 0.20289855, 0.12      ],
       [0.64556962, 0.86363636, 0.23188406, 0.08      ],
       [0.58227848, 0.72727273, 0.20289855, 0.08      ],
       [0.67088608, 0.84090909, 0.2173913 , 0.08      ],
       [0.63291139, 0.75      , 0.20289855, 0.08      ],
       [0.88607595, 0.72727273, 0.68115942, 0.56      ],
       [0.81012658, 0.72727273, 0.65217391, 0.6       ],
       [0.87341772, 0.70454545, 0.71014493, 0.6       ],
       [0.69620253, 0.52272727, 0.57971014, 0.52      ],
       [0.82278481, 0.63636364, 0.66666667, 0.6       ],
       [0.72151899, 0.63636364, 0.65217391, 0.52      ],
       [0.79746835, 0.75      , 0.68115942, 0.64      ],
       [0.62025316, 0.54545455, 0.47826087, 0.4       ],
       [0.83544304, 0.65909091, 0.66666667, 0.52      ],
       [0.65822785, 0.61363636, 0.56521739, 0.56      ],
       [0.63291139, 0.45454545, 0.50724638, 0.4       ],
       [0.74683544, 0.68181818, 0.60869565, 0.6       ],
       [0.75949367, 0.5       , 0.57971014, 0.4       ],
       [0.7721519 , 0.65909091, 0.68115942, 0.56      ],
       [0.70886076, 0.65909091, 0.52173913, 0.52      ],
       [0.84810127, 0.70454545, 0.63768116, 0.56      ],
       [0.70886076, 0.68181818, 0.65217391, 0.6       ],
       [0.73417722, 0.61363636, 0.5942029 , 0.4       ],
       [0.78481013, 0.5       , 0.65217391, 0.6       ],
       [0.70886076, 0.56818182, 0.56521739, 0.44      ],
       [0.74683544, 0.72727273, 0.69565217, 0.72      ],
       [0.7721519 , 0.63636364, 0.57971014, 0.52      ],
       [0.79746835, 0.56818182, 0.71014493, 0.6       ],
       [0.7721519 , 0.63636364, 0.68115942, 0.48      ],
       [0.81012658, 0.65909091, 0.62318841, 0.52      ],
       [0.83544304, 0.68181818, 0.63768116, 0.56      ],
       [0.86075949, 0.63636364, 0.69565217, 0.56      ],
       [0.84810127, 0.68181818, 0.72463768, 0.68      ],
       [0.75949367, 0.65909091, 0.65217391, 0.6       ],
       [0.72151899, 0.59090909, 0.50724638, 0.4       ],
       [0.69620253, 0.54545455, 0.55072464, 0.44      ],
       [0.69620253, 0.54545455, 0.53623188, 0.4       ],
       [0.73417722, 0.61363636, 0.56521739, 0.48      ],
       [0.75949367, 0.61363636, 0.73913043, 0.64      ],
       [0.6835443 , 0.68181818, 0.65217391, 0.6       ],
       [0.75949367, 0.77272727, 0.65217391, 0.64      ],
       [0.84810127, 0.70454545, 0.68115942, 0.6       ],
       [0.79746835, 0.52272727, 0.63768116, 0.52      ],
       [0.70886076, 0.68181818, 0.5942029 , 0.52      ],
       [0.69620253, 0.56818182, 0.57971014, 0.52      ],
       [0.69620253, 0.59090909, 0.63768116, 0.48      ],
       [0.7721519 , 0.68181818, 0.66666667, 0.56      ],
       [0.73417722, 0.59090909, 0.57971014, 0.48      ],
       [0.63291139, 0.52272727, 0.47826087, 0.4       ],
       [0.70886076, 0.61363636, 0.60869565, 0.52      ],
       [0.72151899, 0.68181818, 0.60869565, 0.48      ],
       [0.72151899, 0.65909091, 0.60869565, 0.52      ],
       [0.78481013, 0.65909091, 0.62318841, 0.52      ],
       [0.64556962, 0.56818182, 0.43478261, 0.44      ],
       [0.72151899, 0.63636364, 0.5942029 , 0.52      ],
       [0.79746835, 0.75      , 0.86956522, 1.        ],
       [0.73417722, 0.61363636, 0.73913043, 0.76      ],
       [0.89873418, 0.68181818, 0.85507246, 0.84      ],
       [0.79746835, 0.65909091, 0.8115942 , 0.72      ],
       [0.82278481, 0.68181818, 0.84057971, 0.88      ],
       [0.96202532, 0.68181818, 0.95652174, 0.84      ],
       [0.62025316, 0.56818182, 0.65217391, 0.68      ],
       [0.92405063, 0.65909091, 0.91304348, 0.72      ],
       [0.84810127, 0.56818182, 0.84057971, 0.72      ],
       [0.91139241, 0.81818182, 0.88405797, 1.        ],
       [0.82278481, 0.72727273, 0.73913043, 0.8       ],
       [0.81012658, 0.61363636, 0.76811594, 0.76      ],
       [0.86075949, 0.68181818, 0.79710145, 0.84      ],
       [0.72151899, 0.56818182, 0.72463768, 0.8       ],
       [0.73417722, 0.63636364, 0.73913043, 0.96      ],
       [0.81012658, 0.72727273, 0.76811594, 0.92      ],
       [0.82278481, 0.68181818, 0.79710145, 0.72      ],
       [0.97468354, 0.86363636, 0.97101449, 0.88      ],
       [0.97468354, 0.59090909, 1.        , 0.92      ],
       [0.75949367, 0.5       , 0.72463768, 0.6       ],
       [0.87341772, 0.72727273, 0.82608696, 0.92      ],
       [0.70886076, 0.63636364, 0.71014493, 0.8       ],
       [0.97468354, 0.63636364, 0.97101449, 0.8       ],
       [0.79746835, 0.61363636, 0.71014493, 0.72      ],
       [0.84810127, 0.75      , 0.82608696, 0.84      ],
       [0.91139241, 0.72727273, 0.86956522, 0.72      ],
       [0.78481013, 0.63636364, 0.69565217, 0.72      ],
       [0.7721519 , 0.68181818, 0.71014493, 0.72      ],
       [0.81012658, 0.63636364, 0.8115942 , 0.84      ],
       [0.91139241, 0.68181818, 0.84057971, 0.64      ],
       [0.93670886, 0.63636364, 0.88405797, 0.76      ],
       [1.        , 0.86363636, 0.92753623, 0.8       ],
       [0.81012658, 0.63636364, 0.8115942 , 0.88      ],
       [0.79746835, 0.63636364, 0.73913043, 0.6       ],
       [0.7721519 , 0.59090909, 0.8115942 , 0.56      ],
       [0.97468354, 0.68181818, 0.88405797, 0.92      ],
       [0.79746835, 0.77272727, 0.8115942 , 0.96      ],
       [0.81012658, 0.70454545, 0.79710145, 0.72      ],
       [0.75949367, 0.68181818, 0.69565217, 0.72      ],
       [0.87341772, 0.70454545, 0.7826087 , 0.84      ],
       [0.84810127, 0.70454545, 0.8115942 , 0.96      ],
       [0.87341772, 0.70454545, 0.73913043, 0.92      ],
       [0.73417722, 0.61363636, 0.73913043, 0.76      ],
       [0.86075949, 0.72727273, 0.85507246, 0.92      ],
       [0.84810127, 0.75      , 0.82608696, 1.        ],
       [0.84810127, 0.68181818, 0.75362319, 0.92      ],
       [0.79746835, 0.56818182, 0.72463768, 0.76      ],
       [0.82278481, 0.68181818, 0.75362319, 0.8       ],
       [0.78481013, 0.77272727, 0.7826087 , 0.92      ],
       [0.74683544, 0.68181818, 0.73913043, 0.72      ]])

In [284]:
# 6 
means = np.mean(features, axis=0)
stds = np.std(features, axis=0)
standardized = (features - means) / stds

In [285]:
# 7
standardized_means = np.mean(standardized, axis=0)
standardized_stds = np.std(standardized, axis=0)
print(standardized_means)
print(standardized_stds)

[-4.73695157e-16 -7.81597009e-16 -4.26325641e-16 -4.73695157e-16]
[1. 1. 1. 1.]

In [286]:
# Statistics

In [287]:
print("Minimum:", np.min(features))
print("Maximum:", np.max(features))
print("Mean:", np.mean(features))
print("Standard Deviation:", np.std(features))

Minimum: 0.1
Maximum: 7.9
Mean: 3.4644999999999997
Standard Deviation: 1.9738430577598278

In [288]:
print(features.min())
print(features.max())
print(features.mean())
print(features.std())

0.1
7.9
3.4644999999999997
1.9738430577598278

In [289]:
feature_min = np.min(features, axis=0)
feature_max = np.max(features, axis=0)
feature_mean = np.mean(features, axis=0)
feature_std = np.std(features, axis=0)

print("Minimums:", feature_min)
print("Maximums:", feature_max)
print("Means:", feature_mean)
print("Standard Deviations:", feature_std)

Minimums: [4.3 2.  1.  0.1]
Maximums: [7.9 4.4 6.9 2.5]
Means: [5.84333333 3.05733333 3.758      1.19933333]
Standard Deviations: [0.82530129 0.43441097 1.75940407 0.75969263]

In [290]:
sample_min = np.min(features, axis=1)
sample_max = np.max(features, axis=1)
sample_mean = np.mean(features, axis=1)
sample_std = np.std(features, axis=1)

print("Sample Minimums:", sample_min[:5])  # Print first 5 sample minimums
print("Sample Maximums:", sample_max[:5])  # Print first 5 sample maximums
print("Sample Means:", sample_mean[:5])  # Print first 5 sample means
print("Sample Standard Deviations:", sample_std[:5])  # Print first 5 sample standard deviations

Sample Minimums: [0.2 0.2 0.2 0.2 0.2]
Sample Maximums: [5.1 4.9 4.7 4.6 5. ]
Sample Means: [2.55  2.375 2.35  2.35  2.55 ]
Sample Standard Deviations: [1.88745861 1.76405074 1.72988439 1.65604952 1.86748494]

In [291]:
feature_names = [
    "Sepal Length",
    "Sepal Width",
    "Petal Length",
    "Petal Width"
]

statistics = pd.DataFrame({
    "Feature": feature_names,
    "Minimum": feature_min,
    "Maximum": feature_max,
    "Mean": feature_mean,
    "Std": feature_std
})

statistics

        Feature  Minimum  Maximum      Mean       Std
0  Sepal Length      4.3      7.9  5.843333  0.825301
1   Sepal Width      2.0      4.4  3.057333  0.434411
2  Petal Length      1.0      6.9  3.758000  1.759404
3   Petal Width      0.1      2.5  1.199333  0.759693

In [292]:
# exercise
# 1. Find the feature with the largest mean.
# 2. Find the feature with the smallest standard deviation.
# 3. Compute the range (max - min) for each feature.
# 4. Find the flower with the largest average measurement.
# 5. Find the flower with the smallest average measurement.

In [293]:
# 1
largest_mean_index = np.argmax(feature_mean)

print("Feature with the largest mean:", feature_names[largest_mean_index])

Feature with the largest mean: Sepal Length

In [294]:
# 2
smallest_std_index = np.argmin(feature_std)

print("Feature with the smallest standard deviation:", feature_names[smallest_std_index])

Feature with the smallest standard deviation: Sepal Width

In [295]:
# 3
features_max = np.max(features, axis=0)
features_min = np.min(features, axis=0)

feature_range = features_max - features_min
print("Feature Ranges:", feature_range)

Feature Ranges: [3.6 2.4 5.9 2.4]

In [296]:
# 4
flower_means = np.mean(features, axis=1)
largest_average_index = np.argmax(flower_means)

print("Flower with the largest average measurement (index):", largest_average_index)

Flower with the largest average measurement (index): 117

In [297]:
# 5
smallest_average_index = np.argmin(flower_means)

print("Flower with the smallest average measurement (index):", smallest_average_index)

Flower with the smallest average measurement (index): 41

# Impelenting equvilant code using python

In [298]:
python_features = features.tolist()

In [299]:
python_features[0]

[5.1, 3.5, 1.4, 0.2]

In [300]:
np.min(features)

np.float64(0.1)

In [301]:
min = 1000
for feature in python_features:
    for value in feature:
        if value < min:
            min = value
print("Minimum value in the dataset:", min)

Minimum value in the dataset: 0.1

In [302]:
max = -1000
for feature in python_features:
    for value in feature:
        if value > max:
            max = value
print("Maximum value in the dataset:", max)

Maximum value in the dataset: 7.9

In [303]:
total = 0
count = 0

for feature in python_features:
    for value in feature:
        total += value
        count += 1

average = total / count
print("Average value in the dataset:", average)

Average value in the dataset: 3.4644999999999975

In [304]:
# std = variance**0.5 -> variance = sum((value - average) ** 2 / count

sum_squared_diff = 0

for feature in python_features:
    for value in feature:
        sum_squared_diff += (value - average) ** 2

variance = sum_squared_diff / count
std = variance ** 0.5

print("Standard Deviation of the dataset:", std)

Standard Deviation of the dataset: 1.9738430577598252

In [305]:
# finding the mean of each feature using python

num_rows = len(python_features)
num_cols = len(python_features[0])

feature_means = []

for col in range(num_cols):
    col_sum = 0
    for row in range(num_rows):
        col_sum += python_features[row][col]
    feature_means.append(col_sum / num_rows)

print("Feature Means:", feature_means)

Feature Means: [5.843333333333335, 3.057333333333334, 3.7580000000000027, 1.199333333333334]

In [306]:
# same for col max, min, std

In [307]:
# col max

col_maxes = []

for col in range(num_cols):
    col_max = python_features[0][col]
    for row in range(1, num_rows):
        if python_features[row][col] > col_max:
            col_max = python_features[row][col]
    col_maxes.append(col_max)

print("Column Maxes:", col_maxes)

Column Maxes: [7.9, 4.4, 6.9, 2.5]

In [308]:
# Numerical operations using python

# features + 1

added_features = []
for feature in python_features:
    added_row = []
    for value in feature:
        added_row.append(value + 1)
    added_features.append(added_row)

print("Added Features:", added_features)

Added Features: [[6.1, 4.5, 2.4, 1.2], [5.9, 4.0, 2.4, 1.2], [5.7, 4.2, 2.3, 1.2], [5.6, 4.1, 2.5, 1.2], [6.0, 4.6, 2.4, 1.2], [6.4, 4.9, 2.7, 1.4], [5.6, 4.4, 2.4, 1.3], [6.0, 4.4, 2.5, 1.2], [5.4, 3.9, 2.4, 1.2], [5.9, 4.1, 2.5, 1.1], [6.4, 4.7, 2.5, 1.2], [5.8, 4.4, 2.6, 1.2], [5.8, 4.0, 2.4, 1.1], [5.3, 4.0, 2.1, 1.1], [6.8, 5.0, 2.2, 1.2], [6.7, 5.4, 2.5, 1.4], [6.4, 4.9, 2.3, 1.4], [6.1, 4.5, 2.4, 1.3], [6.7, 4.8, 2.7, 1.3], [6.1, 4.8, 2.5, 1.3], [6.4, 4.4, 2.7, 1.2], [6.1, 4.7, 2.5, 1.4], [5.6, 4.6, 2.0, 1.2], [6.1, 4.3, 2.7, 1.5], [5.8, 4.4, 2.9, 1.2], [6.0, 4.0, 2.6, 1.2], [6.0, 4.4, 2.6, 1.4], [6.2, 4.5, 2.5, 1.2], [6.2, 4.4, 2.4, 1.2], [5.7, 4.2, 2.6, 1.2], [5.8, 4.1, 2.6, 1.2], [6.4, 4.4, 2.5, 1.4], [6.2, 5.1, 2.5, 1.1], [6.5, 5.2, 2.4, 1.2], [5.9, 4.1, 2.5, 1.2], [6.0, 4.2, 2.2, 1.2], [6.5, 4.5, 2.3, 1.2], [5.9, 4.6, 2.4, 1.1], [5.4, 4.0, 2.3, 1.2], [6.1, 4.4, 2.5, 1.2], [6.0, 4.5, 2.3, 1.3], [5.5, 3.3, 2.3, 1.3], [5.4, 4.2, 2.3, 1.2], [6.0, 4.5, 2.6, 1.6], [6.1, 4.8, 2.9, 1.4], [5.8, 4.0, 2.4, 1.3], [6.1, 4.8, 2.6, 1.2], [5.6, 4.2, 2.4, 1.2], [6.3, 4.7, 2.5, 1.2], [6.0, 4.3, 2.4, 1.2], [8.0, 4.2, 5.7, 2.4], [7.4, 4.2, 5.5, 2.5], [7.9, 4.1, 5.9, 2.5], [6.5, 3.3, 5.0, 2.3], [7.5, 3.8, 5.6, 2.5], [6.7, 3.8, 5.5, 2.3], [7.3, 4.3, 5.7, 2.6], [5.9, 3.4, 4.3, 2.0], [7.6, 3.9, 5.6, 2.3], [6.2, 3.7, 4.9, 2.4], [6.0, 3.0, 4.5, 2.0], [6.9, 4.0, 5.2, 2.5], [7.0, 3.2, 5.0, 2.0], [7.1, 3.9, 5.7, 2.4], [6.6, 3.9, 4.6, 2.3], [7.7, 4.1, 5.4, 2.4], [6.6, 4.0, 5.5, 2.5], [6.8, 3.7, 5.1, 2.0], [7.2, 3.2, 5.5, 2.5], [6.6, 3.5, 4.9, 2.1], [6.9, 4.2, 5.8, 2.8], [7.1, 3.8, 5.0, 2.3], [7.3, 3.5, 5.9, 2.5], [7.1, 3.8, 5.7, 2.2], [7.4, 3.9, 5.3, 2.3], [7.6, 4.0, 5.4, 2.4], [7.8, 3.8, 5.8, 2.4], [7.7, 4.0, 6.0, 2.7], [7.0, 3.9, 5.5, 2.5], [6.7, 3.6, 4.5, 2.0], [6.5, 3.4, 4.8, 2.1], [6.5, 3.4, 4.7, 2.0], [6.8, 3.7, 4.9, 2.2], [7.0, 3.7, 6.1, 2.6], [6.4, 4.0, 5.5, 2.5], [7.0, 4.4, 5.5, 2.6], [7.7, 4.1, 5.7, 2.5], [7.3, 3.3, 5.4, 2.3], [6.6, 4.0, 5.1, 2.3], [6.5, 3.5, 5.0, 2.3], [6.5, 3.6, 5.4, 2.2], [7.1, 4.0, 5.6, 2.4], [6.8, 3.6, 5.0, 2.2], [6.0, 3.3, 4.3, 2.0], [6.6, 3.7, 5.2, 2.3], [6.7, 4.0, 5.2, 2.2], [6.7, 3.9, 5.2, 2.3], [7.2, 3.9, 5.3, 2.3], [6.1, 3.5, 4.0, 2.1], [6.7, 3.8, 5.1, 2.3], [7.3, 4.3, 7.0, 3.5], [6.8, 3.7, 6.1, 2.9], [8.1, 4.0, 6.9, 3.1], [7.3, 3.9, 6.6, 2.8], [7.5, 4.0, 6.8, 3.2], [8.6, 4.0, 7.6, 3.1], [5.9, 3.5, 5.5, 2.7], [8.3, 3.9, 7.3, 2.8], [7.7, 3.5, 6.8, 2.8], [8.2, 4.6, 7.1, 3.5], [7.5, 4.2, 6.1, 3.0], [7.4, 3.7, 6.3, 2.9], [7.8, 4.0, 6.5, 3.1], [6.7, 3.5, 6.0, 3.0], [6.8, 3.8, 6.1, 3.4], [7.4, 4.2, 6.3, 3.3], [7.5, 4.0, 6.5, 2.8], [8.7, 4.8, 7.7, 3.2], [8.7, 3.6, 7.9, 3.3], [7.0, 3.2, 6.0, 2.5], [7.9, 4.2, 6.7, 3.3], [6.6, 3.8, 5.9, 3.0], [8.7, 3.8, 7.7, 3.0], [7.3, 3.7, 5.9, 2.8], [7.7, 4.3, 6.7, 3.1], [8.2, 4.2, 7.0, 2.8], [7.2, 3.8, 5.8, 2.8], [7.1, 4.0, 5.9, 2.8], [7.4, 3.8, 6.6, 3.1], [8.2, 4.0, 6.8, 2.6], [8.4, 3.8, 7.1, 2.9], [8.9, 4.8, 7.4, 3.0], [7.4, 3.8, 6.6, 3.2], [7.3, 3.8, 6.1, 2.5], [7.1, 3.6, 6.6, 2.4], [8.7, 4.0, 7.1, 3.3], [7.3, 4.4, 6.6, 3.4], [7.4, 4.1, 6.5, 2.8], [7.0, 4.0, 5.8, 2.8], [7.9, 4.1, 6.4, 3.1], [7.7, 4.1, 6.6, 3.4], [7.9, 4.1, 6.1, 3.3], [6.8, 3.7, 6.1, 2.9], [7.8, 4.2, 6.9, 3.3], [7.7, 4.3, 6.7, 3.5], [7.7, 4.0, 6.2, 3.3], [7.3, 3.5, 6.0, 2.9], [7.5, 4.0, 6.2, 3.0], [7.2, 4.4, 6.4, 3.3], [6.9, 4.0, 6.1, 2.8]]

In [309]:
# boolean filtering using python

filtered_features = []

for feature in python_features:
    if feature[0] > 5:
        filtered_features.append(feature)

print("Filtered Features:", filtered_features)

Filtered Features: [[5.1, 3.5, 1.4, 0.2], [5.4, 3.9, 1.7, 0.4], [5.4, 3.7, 1.5, 0.2], [5.8, 4.0, 1.2, 0.2], [5.7, 4.4, 1.5, 0.4], [5.4, 3.9, 1.3, 0.4], [5.1, 3.5, 1.4, 0.3], [5.7, 3.8, 1.7, 0.3], [5.1, 3.8, 1.5, 0.3], [5.4, 3.4, 1.7, 0.2], [5.1, 3.7, 1.5, 0.4], [5.1, 3.3, 1.7, 0.5], [5.2, 3.5, 1.5, 0.2], [5.2, 3.4, 1.4, 0.2], [5.4, 3.4, 1.5, 0.4], [5.2, 4.1, 1.5, 0.1], [5.5, 4.2, 1.4, 0.2], [5.5, 3.5, 1.3, 0.2], [5.1, 3.4, 1.5, 0.2], [5.1, 3.8, 1.9, 0.4], [5.1, 3.8, 1.6, 0.2], [5.3, 3.7, 1.5, 0.2], [7.0, 3.2, 4.7, 1.4], [6.4, 3.2, 4.5, 1.5], [6.9, 3.1, 4.9, 1.5], [5.5, 2.3, 4.0, 1.3], [6.5, 2.8, 4.6, 1.5], [5.7, 2.8, 4.5, 1.3], [6.3, 3.3, 4.7, 1.6], [6.6, 2.9, 4.6, 1.3], [5.2, 2.7, 3.9, 1.4], [5.9, 3.0, 4.2, 1.5], [6.0, 2.2, 4.0, 1.0], [6.1, 2.9, 4.7, 1.4], [5.6, 2.9, 3.6, 1.3], [6.7, 3.1, 4.4, 1.4], [5.6, 3.0, 4.5, 1.5], [5.8, 2.7, 4.1, 1.0], [6.2, 2.2, 4.5, 1.5], [5.6, 2.5, 3.9, 1.1], [5.9, 3.2, 4.8, 1.8], [6.1, 2.8, 4.0, 1.3], [6.3, 2.5, 4.9, 1.5], [6.1, 2.8, 4.7, 1.2], [6.4, 2.9, 4.3, 1.3], [6.6, 3.0, 4.4, 1.4], [6.8, 2.8, 4.8, 1.4], [6.7, 3.0, 5.0, 1.7], [6.0, 2.9, 4.5, 1.5], [5.7, 2.6, 3.5, 1.0], [5.5, 2.4, 3.8, 1.1], [5.5, 2.4, 3.7, 1.0], [5.8, 2.7, 3.9, 1.2], [6.0, 2.7, 5.1, 1.6], [5.4, 3.0, 4.5, 1.5], [6.0, 3.4, 4.5, 1.6], [6.7, 3.1, 4.7, 1.5], [6.3, 2.3, 4.4, 1.3], [5.6, 3.0, 4.1, 1.3], [5.5, 2.5, 4.0, 1.3], [5.5, 2.6, 4.4, 1.2], [6.1, 3.0, 4.6, 1.4], [5.8, 2.6, 4.0, 1.2], [5.6, 2.7, 4.2, 1.3], [5.7, 3.0, 4.2, 1.2], [5.7, 2.9, 4.2, 1.3], [6.2, 2.9, 4.3, 1.3], [5.1, 2.5, 3.0, 1.1], [5.7, 2.8, 4.1, 1.3], [6.3, 3.3, 6.0, 2.5], [5.8, 2.7, 5.1, 1.9], [7.1, 3.0, 5.9, 2.1], [6.3, 2.9, 5.6, 1.8], [6.5, 3.0, 5.8, 2.2], [7.6, 3.0, 6.6, 2.1], [7.3, 2.9, 6.3, 1.8], [6.7, 2.5, 5.8, 1.8], [7.2, 3.6, 6.1, 2.5], [6.5, 3.2, 5.1, 2.0], [6.4, 2.7, 5.3, 1.9], [6.8, 3.0, 5.5, 2.1], [5.7, 2.5, 5.0, 2.0], [5.8, 2.8, 5.1, 2.4], [6.4, 3.2, 5.3, 2.3], [6.5, 3.0, 5.5, 1.8], [7.7, 3.8, 6.7, 2.2], [7.7, 2.6, 6.9, 2.3], [6.0, 2.2, 5.0, 1.5], [6.9, 3.2, 5.7, 2.3], [5.6, 2.8, 4.9, 2.0], [7.7, 2.8, 6.7, 2.0], [6.3, 2.7, 4.9, 1.8], [6.7, 3.3, 5.7, 2.1], [7.2, 3.2, 6.0, 1.8], [6.2, 2.8, 4.8, 1.8], [6.1, 3.0, 4.9, 1.8], [6.4, 2.8, 5.6, 2.1], [7.2, 3.0, 5.8, 1.6], [7.4, 2.8, 6.1, 1.9], [7.9, 3.8, 6.4, 2.0], [6.4, 2.8, 5.6, 2.2], [6.3, 2.8, 5.1, 1.5], [6.1, 2.6, 5.6, 1.4], [7.7, 3.0, 6.1, 2.3], [6.3, 3.4, 5.6, 2.4], [6.4, 3.1, 5.5, 1.8], [6.0, 3.0, 4.8, 1.8], [6.9, 3.1, 5.4, 2.1], [6.7, 3.1, 5.6, 2.4], [6.9, 3.1, 5.1, 2.3], [5.8, 2.7, 5.1, 1.9], [6.8, 3.2, 5.9, 2.3], [6.7, 3.3, 5.7, 2.5], [6.7, 3.0, 5.2, 2.3], [6.3, 2.5, 5.0, 1.9], [6.5, 3.0, 5.2, 2.0], [6.2, 3.4, 5.4, 2.3], [5.9, 3.0, 5.1, 1.8]]

### Compare the execution time systematically (through multiple repeats and then taking the mean and std) between writing the previous computations in pure Python and in NumPy. In a text/markdown block (if you have a notebook) or in a comment (if you have a script), write your observations and why is NumPy faster than pure Python?

In [312]:
import timeit


def numpy_statistics():
    return (
        np.min(features),
        np.max(features),
        np.mean(features),
        np.std(features),
    )


def python_statistics():
    total = 0
    count = 0
    minimum = python_features[0][0]
    maximum = python_features[0][0]

    for row in python_features:
        for value in row:
            total += value
            count += 1

            if value < minimum:
                minimum = value

            if value > maximum:
                maximum = value

    mean = total / count
    squared_difference_sum = 0

    for row in python_features:
        for value in row:
            squared_difference_sum += (value - mean) ** 2

    standard_deviation = (squared_difference_sum / count) ** 0.5

    return minimum, maximum, mean, standard_deviation


repeats = 10
executions_per_repeat = 10000

numpy_times = timeit.repeat(
    numpy_statistics,
    repeat=repeats,
    number=executions_per_repeat,
)

python_times = timeit.repeat(
    python_statistics,
    repeat=repeats,
    number=executions_per_repeat,
)

numpy_times = np.array(numpy_times) / executions_per_repeat
python_times = np.array(python_times) / executions_per_repeat

print("NumPy result:", numpy_statistics())
print("Python result:", python_statistics())

print(
    f"NumPy:  {numpy_times.mean():.8f} ± "
    f"{numpy_times.std():.8f} seconds"
)

print(
    f"Python: {python_times.mean():.8f} ± "
    f"{python_times.std():.8f} seconds"
)

print(
    f"Speedup: {python_times.mean() / numpy_times.mean():.2f}x"
)

NumPy result: (np.float64(0.1), np.float64(7.9), np.float64(3.4644999999999997), np.float64(1.9738430577598278))
Python result: (0.1, 7.9, 3.4644999999999975, 1.9738430577598252)
NumPy:  0.00001103 ± 0.00000054 seconds
Python: 0.00004441 ± 0.00000044 seconds
Speedup: 4.03x

### From the results it shows that numpy doing the same processes took a fourth of the time it takes for the same process to happen when impemented in pure python doing the same processes and I assume the reason for that is the way is because numpy stores only the same data type for all items in it while using pure python which stores each item as an entire object and has a pointer to it in a list so this will take time at each item to go to the pointed to object and doing an operation on it and then storing a new pointer again.