# Baseline model comparison

Train Logistic Regression and Linear SVM on the training split and compare their performance on the internal validation split.

In [1]:
from pathlib import Path
import sys
import time

import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    precision_recall_fscore_support,
)

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

from src.train import build_logistic_regression_pipeline

In [2]:
TRAIN_PATH = PROJECT_ROOT / "data" / "processed" / "train_clean.csv"
VALIDATION_PATH = PROJECT_ROOT / "data" / "processed" / "validation_clean.csv"

train_df = pd.read_csv(TRAIN_PATH)
validation_df = pd.read_csv(VALIDATION_PATH)

print("Training shape:", train_df.shape)
print("Validation shape:", validation_df.shape)

display(train_df.head())

Training shape: (50301, 4)
Validation shape: (12682, 4)

,tweet_id,entity,sentiment,text
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,i am coming to the borders and i will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...

In [3]:
X_train = train_df["text"]
y_train = train_df["sentiment"]

X_validation = validation_df["text"]
y_validation = validation_df["sentiment"]

print("Training samples:", len(X_train))
print("Validation samples:", len(X_validation))

Training samples: 50301
Validation samples: 12682

In [4]:
baseline_model = build_logistic_regression_pipeline()

baseline_model

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(lowercase=False, max_df=0.98,
                                 max_features=100000, min_df=2,
                                 ngram_range=(1, 2),
                                 preprocessor=<function normalize_text at 0x0000026E632CC220>,
                                 sublinear_tf=True, token_pattern=None,
                                 tokenizer=<function tokenize_text at 0x0000026E632ECD60>)),
                ('classifier',
                 LogisticRegression(max_iter=1000, random_state=42))])

In [5]:
print(baseline_model.named_steps.keys())

dict_keys(['tfidf', 'classifier'])

In [6]:
start_time = time.perf_counter()

baseline_model.fit(X_train, y_train)

training_time = time.perf_counter() - start_time

print(f"Training time: {training_time:.2f} seconds")

Training time: 15.28 seconds

In [7]:
start_time = time.perf_counter()

validation_predictions = baseline_model.predict(X_validation)

prediction_time = time.perf_counter() - start_time

print(f"Prediction time: {prediction_time:.4f} seconds")

Prediction time: 1.7348 seconds

In [8]:
accuracy = accuracy_score(
    y_validation,
    validation_predictions,
)

macro_precision, macro_recall, macro_f1, _ = (
    precision_recall_fscore_support(
        y_validation,
        validation_predictions,
        average="macro",
        zero_division=0,
    )
)

weighted_precision, weighted_recall, weighted_f1, _ = (
    precision_recall_fscore_support(
        y_validation,
        validation_predictions,
        average="weighted",
        zero_division=0,
    )
)

baseline_metrics = pd.DataFrame(
    {
        "metric": [
            "accuracy",
            "macro_precision",
            "macro_recall",
            "macro_f1",
            "weighted_precision",
            "weighted_recall",
            "weighted_f1",
            "training_time_seconds",
            "prediction_time_seconds",
        ],
        "value": [
            accuracy,
            macro_precision,
            macro_recall,
            macro_f1,
            weighted_precision,
            weighted_recall,
            weighted_f1,
            training_time,
            prediction_time,
        ],
    }
)

baseline_metrics

                    metric      value
0                 accuracy   0.573175
1          macro_precision   0.547069
2             macro_recall   0.539104
3                 macro_f1   0.536343
4       weighted_precision   0.560675
5          weighted_recall   0.573175
6              weighted_f1   0.561306
7    training_time_seconds  15.284238
8  prediction_time_seconds   1.734795

In [9]:
report = classification_report(
    y_validation,
    validation_predictions,
    zero_division=0,
)

print(report)

              precision    recall  f1-score   support

  Irrelevant       0.43      0.26      0.32      2228
    Negative       0.60      0.74      0.66      3898
     Neutral       0.55      0.54      0.55      3072
    Positive       0.60      0.62      0.61      3484

    accuracy                           0.57     12682
   macro avg       0.55      0.54      0.54     12682
weighted avg       0.56      0.57      0.56     12682

In [10]:
labels = sorted(y_validation.unique())

confusion = confusion_matrix(
    y_validation,
    validation_predictions,
    labels=labels,
)

confusion_df = pd.DataFrame(
    confusion,
    index=[f"actual_{label}" for label in labels],
    columns=[f"predicted_{label}" for label in labels],
)

confusion_df

,predicted_Irrelevant,predicted_Negative,predicted_Neutral,predicted_Positive
actual_Irrelevant,578,629,473,548
actual_Negative,229,2871,413,385
actual_Neutral,249,679,1663,481
actual_Positive,301,576,450,2157

In [11]:
prediction_results = validation_df[
    ["tweet_id", "entity", "text", "sentiment"]
].copy()

prediction_results["predicted_sentiment"] = (
    validation_predictions
)

prediction_results["correct"] = (
    prediction_results["sentiment"]
    == prediction_results["predicted_sentiment"]
)

mistakes = prediction_results[
    ~prediction_results["correct"]
]

print("Correct predictions:", prediction_results["correct"].sum())
print("Incorrect predictions:", len(mistakes))

display(mistakes.head(20))

Correct predictions: 7269
Incorrect predictions: 5413

,tweet_id,entity,text,sentiment,predicted_sentiment,correct
16,2413,Borderlands,imma probably got some video tps in a bit. tha...,Positive,Neutral,False
17,2415,Borderlands,fuck yessssssss .,Positive,Negative,False
19,2415,Borderlands,fuck yessssssss.,Positive,Negative,False
20,2415,Borderlands,fuck yessssssss,Positive,Negative,False
21,2415,Borderlands,a fuck... yessssssss.,Positive,Negative,False
22,2415,Borderlands,fuck you.,Positive,Negative,False
29,2424,Borderlands,how the hell are we into halloween month alrea...,Irrelevant,Negative,False
30,2424,Borderlands,how the hell are we already into halloween mon...,Irrelevant,Negative,False
31,2424,Borderlands,how the hell are we already in halloween month?!.,Irrelevant,Negative,False
32,2424,Borderlands,how the hell are march into halloween month al...,Irrelevant,Negative,False
33,2424,Borderlands,how the hell are pulling we into halloween mon...,Irrelevant,Negative,False
34,2424,Borderlands,in the hell are we into halloween month alread...,Irrelevant,Negative,False
39,2455,Borderlands,big hearty congratulations to my families on y...,Positive,Irrelevant,False
42,2455,Borderlands,big special congratulations to my fellow famil...,Positive,Irrelevant,False
45,2461,Borderlands,i feel like i accomplished something here even...,Positive,Negative,False
46,2461,Borderlands,i have the feeling that i have achieved someth...,Positive,Irrelevant,False
47,2461,Borderlands,"i feel like i've spilled something here, when ...",Positive,Negative,False
48,2461,Borderlands,i feel like i accomplished something here even...,Positive,Negative,False
49,2461,Borderlands,i feel like i accomplished something here even...,Positive,Negative,False
51,2468,Borderlands,"i'm so damn sorry for the stupid short stream,...",Neutral,Irrelevant,False

In [12]:
RESULTS_DIR = PROJECT_ROOT / "reports" / "results"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

In [13]:
report_dict = classification_report(
    y_validation,
    validation_predictions,
    output_dict=True,
    zero_division=0,
)

report_df = pd.DataFrame(report_dict).transpose()

report_df.to_csv(
    RESULTS_DIR / "baseline_logistic_regression_report.csv"
)

In [14]:
from pathlib import Path
import sys
import time

import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    precision_recall_fscore_support,
)

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

from src.train import build_svm_pipeline

In [15]:
TRAIN_PATH = PROJECT_ROOT / "data" / "processed" / "train_clean.csv"
VALIDATION_PATH = PROJECT_ROOT / "data" / "processed" / "validation_clean.csv"

train_df = pd.read_csv(TRAIN_PATH)
validation_df = pd.read_csv(VALIDATION_PATH)

print("Training shape:", train_df.shape)
print("Validation shape:", validation_df.shape)

Training shape: (50301, 4)
Validation shape: (12682, 4)

In [16]:
X_train = train_df["text"]
y_train = train_df["sentiment"]

X_validation = validation_df["text"]
y_validation = validation_df["sentiment"]

print("Training samples:", len(X_train))
print("Validation samples:", len(X_validation))

Training samples: 50301
Validation samples: 12682

In [17]:
svm_model = build_svm_pipeline()

svm_model

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(lowercase=False, max_df=0.98,
                                 max_features=100000, min_df=2,
                                 ngram_range=(1, 2),
                                 preprocessor=<function normalize_text at 0x0000026E632CC220>,
                                 sublinear_tf=True, token_pattern=None,
                                 tokenizer=<function tokenize_text at 0x0000026E632ECD60>)),
                ('classifier', LinearSVC(random_state=42))])

In [18]:
start_time = time.perf_counter()

svm_model.fit(X_train, y_train)

training_time = time.perf_counter() - start_time

print(f"Training time: {training_time:.2f} seconds")

Training time: 9.58 seconds

In [19]:
start_time = time.perf_counter()

validation_predictions = svm_model.predict(X_validation)

prediction_time = time.perf_counter() - start_time

print(f"Prediction time: {prediction_time:.4f} seconds")

Prediction time: 1.6811 seconds

In [20]:
accuracy = accuracy_score(
    y_validation,
    validation_predictions,
)

macro_precision, macro_recall, macro_f1, _ = (
    precision_recall_fscore_support(
        y_validation,
        validation_predictions,
        average="macro",
        zero_division=0,
    )
)

weighted_precision, weighted_recall, weighted_f1, _ = (
    precision_recall_fscore_support(
        y_validation,
        validation_predictions,
        average="weighted",
        zero_division=0,
    )
)

svm_metrics = pd.DataFrame(
    {
        "metric": [
            "accuracy",
            "macro_precision",
            "macro_recall",
            "macro_f1",
            "weighted_precision",
            "weighted_recall",
            "weighted_f1",
            "training_time_seconds",
            "prediction_time_seconds",
        ],
        "value": [
            accuracy,
            macro_precision,
            macro_recall,
            macro_f1,
            weighted_precision,
            weighted_recall,
            weighted_f1,
            training_time,
            prediction_time,
        ],
    }
)

svm_metrics

                    metric     value
0                 accuracy  0.545340
1          macro_precision  0.518786
2             macro_recall  0.514926
3                 macro_f1  0.513174
4       weighted_precision  0.534098
5          weighted_recall  0.545340
6              weighted_f1  0.536523
7    training_time_seconds  9.582194
8  prediction_time_seconds  1.681124

In [21]:
report = classification_report(
    y_validation,
    validation_predictions,
    zero_division=0,
)

print(report)

              precision    recall  f1-score   support

  Irrelevant       0.39      0.27      0.32      2228
    Negative       0.59      0.70      0.64      3898
     Neutral       0.53      0.51      0.52      3072
    Positive       0.57      0.58      0.57      3484

    accuracy                           0.55     12682
   macro avg       0.52      0.51      0.51     12682
weighted avg       0.53      0.55      0.54     12682

In [22]:
labels = sorted(y_validation.unique())

confusion = confusion_matrix(
    y_validation,
    validation_predictions,
    labels=labels,
)

confusion_df = pd.DataFrame(
    confusion,
    index=[f"actual_{label}" for label in labels],
    columns=[f"predicted_{label}" for label in labels],
)

confusion_df

,predicted_Irrelevant,predicted_Negative,predicted_Neutral,predicted_Positive
actual_Irrelevant,605,604,447,572
actual_Negative,278,2733,453,434
actual_Neutral,339,657,1560,516
actual_Positive,344,615,507,2018

In [23]:
prediction_results = validation_df[
    ["tweet_id", "entity", "text", "sentiment"]
].copy()

prediction_results["predicted_sentiment"] = (
    validation_predictions
)

prediction_results["correct"] = (
    prediction_results["sentiment"]
    == prediction_results["predicted_sentiment"]
)

mistakes = prediction_results[
    ~prediction_results["correct"]
]

print("Correct predictions:", prediction_results["correct"].sum())
print("Incorrect predictions:", len(mistakes))

display(mistakes.head(20))

Correct predictions:

 6916
Incorrect predictions: 5766

,tweet_id,entity,text,sentiment,predicted_sentiment,correct
16,2413,Borderlands,imma probably got some video tps in a bit. tha...,Positive,Neutral,False
17,2415,Borderlands,fuck yessssssss .,Positive,Negative,False
19,2415,Borderlands,fuck yessssssss.,Positive,Negative,False
20,2415,Borderlands,fuck yessssssss,Positive,Negative,False
21,2415,Borderlands,a fuck... yessssssss.,Positive,Negative,False
22,2415,Borderlands,fuck you.,Positive,Negative,False
30,2424,Borderlands,how the hell are we already into halloween mon...,Irrelevant,Negative,False
31,2424,Borderlands,how the hell are we already in halloween month?!.,Irrelevant,Negative,False
39,2455,Borderlands,big hearty congratulations to my families on y...,Positive,Irrelevant,False
41,2455,Borderlands,big heartfelt congratulations to my @ playapex...,Positive,Negative,False
42,2455,Borderlands,big special congratulations to my fellow famil...,Positive,Irrelevant,False
45,2461,Borderlands,i feel like i accomplished something here even...,Positive,Negative,False
46,2461,Borderlands,i have the feeling that i have achieved someth...,Positive,Irrelevant,False
47,2461,Borderlands,"i feel like i've spilled something here, when ...",Positive,Negative,False
48,2461,Borderlands,i feel like i accomplished something here even...,Positive,Negative,False
49,2461,Borderlands,i feel like i accomplished something here even...,Positive,Neutral,False
50,2461,Borderlands,i feel like i accomplished something beautiful...,Positive,Neutral,False
51,2468,Borderlands,"i'm so damn sorry for the stupid short stream,...",Neutral,Negative,False
52,2468,Borderlands,"i'm so damn sorry for the stupid short stream,...",Neutral,Irrelevant,False
53,2468,Borderlands,"i'm so damn sorry for the stupid short stream,...",Neutral,Irrelevant,False

In [24]:
RESULTS_DIR = PROJECT_ROOT / "reports" / "results"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

report_dict = classification_report(
    y_validation,
    validation_predictions,
    output_dict=True,
    zero_division=0,
)
report_df = pd.DataFrame(report_dict).transpose()
report_df.to_csv(RESULTS_DIR / "baseline_svm_report.csv")

The saved report contains the per-class validation metrics. Individual predictions remain in the notebook and are not stored as a large result file.

# Baseline comparison

In [25]:
logistic_values = baseline_metrics.set_index("metric")["value"]
svm_values = svm_metrics.set_index("metric")["value"]

comparison = pd.DataFrame([
    {
        "model": "Baseline Logistic Regression",
        "accuracy": logistic_values["accuracy"],
        "macro_precision": logistic_values["macro_precision"],
        "macro_recall": logistic_values["macro_recall"],
        "macro_f1": logistic_values["macro_f1"],
        "weighted_f1": logistic_values["weighted_f1"],
        "training_or_search_time_seconds": logistic_values["training_time_seconds"],
    },
    {
        "model": "Baseline Linear SVM",
        "accuracy": svm_values["accuracy"],
        "macro_precision": svm_values["macro_precision"],
        "macro_recall": svm_values["macro_recall"],
        "macro_f1": svm_values["macro_f1"],
        "weighted_f1": svm_values["weighted_f1"],
        "training_or_search_time_seconds": svm_values["training_time_seconds"],
    },
])

comparison

,model,accuracy,macro_precision,macro_recall,macro_f1,weighted_f1,training_or_search_time_seconds
0,Baseline Logistic Regression,0.573175,0.547069,0.539104,0.536343,0.561306,15.284238
1,Baseline Linear SVM,0.545340,0.518786,0.514926,0.513174,0.536523,9.582194

In [26]:
comparison.to_csv(
    PROJECT_ROOT / "reports" / "results" / "baseline_model_comparison.csv",
    index=False,
)

The supplied test split remains untouched during baseline comparison and hyperparameter selection.